import { NextResponse } from "next/server";
import type { Firestore } from "firebase-admin/firestore";
import { getAdminServices } from "@/infrastructure/firebase/admin";
import type { BusinessMember } from "@/types";
export const runtime="nodejs";
const err=(message:string,status=400)=>NextResponse.json({success:false,error:message},{status});
async function auth(request:Request){const{auth,db}=getAdminServices();const h=request.headers.get("authorization")||"";if(!h.startsWith("Bearer "))throw new Error("Authentication is required.");return{db,token:await auth.verifyIdToken(h.slice(7))};}
async function member(db:Firestore,businessId:string,uid:string){const s=await db.collection("businesses").doc(businessId).collection("members").doc(uid).get();if(!s.exists)throw Object.assign(new Error("You are not a member of this business."),{statusCode:403});const m=s.data() as BusinessMember;if(m.status!=="active")throw Object.assign(new Error("Your business membership is not active."),{statusCode:403});return m;}
function can(m:BusinessMember,a:"view"|"create"|"edit"){return m.role==="owner"||m.role==="admin"||!!m.permissions?.items?.[a];}
const text=(v:unknown)=>String(v??"").trim();
function amount(v:unknown,n:string){const x=Number(v??0);if(!Number.isFinite(x)||x<0||!Number.isSafeInteger(x))throw new Error(`${n} must be a non-negative amount in minor units.`);return x;}
function rate(v:unknown){const x=Number(v??0);if(!Number.isFinite(x)||x<0||x>100)throw new Error("GST rate must be between 0 and 100.");return x;}
function qty(v:unknown,n:string){const x=Number(v??0);if(!Number.isFinite(x)||x<0)throw new Error(`${n} must be a non-negative quantity.`);return x;}
function itemRecord(body:Record<string,unknown>,existing?:Record<string,unknown>){const itemType=body.itemType===undefined?String(existing?.itemType??"product"):text(body.itemType).toLowerCase();if(!["product","service"].includes(itemType))throw new Error("Item type must be Product or Service.");return{businessId:String(existing?.businessId??body.businessId),itemId:String(existing?.itemId??body.itemId),name:body.name===undefined?String(existing?.name??""):text(body.name),code:body.code===undefined?String(existing?.code??""):text(body.code),unit:body.unit===undefined?String(existing?.unit??"Piece"):text(body.unit)||"Piece",itemType,categoryId:body.categoryId===undefined?existing?.categoryId:text(body.categoryId)||undefined,brand:body.brand===undefined?existing?.brand:text(body.brand)||undefined,hsnSac:body.hsnSac===undefined?existing?.hsnSac:text(body.hsnSac)||undefined,gstRate:body.gstRate===undefined?Number(existing?.gstRate??0):rate(body.gstRate),salePrice:body.salePrice===undefined?Number(existing?.salePrice??0):amount(body.salePrice,"Sale price"),purchasePrice:body.purchasePrice===undefined?Number(existing?.purchasePrice??0):amount(body.purchasePrice,"Purchase price"),mrp:body.mrp===undefined?Number(existing?.mrp??0):amount(body.mrp,"MRP"),minStock:body.minStock===undefined?Number(existing?.minStock??0):qty(body.minStock,"Minimum stock"),maxStock:body.maxStock===undefined?Number(existing?.maxStock??0):qty(body.maxStock,"Maximum stock"),reorderLevel:body.reorderLevel===undefined?Number(existing?.reorderLevel??0):qty(body.reorderLevel,"Reorder level"),trackStock:body.trackStock===undefined?existing?.trackStock!==false:Boolean(body.trackStock),barcode:body.barcode===undefined?existing?.barcode:text(body.barcode)||undefined,status:body.status===undefined?String(existing?.status??"Active"):body.status==="Inactive"?"Inactive":"Active"};}
export async function GET(request:Request){try{const{db,token}=await auth(request);const u=new URL(request.url),businessId=text(u.searchParams.get("businessId"));if(!businessId)return err("Business ID is required.");const m=await member(db,businessId,token.uid);if(!can(m,"view"))return err("Permission denied: item view.",403);const f=await db.collection("businesses").doc(businessId).collection("financialYears").where("locked","==",false).get();const fs=f.docs.sort((a,b)=>String(b.data()?.startDate||"").localeCompare(String(a.data()?.startDate||"")));if(!fs.length)return err("No active financial year is configured for this business.");const financialYearId=fs[0].id;const[itemsSnap,movementSnap]=await Promise.all([db.collection("businesses").doc(businessId).collection("items").get(),db.collection("businesses").doc(businessId).collection("stockMovements").where("financialYearId","==",financialYearId).get()]);const stock=new Map<string,{quantity:number;value:number}>();for(const d of movementSnap.docs){const x=d.data() as{itemId?:string;direction?:string;quantity?:number;value?:number};const id=text(x.itemId);if(!id)continue;const s=stock.get(id)||{quantity:0,value:0};const sign=x.direction==="in"?1:-1;s.quantity+=Number(x.quantity||0)*sign;s.value+=Number(x.value||0)*sign;stock.set(id,s);}return NextResponse.json({success:true,financialYearId,items:itemsSnap.docs.map(d=>{const x=d.data() as Record<string,unknown>,s=stock.get(d.id)||{quantity:0,value:0};return{id:d.id,...x,stock:s.quantity,stockValue:s.value};})});}catch(e){return err(e instanceof Error?e.message:"Could not load items.",(e as{statusCode?:number}).statusCode||400);}}
export async function POST(request:Request){try{const{db,token}=await auth(request);const body=await request.json() as Record<string,unknown>,businessId=text(body.businessId);if(!businessId)return err("Business ID is required.");const m=await member(db,businessId,token.uid);if(!can(m,"create"))return err("Permission denied: item creation.",403);const item=itemRecord(body);if(!item.name||!item.code)return err("Item name and item code/SKU are required.");const ref=db.collection("businesses").doc(businessId).collection("items").doc(),now=new Date().toISOString(),record={...item,itemId:ref.id,createdAt:now,updatedAt:now};await db.runTransaction(async tx=>{const d=await tx.get(db.collection("businesses").doc(businessId).collection("items").where("code","==",item.code).limit(1));if(!d.empty)throw new Error("Item code/SKU already exists.");tx.set(ref,record);});return NextResponse.json({success:true,item:{id:ref.id,...record}});}catch(e){return err(e instanceof Error?e.message:"Could not create item.",(e as{statusCode?:number}).statusCode||400);}}
export async function PATCH(request:Request){try{const{db,token}=await auth(request);const body=await request.json() as Record<string,unknown>,businessId=text(body.businessId),itemId=text(body.itemId);if(!businessId||!itemId)return err("Business ID and item ID are required.");const m=await member(db,businessId,token.uid);if(!can(m,"edit"))return err("Permission denied: item edit.",403);const ref=db.collection("businesses").doc(businessId).collection("items").doc(itemId);const result=await db.runTransaction(async tx=>{const snap=await tx.get(ref);if(!snap.exists)throw Object.assign(new Error("Item not found."),{statusCode:404});const existing=snap.data() as Record<string,unknown>,next=itemRecord(body,existing);if(!next.name||!next.code)throw new Error("Item name and item code/SKU are required.");if(next.code!==String(existing.code||"")){const d=await tx.get(db.collection("businesses").doc(businessId).collection("items").where("code","==",next.code).limit(1));if(!d.empty&&d.docs[0].id!==itemId)throw new Error("Item code/SKU already exists.");}const record={...next,businessId,itemId,updatedAt:new Date().toISOString()};tx.set(ref,record,{merge:true});return record;});return NextResponse.json({success:true,item:{id:itemId,...result}});}catch(e){return err(e instanceof Error?e.message:"Could not update item.",(e as{statusCode?:number}).statusCode||400);}}
