import { NextResponse } from "next/server";
import type { Firestore } from "firebase-admin/firestore";
import { getAdminServices } from "@/infrastructure/firebase/admin";
import type { BusinessMember } from "@/types";

export const runtime="nodejs";
const err=(message:string,status=400)=>NextResponse.json({success:false,error:message},{status});
async function auth(request:Request){const{auth,db}=getAdminServices();const h=request.headers.get("authorization")||"";if(!h.startsWith("Bearer "))throw new Error("Authentication is required.");return{db,token:await auth.verifyIdToken(h.slice(7))};}
async function member(db:Firestore,businessId:string,uid:string){const s=await db.collection("businesses").doc(businessId).collection("members").doc(uid).get();if(!s.exists)throw Object.assign(new Error("You are not a member of this business."),{statusCode:403});const m=s.data() as BusinessMember;if(m.status!=="active")throw Object.assign(new Error("Your business membership is not active."),{statusCode:403});return m;}
function can(m:BusinessMember,a:"view"|"edit"){return m.role==="owner"||m.role==="admin"||!!m.permissions?.items?.[a];}
function normalize(value:unknown){return String(value??"").trim();}
function positiveMoney(value:unknown,name:string){const n=Number(value??0);if(!Number.isSafeInteger(Math.round(n*100))||n<0)throw new Error(`${name} must be a valid non-negative amount.`);return Math.round(n*100);}

export async function GET(request:Request){try{const{db,token}=await auth(request);const u=new URL(request.url);const businessId=normalize(u.searchParams.get("businessId"));if(!businessId)return err("Business ID is required.");const m=await member(db,businessId,token.uid);if(!can(m,"view"))return err("Permission denied: item view.",403);const snap=await db.collection("businesses").doc(businessId).collection("items").get();const movementSnap=await db.collection("businesses").doc(businessId).collection("stockMovements").get();const stock=new Map<string,{quantity:number;value:number}>();for(const d of movementSnap.docs){const x=d.data() as{itemId?:string;direction?:string;quantity?:number;value?:number};const itemId=String(x.itemId||"");if(!itemId)continue;const current=stock.get(itemId)||{quantity:0,value:0};const sign=x.direction==="in"?1:-1;current.quantity+=Number(x.quantity||0)*sign;current.value+=Number(x.value||0)*sign;stock.set(itemId,current);}const items=snap.docs.map(d=>{const x=d.data() as Record<string,unknown>;const s=stock.get(d.id)||{quantity:0,value:0};return{id:d.id,...x,stock:s.quantity,stockValue:s.value};});return NextResponse.json({success:true,items});}catch(e){const m=e instanceof Error?e.message:"Could not load items.";return err(m,(e as{statusCode?:number}).statusCode||400);}}

export async function POST(request:Request){try{const{db,token}=await auth(request);const body=await request.json() as Record<string,unknown>;const businessId=normalize(body.businessId);if(!businessId)return err("Business ID is required.");const m=await member(db,businessId,token.uid);if(!can(m,"edit"))return err("Permission denied: item creation.",403);const name=normalize(body.name);const code=normalize(body.code);const unit=normalize(body.unit)||"Piece";if(!name)return err("Item name is required.");if(!code)return err("Item code/SKU is required.");const duplicate=await db.collection("businesses").doc(businessId).collection("items").where("code","==",code).limit(1).get();if(!duplicate.empty)return err("Item code/SKU already exists.");const ref=db.collection("businesses").doc(businessId).collection("items").doc();const now=new Date().toISOString();const item={businessId,itemId:ref.id,name,code,unit,itemType:normalize(body.itemType)||"Product",categoryId:normalize(body.categoryId)||undefined,brand:normalize(body.brand)||undefined,hsnSac:normalize(body.hsnSac)||undefined,gstRate:Number(body.gstRate||0),salePrice:positiveMoney(body.salePrice,"Sale price"),purchasePrice:positiveMoney(body.purchasePrice,"Purchase price"),mrp:positiveMoney(body.mrp,"MRP"),minStock:Number(body.minStock||0),maxStock:Number(body.maxStock||0),reorderLevel:Number(body.reorderLevel||0),status:"Active",createdAt:now,updatedAt:now};await ref.set(item);return NextResponse.json({success:true,item:{id:ref.id,...item}});}catch(e){return err(e instanceof Error?e.message:"Could not create item.",(e as{statusCode?:number}).statusCode||400);}}

export async function PATCH(request:Request){try{const{db,token}=await auth(request);const body=await request.json() as Record<string,unknown>;const businessId=normalize(body.businessId),itemId=normalize(body.itemId);if(!businessId||!itemId)return err("Business ID and item ID are required.");const m=await member(db,businessId,token.uid);if(!can(m,"edit"))return err("Permission denied: item edit.",403);const ref=db.collection("businesses").doc(businessId).collection("items").doc(itemId);const current=await ref.get();if(!current.exists)return err("Item not found.",404);const existing=current.data()||{};const code=body.code===undefined?String(existing.code||""):normalize(body.code);if(!code)return err("Item code/SKU is required.");if(code!==String(existing.code||"")){const duplicate=await db.collection("businesses").doc(businessId).collection("items").where("code","==",code).limit(1).get();if(!duplicate.empty&&duplicate.docs[0].id!==itemId)return err("Item code/SKU already exists.");}const patch:Record<string,unknown>={updatedAt:new Date().toISOString(),...body};delete patch.businessId;delete patch.itemId;delete patch.stock;delete patch.stockValue;delete patch.openingStock;delete patch.openingStockValue;delete patch.id;await ref.set({...patch,code},{merge:true});return NextResponse.json({success:true});}catch(e){return err(e instanceof Error?e.message:"Could not update item.",(e as{statusCode?:number}).statusCode||400);}}
