"use client";
import { useEffect, useMemo, useState } from "react";
import Sidebar from "../Components/Sidebar/page";
import TopNav from "../Components/TopNav/page";
import AuthGate from "../Components/Auth/AuthGate";
import { auth } from "../../lib/firebase";
import { useBusiness } from "../../context/BusinessContext";

type Item={id:string;name:string;code:string;unit?:string;unitId?:string;categoryId?:string;itemType?:string;hsnSac?:string;gstRate?:number;purchasePrice?:number;salePrice?:number;mrp?:number;barcode?:string;stock?:number;stockValue?:number;minStock?:number;maxStock?:number;reorderLevel?:number;status?:string;trackStock?:boolean;tracking?:{batch:boolean;serial:boolean;expiry:boolean}};
type Master={id:string;name:string;shortName?:string;address?:string};
const money=(n:number)=>new Intl.NumberFormat("en-IN",{style:"currency",currency:"INR"}).format((n||0)/100);
const token=async()=>{if(!auth.currentUser)throw Error("Please sign in again.");return auth.currentUser.getIdToken()};

export default function ItemsPage(){
 const {activeBusinessId,businessName,loading}=useBusiness();
 const [items,setItems]=useState<Item[]>([]),[masters,setMasters]=useState<Record<string,Master[]>>({units:[],categories:[],warehouses:[]}),[q,setQ]=useState(""),[tab,setTab]=useState<"items"|"masters"|"reports">("items"),[show,setShow]=useState(false),[edit,setEdit]=useState<Item|null>(null),[selected,setSelected]=useState<Item|null>(null),[error,setError]=useState(""),[saving,setSaving]=useState(false),[form,setForm]=useState<any>({name:"",code:"",itemType:"product",unitId:"",categoryId:"",hsnSac:"",gstRate:"0",purchasePrice:"0",salePrice:"0",mrp:"0",barcode:"",minStock:"0",maxStock:"0",reorderLevel:"0",trackStock:true,batch:false,serial:false,expiry:false}),[masterType,setMasterType]=useState("units"),[masterName,setMasterName]=useState(""),[masterShort,setMasterShort]=useState("");
 const load=async()=>{if(!activeBusinessId)return;try{const t=await token(),headers={Authorization:`Bearer ${t}`};const r=await fetch(`/api/items?businessId=${activeBusinessId}`,{headers,cache:"no-store"});const b=await r.json();if(!r.ok)throw Error(b.error);setItems(b.items||[]);for(const type of ["units","categories","warehouses"]){const x=await fetch(`/api/item-masters?businessId=${activeBusinessId}&type=${type}`,{headers,cache:"no-store"}),y=await x.json();if(x.ok)setMasters(v=>({...v,[type]:y.items||[]}))}}catch(e){setError(e instanceof Error?e.message:"Unable to load inventory")}};
 useEffect(()=>{if(!loading)void load()},[activeBusinessId,loading]);
 const filtered=useMemo(()=>{const x=q.toLowerCase().trim();return x?items.filter(i=>`${i.name} ${i.code} ${i.barcode||""}`.toLowerCase().includes(x)):items},[items,q]);
 const stats={count:items.length,qty:items.reduce((s,i)=>s+Number(i.stock||0),0),value:items.reduce((s,i)=>s+Number(i.stockValue||0),0),low:items.filter(i=>Number(i.stock||0)<=Number(i.reorderLevel??i.minStock??0)).length};
 const open=(i?:Item)=>{setEdit(i||null);setForm(i?{...form,name:i.name,code:i.code,itemType:i.itemType||"product",unitId:i.unitId||"",categoryId:i.categoryId||"",hsnSac:i.hsnSac||"",gstRate:String(i.gstRate||0),purchasePrice:String(Number(i.purchasePrice||0)/100),salePrice:String(Number(i.salePrice||0)/100),mrp:String(Number(i.mrp||0)/100),barcode:i.barcode||"",minStock:String(i.minStock||0),maxStock:String(i.maxStock||0),reorderLevel:String(i.reorderLevel||0),trackStock:i.trackStock!==false,batch:!!i.tracking?.batch,serial:!!i.tracking?.serial,expiry:!!i.tracking?.expiry}:{...form,name:"",code:""});setShow(true);setError("")};
 const save=async(e:React.FormEvent)=>{e.preventDefault();setSaving(true);try{const t=await token(),u=masters.units.find(x=>x.id===form.unitId);const body:any={businessId:activeBusinessId,name:form.name.trim(),code:form.code.trim(),itemType:form.itemType,unit:u?.shortName||u?.name||"Piece",unitId:form.unitId||null,categoryId:form.categoryId||null,hsnSac:form.hsnSac||null,gstRate:Number(form.gstRate),purchasePrice:Math.round(Number(form.purchasePrice)*100),salePrice:Math.round(Number(form.salePrice)*100),mrp:Math.round(Number(form.mrp)*100),barcode:form.barcode||null,minStock:Number(form.minStock),maxStock:Number(form.maxStock),reorderLevel:Number(form.reorderLevel),trackStock:Boolean(form.trackStock),tracking:{batch:Boolean(form.batch),serial:Boolean(form.serial),expiry:Boolean(form.expiry)}};if(edit)body.itemId=edit.id;const r=await fetch("/api/items",{method:edit?"PATCH":"POST",headers:{"Content-Type":"application/json",Authorization:`Bearer ${t}`},body:JSON.stringify(body)}),b=await r.json();if(!r.ok)throw Error(b.error);setShow(false);await load()}catch(e){setError(e instanceof Error?e.message:"Unable to save item")}finally{setSaving(false)}};
 const addMaster=async()=>{try{const t=await token(),r=await fetch("/api/item-masters",{method:"POST",headers:{"Content-Type":"application/json",Authorization:`Bearer ${t}`},body:JSON.stringify({businessId:activeBusinessId,type:masterType,name:masterName,shortName:masterShort})}),b=await r.json();if(!r.ok)throw Error(b.error);setMasterName("");setMasterShort("");await load()}catch(e){setError(e instanceof Error?e.message:"Unable to create master")}};
 return <AuthGate><div className="flex min-h-screen bg-slate-50"><Sidebar/><main className="min-w-0 flex-1 px-4 pb-10 sm:px-8"><TopNav/><div className="mx-auto max-w-[1500px] py-5"><div className="flex flex-wrap justify-between gap-4"><div><p className="text-sm font-semibold text-indigo-600">{businessName||"Business"} · Inventory</p><h1 className="text-3xl font-bold text-slate-900">Items & Inventory</h1><p className="mt-1 text-sm text-slate-500">Complete item master, tracking and stock control.</p></div><button onClick={()=>open()} className="rounded-xl bg-indigo-600 px-5 py-2.5 font-semibold text-white">+ New Item</button></div>{error&&<div className="mt-4 rounded-xl border border-red-200 bg-red-50 p-3 text-sm text-red-700">{error}</div>}<nav className="mt-6 flex gap-1 overflow-x-auto rounded-xl border bg-white p-1"><button onClick={()=>setTab("items")} className={`rounded-lg px-4 py-2 text-sm font-semibold ${tab==="items"?"bg-slate-900 text-white":"text-slate-600"}`}>Items</button><button onClick={()=>setTab("masters")} className={`rounded-lg px-4 py-2 text-sm font-semibold ${tab==="masters"?"bg-slate-900 text-white":"text-slate-600"}`}>Units / Categories / Warehouses</button><button onClick={()=>setTab("reports")} className={`rounded-lg px-4 py-2 text-sm font-semibold ${tab==="reports"?"bg-slate-900 text-white":"text-slate-600"}`}>Inventory Reports</button></nav>
 {tab==="items"&&<><div className="mt-5 grid gap-4 sm:grid-cols-4">{[["Items",stats.count],["Quantity",stats.qty],["Low / Reorder",stats.low],["Stock Value",money(stats.value)]].map(x=><div key={String(x[0])} className="rounded-2xl border bg-white p-5"><p className="text-sm text-slate-500">{x[0]}</p><p className="mt-2 text-2xl font-bold">{x[1]}</p></div>)}</div><section className="mt-5 overflow-hidden rounded-2xl border bg-white"><div className="flex justify-between gap-3 border-b p-5"><h2 className="font-bold">Item Catalogue</h2><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Search item / SKU / barcode" className="h-10 w-full max-w-sm rounded-xl border px-3 text-sm"/></div><div className="overflow-x-auto"><table className="w-full min-w-[1200px] text-left"><thead className="bg-slate-50 text-xs uppercase text-slate-500"><tr>{["Item / SKU","Type","Unit","GST","Stock","Value","Purchase","Sale","Tracking","Status"].map(h=><th className="px-5 py-3" key={h}>{h}</th>)}</tr></thead><tbody className="divide-y">{filtered.map(i=><tr key={i.id} onClick={()=>setSelected(i)} className="cursor-pointer hover:bg-slate-50"><td className="px-5 py-4"><b>{i.name}</b><div className="text-xs text-slate-400">{i.code}{i.barcode?` · ${i.barcode}`:""}</div></td><td className="px-5 py-4 text-sm capitalize">{i.itemType||"product"}</td><td className="px-5 py-4">{i.unit||"Piece"}</td><td className="px-5 py-4">{i.gstRate||0}%</td><td className="px-5 py-4 font-semibold">{i.stock||0}</td><td className="px-5 py-4">{money(Number(i.stockValue||0))}</td><td className="px-5 py-4">{money(Number(i.purchasePrice||0))}</td><td className="px-5 py-4">{money(Number(i.salePrice||0))}</td><td className="px-5 py-4 text-xs">{[i.tracking?.batch&&"Batch",i.tracking?.serial&&"Serial",i.tracking?.expiry&&"Expiry"].filter(Boolean).join(" · ")||"—"}</td><td className="px-5 py-4 text-xs font-semibold">{i.status||"Active"}</td></tr>)}</tbody></table></div></section></>}
 {tab==="masters"&&<div className="mt-5 grid gap-5 lg:grid-cols-[360px_1fr]"><section className="rounded-2xl border bg-white p-5"><h2 className="font-bold">Master Setup</h2><select value={masterType} onChange={e=>setMasterType(e.target.value)} className="mt-4 h-10 w-full rounded-xl border px-3"><option value="units">Units</option><option value="categories">Categories</option><option value="warehouses">Warehouses</option></select><input value={masterName} onChange={e=>setMasterName(e.target.value)} placeholder="Name" className="mt-3 h-10 w-full rounded-xl border px-3"/>{masterType==="units"&&<input value={masterShort} onChange={e=>setMasterShort(e.target.value)} placeholder="Short name" className="mt-3 h-10 w-full rounded-xl border px-3"/>}<button onClick={addMaster} className="mt-4 w-full rounded-xl bg-indigo-600 px-4 py-2.5 font-semibold text-white">Add</button></section><section className="rounded-2xl border bg-white p-5"><h2 className="font-bold capitalize">{masterType}</h2>{masters[masterType].map(m=><div key={m.id} className="flex justify-between border-b py-3"><span>{m.name}</span><span className="text-xs text-slate-400">{m.shortName||m.address||"Active"}</span></div>)}</section></div>}
 {tab==="reports"&&<div className="mt-5 grid gap-4 md:grid-cols-2 lg:grid-cols-3">{[["Stock Summary","/reports/inventory?view=summary"],["Stock Ledger","/reports/inventory?view=ledger"],["Low Stock","/reports/inventory?view=low"],["Warehouse Stock","/reports/inventory?view=warehouse"],["Batch / Expiry","/reports/inventory?view=expiry"],["Stock Valuation","/reports/inventory?view=valuation"]].map(([n,u])=><a key={n} href={u} className="rounded-2xl border bg-white p-6 hover:border-indigo-300"><b>{n}</b><p className="mt-1 text-sm text-slate-500">Open inventory report →</p></a>)}</div>}</div></main>
 {selected&&<aside className="fixed inset-y-0 right-0 z-40 w-full max-w-md overflow-y-auto border-l bg-white p-6 shadow-2xl"><button onClick={()=>setSelected(null)} className="float-right text-2xl">×</button><h2 className="text-2xl font-bold">{selected.name}</h2><p className="text-sm text-slate-500">{selected.code}</p><div className="mt-6 grid grid-cols-2 gap-3"><div className="rounded-xl border p-4"><small>Stock</small><b className="mt-1 block text-xl">{selected.stock||0}</b></div><div className="rounded-xl border p-4"><small>Value</small><b className="mt-1 block text-xl">{money(Number(selected.stockValue||0))}</b></div></div><div className="mt-5 grid grid-cols-2 gap-2"><button onClick={()=>open(selected)} className="rounded-xl border px-3 py-2">Edit</button><a href={`/reports/inventory?view=ledger&itemId=${selected.id}`} className="rounded-xl border px-3 py-2 text-center">Ledger</a></div><div className="mt-5 rounded-xl bg-slate-50 p-4 text-sm"><b>Tracking</b><p className="mt-2 text-slate-600">{selected.tracking?.batch ? "Batch · " : ""}{selected.tracking?.serial ? "Serial · " : ""}{selected.tracking?.expiry ? "Expiry" : "Standard"}</p></div></aside>}
 {show&&<div className="fixed inset-0 z-50 flex items-center justify-center overflow-y-auto bg-black/30 p-4"><form onSubmit={save} className="my-6 w-full max-w-5xl rounded-2xl bg-white p-6 shadow-2xl"><div className="flex justify-between"><div><h2 className="text-xl font-bold">{edit?"Edit Item":"New Item"}</h2><p className="text-sm text-slate-500">Configure master, GST, pricing, units and tracking.</p></div><button type="button" onClick={()=>setShow(false)}>×</button></div><div className="mt-5 grid gap-4 md:grid-cols-3">{[["name","Item name"],["code","Item code / SKU"],["hsnSac","HSN / SAC"],["barcode","Barcode"],["gstRate","GST %"],["purchasePrice","Purchase price ₹"],["salePrice","Sale price ₹"],["mrp","MRP ₹"],["minStock","Minimum stock"],["maxStock","Maximum stock"],["reorderLevel","Reorder level"]].map(([k,l])=><label key={k} className="text-sm">{l}<input value={form[k]} onChange={e=>setForm({...form,[k]:e.target.value})} type={["gstRate","purchasePrice","salePrice","mrp","minStock","maxStock","reorderLevel"].includes(k)?"number":"text"} min="0" className="mt-1 h-10 w-full rounded-xl border px-3" required={k==="name"||k==="code"}/></label>)}<label className="text-sm">Type<select value={form.itemType} onChange={e=>setForm({...form,itemType:e.target.value})} className="mt-1 h-10 w-full rounded-xl border px-3"><option value="product">Product</option><option value="service">Service</option></select></label><label className="text-sm">Unit<select value={form.unitId} onChange={e=>setForm({...form,unitId:e.target.value})} className="mt-1 h-10 w-full rounded-xl border px-3"><option value="">Piece</option>{masters.units.map(u=><option key={u.id} value={u.id}>{u.name} ({u.shortName||u.name})</option>)}</select></label><label className="text-sm">Category<select value={form.categoryId} onChange={e=>setForm({...form,categoryId:e.target.value})} className="mt-1 h-10 w-full rounded-xl border px-3"><option value="">None</option>{masters.categories.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></label></div><div className="mt-5 grid gap-3 rounded-xl border p-4 md:grid-cols-4"><label><input type="checkbox" checked={form.trackStock} onChange={e=>setForm({...form,trackStock:e.target.checked})}/> Track stock</label><label><input type="checkbox" checked={form.batch} onChange={e=>setForm({...form,batch:e.target.checked})}/> Batch / Lot</label><label><input type="checkbox" checked={form.serial} onChange={e=>setForm({...form,serial:e.target.checked})}/> Serial</label><label><input type="checkbox" checked={form.expiry} onChange={e=>setForm({...form,expiry:e.target.checked})}/> Expiry</label></div><div className="mt-6 flex justify-end gap-2"><button type="button" onClick={()=>setShow(false)} className="rounded-xl border px-4 py-2">Cancel</button><button disabled={saving} className="rounded-xl bg-indigo-600 px-5 py-2 font-semibold text-white">{saving?"Saving…":"Save Item"}</button></div></form></div>}
 </AuthGate>;
}