import { NextResponse } from "next/server";
import { getAdminServices } from "@/infrastructure/firebase/admin";
import { buildBalanceSheet, buildProfitLoss, buildTrialBalance, type ReportPeriod } from "@/core/accounting/reports";
import { valueFifo, valueWeightedAverage, type StockValuationMethod } from "@/core/accounting/valuation";
import type { Account, LedgerEntry, StockMovement } from "@/core/accounting/types";

export const runtime = "nodejs";
type Membership={status?:string;role?:string;permissions?:Record<string,unknown>};
type PeriodName="Today"|"This week"|"This month"|"This year";
const PERIODS=["Today","This week","This month","This year"] as const;
const rupees=(paise:number)=>Math.round(Number(paise||0))/100;
const iso=(v:unknown)=>{if(typeof v==="string")return v.slice(0,10);if(v&&typeof v==="object"&&"toDate" in v&&typeof (v as {toDate?:unknown}).toDate==="function")return (v as {toDate:()=>Date}).toDate().toISOString().slice(0,10);return "";};
const dateTime=(v:unknown)=>{if(typeof v==="string"){const d=new Date(v);return Number.isFinite(d.getTime())?d:null;}if(v&&typeof v==="object"&&"toDate" in v&&typeof (v as {toDate?:unknown}).toDate==="function")return(v as {toDate:()=>Date}).toDate();return null;};
function periodRange(period:PeriodName,fy?:{startDate?:string}){const now=new Date(),end=now.toISOString().slice(0,10);if(period==="Today")return{from:end,to:end};if(period==="This week"){const d=new Date(now);d.setHours(0,0,0,0);const day=d.getDay()||7;d.setDate(d.getDate()-day+1);return{from:d.toISOString().slice(0,10),to:end};}if(period==="This year"&&fy?.startDate)return{from:fy.startDate,to:end};return{from:`${now.getFullYear()}-${String(now.getMonth()+1).padStart(2,"0")}-01`,to:end};}
function monthKey(d:Date){return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,"0")}`;}
function buildMonthBuckets(start:string,end:string){const s=new Date(`${start}T00:00:00`),e=new Date(`${end}T00:00:00`),out:Array<{key:string;label:string;value:number}>=[];let cursor=new Date(s.getFullYear(),s.getMonth(),1);while(cursor<=e){out.push({key:monthKey(cursor),label:cursor.toLocaleString("en-IN",{month:"short"}),value:0});cursor.setMonth(cursor.getMonth()+1);}return out;}
async function authorize(request:Request){const{auth,db}=getAdminServices();const h=request.headers.get("authorization")||"";if(!h.startsWith("Bearer "))throw Object.assign(new Error("Authentication is required."),{status:401});const token=await auth.verifyIdToken(h.slice(7));const businessId=new URL(request.url).searchParams.get("businessId")?.trim()||"";if(!businessId)throw Object.assign(new Error("Business ID is required."),{status:400});const businessRef=db.collection("businesses").doc(businessId);const memberSnap=await businessRef.collection("members").doc(token.uid).get();if(!memberSnap.exists)throw Object.assign(new Error("You are not a member of this business."),{status:403});const member=memberSnap.data() as Membership;if(member.status!=="active")throw Object.assign(new Error("Your business membership is not active."),{status:403});const reports=(member.permissions?.reports??{}) as Record<string,unknown>;if(!(member.role==="owner"||member.role==="admin"||reports.view===true))throw Object.assign(new Error("Permission denied: dashboard view."),{status:403});return{db,businessRef};}
function mapAccount(d:Record<string,unknown>,id:string):Account{return{id,businessId:String(d.businessId??""),code:String(d.code??""),name:String(d.name??""),type:d.type as Account["type"],parentId:(d.parentId as string|undefined)??null,systemAccount:Boolean(d.systemAccount),active:d.active!==false,openingDebit:Number(d.openingDebit??0),openingCredit:Number(d.openingCredit??0),createdAt:iso(d.createdAt),updatedAt:iso(d.updatedAt)};}
function mapEntry(d:Record<string,unknown>,id:string):LedgerEntry{return{lineId:String(d.lineId??d.entryId??id),voucherId:String(d.voucherId??""),businessId:String(d.businessId??""),lineNo:Number(d.lineNo??0),accountId:String(d.accountId??""),partyId:d.partyId?String(d.partyId):undefined,description:d.description?String(d.description):undefined,debit:Number(d.debit??0),credit:Number(d.credit??0),date:iso(d.date),voucherType:String(d.voucherType??""),voucherNumber:String(d.voucherNumber??""),createdAt:iso(d.createdAt)};}
function mapMovement(d:Record<string,unknown>,id:string):StockMovement{return{id:String(d.id??d.movementId??id),businessId:String(d.businessId??""),financialYearId:String(d.financialYearId??""),itemId:String(d.itemId??""),warehouseId:String(d.warehouseId??"MAIN"),direction:d.direction==="out"?"out":"in",quantity:Number(d.quantity??0),baseQuantity:Number(d.baseQuantity??d.quantity??0),unitCost:Number(d.unitCost??0),value:Number(d.value??0),date:iso(d.date),createdAt:iso(d.createdAt),createdBy:String(d.createdBy??d.userId??""),sourceType:String(d.sourceType??"opening"),sourceId:String(d.sourceId??"")};}
const balance=(rows:{accountId:string;balance:number}[],ids:Set<string>)=>rows.filter(r=>ids.has(r.accountId)).reduce((s,r)=>s+r.balance,0);
function accountBalance(rows:{accountId:string;balance:number}[],account?:Account){return account?rows.find(r=>r.accountId===account.id)?.balance??0:0;}
export async function GET(request:Request){try{const{businessRef}=await authorize(request);const url=new URL(request.url);const rawPeriod=url.searchParams.get("period") as PeriodName;const selected:PeriodName=PERIODS.includes(rawPeriod)?rawPeriod:"This month";
const fySnap=await businessRef.collection("financialYears").where("locked","==",false).get();const fyDocs=fySnap.docs.sort((a,b)=>String(b.data()?.startDate||"").localeCompare(String(a.data()?.startDate||"")));const fy=fyDocs[0]?.data() as {id?:string;startDate?:string;endDate?:string;locked?:boolean}|undefined;const fyId=String(fy?.id||"");const range=periodRange(selected,fy);const [accountsSnap,ledgerSnap,movementSnap,voucherSnap,itemSnap,settingsSnap,businessSnap]=await Promise.all([businessRef.collection("accounts").get(),businessRef.collection("ledgerEntries").where("date","<=",range.to).get(),businessRef.collection("stockMovements").where("date","<=",range.to).get(),businessRef.collection("vouchers").where("date","<=",range.to).get(),businessRef.collection("items").get(),businessRef.collection("settings").doc("business").get(),businessRef.get()]);
const accounts=accountsSnap.docs.map(d=>mapAccount(d.data() as Record<string,unknown>,d.id));const fyStart=String(fy?.startDate||"0000-01-01");const entries=ledgerSnap.docs.map(d=>mapEntry(d.data() as Record<string,unknown>,d.id)).filter(e=>e.accountId&&e.date&&e.date>=fyStart&&(!fy?.endDate||e.date<=fy.endDate));const movements=movementSnap.docs.map(d=>mapMovement(d.data() as Record<string,unknown>,d.id)).filter(m=>m.itemId&&m.date&&(!fyId||!m.financialYearId||m.financialYearId===fyId)&&m.date>=fyStart);const vouchers=voucherSnap.docs.map(d=>({id:d.id,...d.data()} as Record<string,unknown>)).filter(v=>{const d=iso(v.date||v.createdAt);return d>=fyStart&&(!fy?.endDate||d<=fy.endDate);});
const p:ReportPeriod={fromDate:range.from,toDate:range.to};const tb=buildTrialBalance(accounts,entries,{toDate:range.to});const pl=buildProfitLoss(accounts,entries,p);const bs=buildBalanceSheet(accounts,entries,{toDate:range.to});
const salesAccount=accounts.find(a=>a.code==="4000"||/^sales$/i.test(a.name));const cogsAccount=accounts.find(a=>a.code==="5100"||/cost of goods sold/i.test(a.name));const receivableAccounts=accounts.filter(a=>a.code==="1200"||/debtor|receivable/i.test(a.name));const payableAccounts=accounts.filter(a=>a.code==="2000"||/creditor|payable/i.test(a.name));const cashAccounts=accounts.filter(a=>["1000","1010"].includes(a.code)||/^cash$/i.test(a.name)||/bank/i.test(a.name));const salesIds=new Set(salesAccount?[salesAccount.id]:[]);const receivableIds=new Set(receivableAccounts.map(a=>a.id));const payableIds=new Set(payableAccounts.map(a=>a.id));const cashIds=new Set(cashAccounts.map(a=>a.id));
const periodSalesPaise=salesAccount?entries.filter(e=>e.accountId===salesAccount.id&&e.date>=range.from&&e.date<=range.to).reduce((s,e)=>s+e.credit-e.debit,0):0;const receivables=balance(tb.rows,receivableIds),payables=balance(tb.rows,payableIds),cashBank=balance(tb.rows,cashIds);const customerBalances=new Map<string,number>();for(const e of entries.filter(e=>e.date<=range.to&&receivableIds.has(e.accountId)&&e.partyId))customerBalances.set(e.partyId,(customerBalances.get(e.partyId)||0)+e.debit-e.credit);const receivableCount=[...customerBalances.values()].filter(v=>v>0).length;
const settings=(settingsSnap.data()||{}) as Record<string,unknown>;const transactionSettings=(settings.transactions||{}) as Record<string,unknown>;const valuationMethod:StockValuationMethod=transactionSettings.inventoryValuationMethod==="weighted_average"||settings.inventoryValuationMethod==="weighted_average"?"weighted_average":"fifo";
const byKey=new Map<string,StockMovement[]>();for(const m of movements.filter(m=>m.date<=range.to)){const k=`${m.itemId}::${m.warehouseId}`;(byKey.get(k)||byKey.set(k,[]).get(k)!).push(m);}let inventorySubledger=0,negativeStock=0,unvalued=0,valuationFailed=false;for(const ms of byKey.values()){if(ms.some(m=>m.direction==="in"&&m.quantity>0&&m.unitCost===0&&m.value===0))unvalued++;try{inventorySubledger+=(valuationMethod==="weighted_average"?valueWeightedAverage(ms):valueFifo(ms)).value;}catch{negativeStock++;valuationFailed=true;}}
const inventoryGl=accounts.find(a=>a.code==="1300"||/^inventory$/i.test(a.name));const inventoryGlValue=accountBalance(tb.rows,inventoryGl);const inventoryDiff=valuationFailed?null:inventoryGlValue-inventorySubledger;
const postedSales=vouchers.filter(v=>String(v.voucherType||"").toUpperCase()==="SALE"&&String(v.status||"").toLowerCase()==="posted"&&inRange(v,range));const recent=[...postedSales].sort((a,b)=>iso(b.date||b.createdAt).localeCompare(iso(a.date||a.createdAt))).slice(0,8).map(v=>({id:String(v.id),voucherNumber:String(v.voucherNumber||v.id.slice(0,8)),customerName:String(v.partyName||v.narration||"Posted sale"),date:iso(v.date||v.createdAt),total:rupees(Number(v.grandTotal??v.totalDebit??0)),status:"posted"}));
const chart=selected==="This year"?buildMonthBuckets(range.from,range.to):selected==="Today"?Array.from({length:24},(_,h)=>({key:String(h),label:`${String(h).padStart(2,"0")}:00`,value:0})):Array.from({length:selected==="This week"?7:30},(_,i)=>{const d=new Date();d.setDate(d.getDate()-(selected==="This week"?6-i:29-i));return{key:d.toISOString().slice(0,10),label:String(d.getDate()),value:0};});
for(const e of entries.filter(e=>salesIds.has(e.accountId)&&e.date>=range.from&&e.date<=range.to)){let index=-1;if(selected==="Today"){const raw=vouchers.find(v=>String(v.id)===e.voucherId);const dt=dateTime(raw?.date)||dateTime(raw?.createdAt);index=dt?dt.getHours():-1;}else if(selected==="This year"){const key=e.date.slice(0,7);index=chart.findIndex((x)=>x.key===key);}else index=chart.findIndex(x=>x.key===e.date);if(index>=0)chart[index].value+=rupees(e.credit-e.debit);}
const stockByItem=new Map<string,number>();for(const m of movements.filter(m=>m.date<=range.to))stockByItem.set(m.itemId,(stockByItem.get(m.itemId)||0)+(m.direction==="in"?m.baseQuantity:-m.baseQuantity));const lowStock=itemSnap.docs.map(d=>{const x=d.data() as Record<string,unknown>;return{id:d.id,name:String(x.name||"Unnamed item"),stock:Number(stockByItem.get(d.id)??x.stock??0),minStock:Number(x.minStock??x.minimumStock??x.reorderLevel??0)};}).filter(x=>x.minStock>0&&x.stock<=x.minStock).sort((a,b)=>a.stock-b.stock).slice(0,8);
const overdueReceivables=vouchers.filter(v=>{const type=String(v.voucherType||"").toUpperCase();if(type!=="SALE"||String(v.status||"").toLowerCase()!=="posted")return false;const due=iso(v.dueDate);if(!due||due>=new Date().toISOString().slice(0,10))return false;const outstanding=Number(v.outstandingBalance??v.balance??0);return outstanding>0;}).length;const cogs=accountBalance(tb.rows,cogsAccount);const grossProfit=pl.income-pl.contraRevenue-cogs;const gstInput=balance(tb.rows,new Set(accounts.filter(a=>/^14/.test(a.code)).map(a=>a.id)));const gstOutput=balance(tb.rows,new Set(accounts.filter(a=>/^21/.test(a.code)).map(a=>a.id)));const gstPayable=Math.max(0,gstOutput-gstInput);
const accountingBalanced=tb.balanced&&bs.balanced;return NextResponse.json({success:true,data:{period:selected,from:range.from,to:range.to,businessName:String(businessSnap.data()?.name||"Your business"),financialYear:{id:fyId,startDate:fy?.startDate||"",endDate:fy?.endDate||"",locked:Boolean(fy?.locked)},lastUpdated:new Date().toISOString(),accounting:{profit:rupees(pl.profit),income:rupees(pl.income),contraRevenue:rupees(pl.contraRevenue),expenses:rupees(pl.expense),grossProfit:rupees(grossProfit),cogs:rupees(cogs),assets:rupees(bs.assets),liabilities:rupees(bs.liabilities),equity:rupees(bs.equity),cashBank:rupees(cashBank),receivables:rupees(Math.max(0,receivables)),payables:rupees(Math.max(0,payables)),inventoryValue:inventoryDiff===null?null:rupees(inventorySubledger),inventoryMethod:valuationMethod,trialBalanceDifference:rupees(tb.difference),balanceSheetDifference:rupees(bs.difference),inventoryGlDifference:inventoryDiff===null?null:rupees(inventoryDiff),balanced:accountingBalanced,inventoryReconciled:inventoryDiff!==null&&inventoryDiff===0,gstInput:rupees(gstInput),gstOutput:rupees(gstOutput),gstPayable:rupees(gstPayable)},sales:{total:rupees(periodSalesPaise),count:postedSales.length},receivables:{outstanding:rupees(Math.max(0,receivables)),count:receivableCount},inventory:{lowStockCount:lowStock.length,lowStock,valuationAvailable:!valuationFailed},exceptions:{negativeStock,unvaluedStock:unvalued,inventoryVariance:inventoryDiff!==null&&inventoryDiff!==0,accountingBalanced,overdueReceivables},recentSales:recent,chart}});}catch(e){const message=e instanceof Error?e.message:"Could not load dashboard.";return NextResponse.json({success:false,error:message},{status:(e as{status?:number}).status||500});}}
function inRange(v:Record<string,unknown>,r:{from:string;to:string}){const d=iso(v.date||v.createdAt);return !!d&&d>=r.from&&d<=r.to;}
