import { NextResponse } from "next/server";
import { getAdminServices } from "@/infrastructure/firebase/admin";

export const runtime = "nodejs";

type Membership={status?:string;role?:string;permissions?:Record<string,unknown>};
const money=(n:number)=>Math.round(Number(n||0)*100)/100;
const iso=(v:unknown)=>{if(typeof v==="string")return v.slice(0,10);if(v&&typeof v==="object"&&"toDate" in v&&typeof (v as {toDate?:unknown}).toDate==="function")return (v as {toDate:()=>Date}).toDate().toISOString().slice(0,10);return "";};
function range(period:string){const now=new Date();const end=now.toISOString().slice(0,10);const d=new Date(now);d.setHours(0,0,0,0);if(period==="Today")return{from:end,to:end};if(period==="This week"){const day=d.getDay()||7;d.setDate(d.getDate()-day+1);return{from:d.toISOString().slice(0,10),to:end};}if(period==="This year"){const y=now.getMonth()>=3?now.getFullYear():now.getFullYear()-1;return{from:`${y}-04-01`,to:end};}return{from:`${now.getFullYear()}-${String(now.getMonth()+1).padStart(2,"0")}-01`,to:end};}
function inRange(date:string,r:{from:string;to:string}){return !!date&&date>=r.from&&date<=r.to;}
async function authorize(request:Request){const{auth,db}=getAdminServices();const h=request.headers.get("authorization")||"";if(!h.startsWith("Bearer "))throw Object.assign(new Error("Authentication is required."),{status:401});const token=await auth.verifyIdToken(h.slice(7));const businessId=new URL(request.url).searchParams.get("businessId")?.trim()||"";if(!businessId)throw Object.assign(new Error("Business ID is required."),{status:400});const businessRef=db.collection("businesses").doc(businessId);const memberSnap=await businessRef.collection("members").doc(token.uid).get();if(!memberSnap.exists)throw Object.assign(new Error("You are not a member of this business."),{status:403});const member=memberSnap.data() as Membership;if(member.status!=="active")throw Object.assign(new Error("Your business membership is not active."),{status:403});const reports=(member.permissions?.reports??{}) as Record<string,unknown>;if(!(member.role==="owner"||member.role==="admin"||reports.view===true))throw Object.assign(new Error("Permission denied: dashboard view."),{status:403});return{db,businessRef};}
export async function GET(request:Request){try{const{businessRef}=await authorize(request);const period=new URL(request.url).searchParams.get("period")||"This month";const r=range(period);const [salesSnap,expenseSnap,customerSnap,itemSnap,movementSnap]=await Promise.all([businessRef.collection("sales").get(),businessRef.collection("expenses").get(),businessRef.collection("customers").get(),businessRef.collection("items").get(),businessRef.collection("stockMovements").get()]);
 const sales=salesSnap.docs.map(d=>({id:d.id,...d.data()} as Record<string,unknown>)).filter(s=>inRange(iso(s.invoiceDate||s.date||s.createdAt),r));
 const expenses=expenseSnap.docs.map(d=>({id:d.id,...d.data()} as Record<string,unknown>)).filter(e=>inRange(iso(e.date||e.expenseDate||e.createdAt),r));
 const customers=customerSnap.docs.map(d=>({id:d.id,...d.data()} as Record<string,unknown>));
 const items=itemSnap.docs.map(d=>({id:d.id,...d.data()} as Record<string,unknown>));
 const movements=movementSnap.docs.map(d=>({id:d.id,...d.data()} as Record<string,unknown>));
 const totalSales=money(sales.reduce((n,s)=>n+Number(s.total||0),0));
 const paid=money(sales.reduce((n,s)=>n+Number(s.paid||0),0));
 const outstanding=money(customers.reduce((n,c)=>n+Math.max(0,Number(c.balance||0)),0));
 const expenseTotal=money(expenses.reduce((n,e)=>n+Number(e.amount||e.total||0),0));
 const stockByItem=new Map<string,number>();for(const m of movements){const id=String(m.itemId||"");if(!id)continue;const q=Number(m.quantity||0)*(m.direction==="out"?-1:1);stockByItem.set(id,(stockByItem.get(id)||0)+q);}
 const lowStock=items.map(i=>{const id=String(i.id||"");const stock=money(stockByItem.has(id)?stockByItem.get(id)||0:Number(i.stock||0));const min=Number(i.minStock??i.minimumStock??i.reorderLevel??0);return{id,name:String(i.name||"Unnamed item"),stock,minStock:min};}).filter(i=>i.stock<=i.minStock&&i.minStock>0).sort((a,b)=>a.stock-b.stock).slice(0,8);
 const recent=[...sales].sort((a,b)=>iso(b.invoiceDate||b.date||b.createdAt).localeCompare(iso(a.invoiceDate||a.date||a.createdAt))).slice(0,8).map(s=>({id:s.id,invoiceNumber:String(s.invoiceNumber||s.invoiceNo||s.id.slice(0,8)),customerName:String(s.customerName||"Cash Sale"),date:iso(s.invoiceDate||s.date||s.createdAt),total:money(Number(s.total||0)),paid:money(Number(s.paid||0)),balance:money(Math.max(0,Number(s.balance||0))),status:String(s.status||"")}));
 const days=period==="Today"?24:period==="This year"?12:period==="This week"?7:30;const chart=Array.from({length:days},(_,i)=>{const d=new Date();if(period==="Today")return{label:`${String(i).padStart(2,"0")}:00`,value:0};if(period==="This year"){d.setMonth(d.getMonth()-(days-1-i),1);return{label:d.toLocaleString("en-IN",{month:"short"}),value:0};}d.setDate(d.getDate()-(days-1-i));return{label:String(d.getDate()),value:0};});for(const s of sales){const date=iso(s.invoiceDate||s.date||s.createdAt);if(!date)continue;const index=period==="Today"?Number(String(s.invoiceDate||s.createdAt).slice(11,13)):period==="This year"?chart.findIndex((x)=>x.label===new Date(date).toLocaleString("en-IN",{month:"short"})):days-1-Math.floor((Date.now()-new Date(date).getTime())/86400000);if(index>=0&&index<chart.length)chart[index].value=money(chart[index].value+Number(s.total||0));}
 return NextResponse.json({success:true,data:{period,from:r.from,to:r.to,businessName:String((await businessRef.get()).data()?.name||"Your business"),sales:{total:totalSales,count:sales.length,paid,collectionRate:totalSales?Math.round(paid/totalSales*100):0},profit:{estimated:money(totalSales-expenseTotal),margin:totalSales?Math.round((totalSales-expenseTotal)/totalSales*100):0,expenses:expenseTotal},receivables:{outstanding,count:sales.filter(s=>Number(s.balance||0)>0).length},inventory:{lowStockCount:lowStock.length,lowStock},recentSales:recent,chart}});}catch(e){const message=e instanceof Error?e.message:"Could not load dashboard.";return NextResponse.json({success:false,error:message},{status:(e as{status?:number}).status||500});}}
