"use client";
import {useState} from "react";
type Category={id:string;name:string;code?:string};
export default function ExpenseCategoryManager({businessId,categories,onChanged,canEdit}:{businessId:string;categories:Category[];onChanged:()=>void;canEdit:boolean}){
 const [open,setOpen]=useState(false),[name,setName]=useState(""),[code,setCode]=useState(""),[editing,setEditing]=useState<Category|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState("");
 async function auth(){const {firebaseAuth}=await import("../../lib/firebase");if(!firebaseAuth?.currentUser)throw new Error("You must be signed in.");return{Authorization:`Bearer ${await firebaseAuth.currentUser.getIdToken()}`,"Content-Type":"application/json"};}
 function start(c?:Category){setEditing(c??null);setName(c?.name??"");setCode(c?.code??"");setError("");setOpen(true);}
 async function save(){if(!name.trim())return setError("Category name is required.");setBusy(true);setError("");try{const r=await fetch("/api/accounting/expenses",{method:"POST",headers:await auth(),body:JSON.stringify({businessId,action:editing?"category_edit":"category_create",categoryId:editing?.id,name:name.trim(),code:code.trim()})});const d=await r.json();if(!r.ok||!d.success)throw new Error(d.error??"Could not save category.");setOpen(false);onChanged();}catch(e){setError(e instanceof Error?e.message:"Could not save category.");}finally{setBusy(false);}}
 async function remove(c:Category){if(!confirm(`Delete expense category “${c.name}”? Categories used by existing expenses cannot be deleted.`))return;setBusy(true);setError("");try{const r=await fetch("/api/accounting/expenses",{method:"POST",headers:await auth(),body:JSON.stringify({businessId,action:"category_delete",categoryId:c.id})});const d=await r.json();if(!r.ok||!d.success)throw new Error(d.error??"Could not delete category.");onChanged();}catch(e){setError(e instanceof Error?e.message:"Could not delete category.");}finally{setBusy(false);}}
 return <><button type="button" onClick={()=>start()} className="rounded-lg border px-3 py-2 text-sm font-semibold hover:bg-slate-50">⚙ Manage Categories</button>{open&&<div className="fixed inset-0 z-[60] flex items-center justify-center bg-black/30 p-4"><div className="w-full max-w-xl rounded-2xl bg-white shadow-2xl"><div className="flex items-center justify-between border-b px-5 py-4"><div><h3 className="font-bold">Expense Categories</h3><p className="text-xs text-slate-500">Add, edit or disable categories used by expense vouchers.</p></div><button onClick={()=>setOpen(false)} className="text-xl text-slate-500">×</button></div><div className="p-5">{error&&<div className="mb-3 rounded-lg border border-red-200 bg-red-50 px-3 py-2 text-sm text-red-700">{error}</div>}<div className="mb-4 flex gap-2"><input autoFocus value={name} onChange={e=>setName(e.target.value)} placeholder="Category name" className="erp-input h-10 flex-1 rounded-lg px-3 text-sm"/><input value={code} onChange={e=>setCode(e.target.value)} placeholder="Code (optional)" className="erp-input h-10 w-32 rounded-lg px-3 text-sm"/><button onClick={()=>void save()} disabled={busy} className="erp-btn-primary rounded-lg px-4 text-sm font-semibold">{editing?"Update":"Add"}</button></div><div className="max-h-72 overflow-y-auto rounded-lg border">{categories.length===0?<p className="p-6 text-center text-sm text-slate-500">No categories yet.</p>:categories.map(c=><div key={c.id} className="flex items-center justify-between border-b px-3 py-2 last:border-0"><div><span className="text-sm font-medium">{c.name}</span>{c.code&&<span className="ml-2 text-xs text-slate-400">{c.code}</span>}</div>{canEdit&&<div className="flex gap-1"><button onClick={()=>start(c)} className="rounded px-2 py-1 text-xs font-semibold hover:bg-slate-100">Edit</button><button onClick={()=>void remove(c)} disabled={busy} className="rounded px-2 py-1 text-xs font-semibold text-red-600 hover:bg-red-50">Delete</button></div>}</div>)}</div>{editing&&<button onClick={()=>start()} className="mt-3 text-xs font-semibold text-blue-600">+ Add new category</button>}</div></div></div>}</>;
}
