import { NextResponse } from "next/server";
import type { Firestore, Query } from "firebase-admin/firestore";
import { getAdminServices } from "@/infrastructure/firebase/admin";
import type { BusinessMember } from "@/types";
import { validateManufacturingConfig } from "@/core/accounting/manufacturing";
import { validateProductionPlan } from "@/core/accounting/manufacturingPlanning";
export const runtime="nodejs";
const fail=(message:string,status=400)=>NextResponse.json({success:false,error:message},{status});const text=(v:unknown)=>String(v??"").trim();
async function auth(request:Request){const{auth,db}=getAdminServices();const h=request.headers.get("authorization")||"";if(!h.startsWith("Bearer "))throw Object.assign(new Error("Authentication is required."),{statusCode:401});return{db,token:await auth.verifyIdToken(h.slice(7))};}
async function member(db:Firestore,businessId:string,uid:string){const s=await db.collection("businesses").doc(businessId).collection("members").doc(uid).get();if(!s.exists)throw Object.assign(new Error("You are not a member of this business."),{statusCode:403});const m=s.data() as BusinessMember;if(m.status!=="active")throw Object.assign(new Error("Your business membership is not active."),{statusCode:403});return m;}
function can(m:BusinessMember,edit:boolean){return m.role==="owner"||m.role==="admin"||!!m.permissions?.items?.[edit?"edit":"view"];}
export async function GET(request:Request){try{const{db,token}=await auth(request);const u=new URL(request.url),businessId=text(u.searchParams.get("businessId")),status=text(u.searchParams.get("status"));if(!businessId)return fail("Business ID is required.");const m=await member(db,businessId,token.uid);if(!can(m,false))return fail("Permission denied: production plans.",403);let q:Query=db.collection("businesses").doc(businessId).collection("productionPlans").limit(500);if(status)q=q.where("status","==",status);const s=await q.get();return NextResponse.json({success:true,plans:s.docs.map(d=>({id:d.id,...d.data()})).sort((a:any,b:any)=>String(a.dueDate||"").localeCompare(String(b.dueDate||"")))});}catch(e){return fail(e instanceof Error?e.message:"Unable to load production plans.",(e as{statusCode?:number}).statusCode||400);}}
export async function POST(request:Request){try{const{db,token}=await auth(request);const b=await request.json() as Record<string,unknown>,businessId=text(b.businessId),itemId=text(b.itemId),dueDate=text(b.dueDate),warehouseId=text(b.warehouseId)||undefined,notes=text(b.notes)||undefined;const plannedQuantity=Number(b.plannedQuantity);if(!businessId||!itemId)return fail("Business ID and item are required.");const m=await member(db,businessId,token.uid);if(!can(m,true))return fail("Permission denied: production plan edit.",403);validateProductionPlan({plannedQuantity,dueDate,bomVersion:Number(b.bomVersion||1),status:"draft"});const root=db.collection("businesses").doc(businessId),item=await root.collection("items").doc(itemId).get();if(!item.exists||item.data()?.businessId!==businessId)return fail("Manufactured item not found.",404);const config=item.data()?.manufacturing;if(!config?.enabled)return fail("Item is not configured for manufacturing.");const bomSnapshot=validateManufacturingConfig(config);const version=Number(config.version||b.bomVersion||1);const now=new Date().toISOString();const ref=root.collection("productionPlans").doc();const planNumber=`PLAN-${now.slice(0,10).replaceAll("-","")}-${ref.id.slice(0,6).toUpperCase()}`;await ref.set({id:ref.id,businessId,financialYearId:text(b.financialYearId)||null,planNumber,itemId,warehouseId:warehouseId||null,plannedQuantity,completedQuantity:0,dueDate,status:"draft",bomVersion:version,bomSnapshot,notes:notes||null,createdBy:token.uid,createdAt:now,updatedAt:now});return NextResponse.json({success:true,plan:{id:ref.id,planNumber,itemId,plannedQuantity,dueDate,status:"draft",bomVersion:version}});}catch(e){return fail(e instanceof Error?e.message:"Unable to create production plan.",(e as{statusCode?:number}).statusCode||400);}}
export async function PATCH(request:Request){try{const{db,token}=await auth(request);const b=await request.json() as Record<string,unknown>,businessId=text(b.businessId),id=text(b.planId),status=text(b.status);if(!businessId||!id)return fail("Business ID and plan ID are required.");if(!["released","cancelled"].includes(status))return fail("Only release or cancellation is allowed here.");const m=await member(db,businessId,token.uid);if(!can(m,true))return fail("Permission denied: production plan edit.",403);const ref=db.collection("businesses").doc(businessId).collection("productionPlans").doc(id),snap=await ref.get();if(!snap.exists)return fail("Production plan not found.",404);const p=snap.data() as Record<string,unknown>;if(p.businessId!==businessId)return fail("Production plan business mismatch.",403);if(status==="released"&&p.status!=="draft")return fail("Only draft plans can be released.");if(status==="cancelled"&&["completed","cancelled"].includes(String(p.status)))return fail("Completed or already cancelled plans cannot be cancelled.");await ref.set({status,updatedAt:new Date().toISOString(),updatedBy:token.uid},{merge:true});return NextResponse.json({success:true,id,status});}catch(e){return fail(e instanceof Error?e.message:"Unable to update production plan.",(e as{statusCode?:number}).statusCode||400);}}
