import { NextResponse } from "next/server";
import { getAdminServices } from "@/infrastructure/firebase/admin";
import { createAdminAccountingRepository } from "@/infrastructure/firebase/adminAccountingRepository";
import { createPurchase } from "@/application/purchases/service";
import { resolveFinancialYear } from "@/core/accounting/financialYear";
import type { AccountingPermission } from "@/core/accounting/authorization";

export const runtime="nodejs";
const errorResponse=(message:string,status=400)=>NextResponse.json({success:false,error:message},{status});
async function requireSetup(db:ReturnType<typeof getAdminServices>["db"],businessId:string,date:string){const ref=db.collection("businesses").doc(businessId);const snap=await ref.get();if(!snap.exists)throw new Error("Business does not exist.");const business=snap.data() as {setupStatus?:string;financialYearStartMonth?:number};if(business.setupStatus&&business.setupStatus!=="ready")throw new Error("Business accounting setup is not ready.");const fy=resolveFinancialYear(date,Number(business.financialYearStartMonth??4));if(!(await ref.collection("financialYears").doc(fy.id).get()).exists)throw new Error("Financial year is not initialized for this business.");return fy.id;}
export async function POST(request:Request){try{const{auth,db}=getAdminServices();const header=request.headers.get("authorization")||"";if(!header.startsWith("Bearer "))return errorResponse("Authentication is required.",401);const token=await auth.verifyIdToken(header.slice(7));const body=await request.json() as Record<string,unknown>;const businessId=String(body.businessId??"").trim(),date=String(body.date??"").trim();if(!businessId||!date)return errorResponse("Business and purchase date are required.");const ref=db.collection("businesses").doc(businessId);const memberSnap=await ref.collection("members").doc(token.uid).get();if(!memberSnap.exists)return errorResponse("You are not a member of this business.",403);const member=memberSnap.data() as {status?:string;role?:string;permissions?:Record<string,unknown>};if(member.status!=="active")return errorResponse("Your business membership is not active.",403);const permissions=(member.permissions?.purchase??{}) as Record<string,unknown>;if(!(member.role==="owner"||member.role==="admin"||permissions.create===true))return errorResponse("Permission denied: PURCHASE_CREATE.",403);const financialYearId=await requireSetup(db,businessId,date);const supplierId=typeof body.supplierId==="string"&&body.supplierId?body.supplierId:undefined;let partyLedger="acct-creditors";if(supplierId){const snap=await ref.collection("parties").doc(supplierId).get();if(!snap.exists)return errorResponse("Selected supplier does not exist.");const party=snap.data() as {businessId?:string;kind?:string;status?:string;ledgerAccountId?:string;payableLedgerAccountId?:string};if(party.businessId!==businessId||!(["supplier","both"].includes(String(party.kind))))return errorResponse("Selected party is not a supplier of this business.");if(party.status!=="active")return errorResponse("Selected supplier is inactive.");partyLedger=String(party.payableLedgerAccountId??party.ledgerAccountId??"");if(!partyLedger)return errorResponse("Selected supplier has no payable ledger account.");}
const mode=String(body.mode??"credit") as "credit"|"cash"|"bank";if(!["credit","cash","bank"].includes(mode))return errorResponse("Invalid purchase settlement mode.");const bankAccountId=typeof body.bankAccountId==="string"&&body.bankAccountId?body.bankAccountId:undefined;let bankLedger:string|undefined;if(mode==="bank"){if(!bankAccountId)return errorResponse("Bank account is required for a bank purchase.");const snap=await ref.collection("bankAccounts").doc(bankAccountId).get();if(!snap.exists)return errorResponse("Selected bank account does not exist.");const bank=snap.data() as {status?:string;kind?:string;ledgerAccountId?:string};if(bank.status!=="active"||bank.kind!=="bank")return errorResponse("Selected bank account is not active.");bankLedger=String(bank.ledgerAccountId??"");if(!bankLedger)return errorResponse("Selected bank account is not linked to a ledger account.");const ledger=await ref.collection("accounts").doc(bankLedger).get();const account=ledger.data() as {active?:boolean;type?:string}|undefined;if(!ledger.exists||account?.active===false||account?.type!=="asset")return errorResponse("Selected bank ledger account is invalid.");}
const paidAmount=Object.prototype.hasOwnProperty.call(body,"paidAmount")?Number(body.paidAmount):undefined;const repo=createAdminAccountingRepository(businessId);const result=await createPurchase({repo,ids:{next:p=>`${p}-${crypto.randomUUID()}`},clock:{now:()=>new Date().toISOString()}},{businessId,userId:token.uid,financialYearId,idempotencyKey:String(body.idempotencyKey??`purchase-${businessId}-${crypto.randomUUID()}`),permissions:["PURCHASE_CREATE" as AccountingPermission]},{supplierId,taxableValue:Number(body.taxableValue),grossValue:body.grossValue===undefined?undefined:Number(body.grossValue),discountPercent:Number(body.discountPercent??0),discountAmount:Number(body.discountAmount??0),taxRate:Number(body.taxRate??0),intraState:Boolean(body.intraState),cessRate:Number(body.cessRate??0),mode,paidAmount,supplierInvoiceNumber:typeof body.supplierInvoiceNumber==="string"?body.supplierInvoiceNumber:undefined,accountMap:{party:partyLedger,cash:"acct-cash",bank:bankLedger||"acct-bank",inputCgst:"acct-input-cgst",inputSgst:"acct-input-sgst",inputIgst:"acct-input-igst",inputCess:"acct-input-cess",inventory:"acct-inventory"},itemMovements:Array.isArray(body.itemMovements)?body.itemMovements as Array<{itemId:string;quantity:number;unitCost:number;warehouseId?:string;batchId?:string;batchNumber?:string;manufactureDate?:string;expiryDate?:string;serialNumbers?:string[];unitId?:string;quantityInBaseUnit?:number}>:[],narration:typeof body.narration==="string"?body.narration:undefined,documentId:typeof body.documentId==="string"&&body.documentId?body.documentId:undefined,documentPayload:body.documentPayload&&typeof body.documentPayload==="object"?body.documentPayload as Record<string,unknown>:undefined});return NextResponse.json({success:true,result});}catch(error){const message=error instanceof Error?error.message:"Could not post purchase.";const status=/authentication|token|credential/i.test(message)?401:/permission|member/i.test(message)?403:/conflict|duplicate|idempotency/i.test(message)?409:400;return errorResponse(message,status);}}
