import { collection, doc, query, where, runTransaction, type Firestore, type Transaction } from "firebase/firestore";
import type { AccountingRepository, AccountingTransaction, Account, AtomicAccountingDocument, AuditEvent, FinancialYear, LedgerEntry, PartyAllocation, ReturnDocument, StockMovement, Voucher, VoucherLine } from "@/core/accounting/types";
import { ValidationError } from "@/core/accounting/errors";
import { normalizeWarehouseId } from "@/core/accounting/stock";
import { firestoreSafe } from "@/core/accounting/firestoreSafe";

const assertId=(value:string,name:string)=>{if(!value||typeof value!=="string")throw new ValidationError(`${name} is required for Firestore accounting.`);return value;};
const ref=(db:Firestore,businessId:string,collectionName:string,id:string)=>{if(!db)throw new ValidationError("Firestore database is not initialized. Check Firebase configuration.");assertId(businessId,"Business ID");assertId(collectionName,"Firestore collection");assertId(id,`Firestore document ID for ${collectionName}`);return doc(db,"businesses",businessId,collectionName,id);};
const col=(db:Firestore,businessId:string,collectionName:string)=>{if(!db)throw new ValidationError("Firestore database is not initialized. Check Firebase configuration.");assertId(businessId,"Business ID");assertId(collectionName,"Firestore collection");return collection(db,"businesses",businessId,collectionName);};
function toAccount(data:Record<string,unknown>,id:string):Account{return{id,businessId:String(data.businessId??""),code:String(data.code??""),name:String(data.name??""),type:data.type as Account["type"],parentId:(data.parentId as string|null|undefined)??null,systemAccount:Boolean(data.systemAccount),active:data.active!==false,openingDebit:Number(data.openingDebit??0),openingCredit:Number(data.openingCredit??0),createdAt:String(data.createdAt??""),updatedAt:String(data.updatedAt??"")};}
class FirestoreAccountingTransaction implements AccountingTransaction{
 constructor(private readonly db:Firestore,private readonly tx:Transaction,private readonly businessId:string){if(!db)throw new ValidationError("Firestore database is not initialized.");assertId(businessId,"Business ID");}
 async getFinancialYear(id:string){const s=await this.tx.get(ref(this.db,this.businessId,"financialYears",id));return s.exists()?s.data() as FinancialYear:null;}
 async getAccount(id:string){const s=await this.tx.get(ref(this.db,this.businessId,"accounts",id));return s.exists()?toAccount(s.data() as Record<string,unknown>,s.id):null;}
 async getVoucher(id:string){const s=await this.tx.get(ref(this.db,this.businessId,"vouchers",id));return s.exists()?s.data() as Voucher:null;}
 async getVoucherLines(voucherId:string){assertId(voucherId,"Voucher ID");const s=await this.tx.get(query(col(this.db,this.businessId,"voucherLines"),where("voucherId","==",voucherId)));return s.docs.map(d=>d.data() as VoucherLine).sort((a,b)=>a.lineNo-b.lineNo);}
 async getVouchersByReference(referenceType:string,referenceId:string){const s=await this.tx.get(query(col(this.db,this.businessId,"vouchers"),where("referenceType","==",referenceType),where("referenceId","==",referenceId)));return s.docs.map(d=>d.data() as Voucher).filter(v=>v.status==="posted");}
 async getVoucherByIdempotencyKey(businessId:string,financialYearId:string,idempotencyKey:string){if(businessId!==this.businessId)return null;const s=await this.tx.get(query(col(this.db,this.businessId,"vouchers"),where("financialYearId","==",financialYearId),where("idempotencyKey","==",idempotencyKey)));const d=s.docs.find(x=>x.exists());return d?d.data() as Voucher:null;}
 async getAtomicDocumentByIdempotencyKey(businessId:string,financialYearId:string,idempotencyKey:string){if(businessId!==this.businessId)return null;const s=await this.tx.get(query(col(this.db,this.businessId,"accountingDocuments"),where("financialYearId","==",financialYearId),where("idempotencyKey","==",idempotencyKey)));const d=s.docs.find(x=>x.exists());return d?d.data() as AtomicAccountingDocument:null;}
 async getStockMovementsForSource(sourceId:string){assertId(sourceId,"Stock source ID");const s=await this.tx.get(query(col(this.db,this.businessId,"stockMovements"),where("sourceId","==",sourceId)));return s.docs.map(d=>d.data() as StockMovement);}
 async getStockMovementsForItem(itemId:string,warehouseId?:string,throughDate?:string){assertId(itemId,"Item ID");const wanted=warehouseId?normalizeWarehouseId(warehouseId):undefined;const constraints=wanted?[where("itemId","==",itemId),where("warehouseId","==",wanted)]:[where("itemId","==",itemId)];const s=await this.tx.get(query(col(this.db,this.businessId,"stockMovements"),...constraints));return s.docs.map(d=>d.data() as StockMovement).filter(m=>!throughDate||m.date<=throughDate).sort((a,b)=>`${a.date}:${a.createdAt}:${a.id}`.localeCompare(`${b.date}:${b.createdAt}:${b.id}`));}
 async getPartyAllocationsForVoucher(voucherId:string){assertId(voucherId,"Voucher ID");const c=col(this.db,this.businessId,"partyAllocations");const a=await this.tx.get(query(c,where("fromVoucherId","==",voucherId)));const b=await this.tx.get(query(c,where("toVoucherId","==",voucherId)));const map=new Map<string,PartyAllocation>();for(const d of [...a.docs,...b.docs])map.set(d.id,d.data() as PartyAllocation);return[...map.values()];}
 async getBusinessDocument(collectionName:string,id:string){if(!/^[A-Za-z0-9_-]{1,64}$/.test(collectionName)||!id)throw new ValidationError("Invalid business document reference.");const s=await this.tx.get(ref(this.db,this.businessId,collectionName,id));if(!s.exists())return null;const data=(s.data()??{}) as Record<string,unknown>;if(collectionName!=="items")return data;const movements=await this.tx.get(query(col(this.db,this.businessId,"stockMovements"),where("itemId","==",id)));let stock=0;let stockValue=0;for(const d of movements.docs){const m=d.data() as StockMovement;stock+=m.direction==="in"?m.quantity:-m.quantity;stockValue+=m.direction==="in"?m.value:-m.value;}return{...data,stock,stockValue,stockReconciliationSource:"stockMovements"};}
 async saveAccount(account:Account){if(account.businessId!==this.businessId)throw new ValidationError("Business mismatch while saving account.");this.tx.set(ref(this.db,this.businessId,"accounts",account.id),firestoreSafe(account),{merge:false});}
 async saveVoucher(voucher:Voucher){this.tx.set(ref(this.db,this.businessId,"vouchers",voucher.id),firestoreSafe(voucher));}
 async saveVoucherLines(lines:VoucherLine[]){for(const line of lines)this.tx.set(ref(this.db,this.businessId,"voucherLines",line.lineId),firestoreSafe(line));}
 async saveLedgerEntries(entries:LedgerEntry[]){for(const entry of entries)this.tx.set(ref(this.db,this.businessId,"ledgerEntries",entry.lineId),firestoreSafe(entry));}
 async saveStockMovements(movements:StockMovement[]){for(const movement of movements)this.tx.set(ref(this.db,this.businessId,"stockMovements",movement.id),firestoreSafe(movement));}
 async savePartyAllocations(allocations:PartyAllocation[]){for(const a of allocations){if(a.businessId!==this.businessId)throw new ValidationError("Business mismatch while saving party allocation.");this.tx.set(ref(this.db,this.businessId,"partyAllocations",a.id),firestoreSafe(a));}}
 async saveReturnDocument(document:ReturnDocument){if(document.businessId!==this.businessId)throw new ValidationError("Business mismatch while saving return document.");this.tx.set(ref(this.db,this.businessId,"returnDocuments",document.id),firestoreSafe(document));}
 async saveAtomicDocument(document:AtomicAccountingDocument){if(document.businessId!==this.businessId)throw new ValidationError("Business mismatch while saving atomic document.");this.tx.set(ref(this.db,this.businessId,"accountingDocuments",document.id),firestoreSafe(document));}
 async saveBusinessDocument(collectionName:string,id:string,data:Record<string,unknown>){if(!/^[A-Za-z0-9_-]{1,64}$/.test(collectionName)||!id)throw new ValidationError("Invalid business document collection.");if(String(data.businessId??"")!==this.businessId)throw new ValidationError("Business document business mismatch.");this.tx.set(ref(this.db,this.businessId,collectionName,id),firestoreSafe(data),{merge:true});}
 async saveAuditEvent(event:AuditEvent){this.tx.set(ref(this.db,this.businessId,"auditLogs",event.id),firestoreSafe(event));}
 async allocateVoucherNumber(input:{businessId:string;financialYearId:string;voucherType:string;prefix?:string}){if(input.businessId!==this.businessId)throw new ValidationError("Business mismatch while allocating voucher number.");const sequenceId=`${input.financialYearId}_${input.voucherType}`.replace(/[^a-zA-Z0-9_-]/g,"_");const sequenceRef=ref(this.db,this.businessId,"voucherSequences",sequenceId);const snap=await this.tx.get(sequenceRef);const next=Number(snap.exists()?snap.data().nextNumber??1:1);if(!Number.isSafeInteger(next)||next<1)throw new ValidationError("Invalid voucher sequence state.");const prefix=input.prefix??input.voucherType.toUpperCase();this.tx.set(sequenceRef,firestoreSafe({businessId:this.businessId,financialYearId:input.financialYearId,voucherType:input.voucherType,prefix,nextNumber:next+1,updatedAt:new Date().toISOString()}),{merge:true});return`${prefix}-${String(next).padStart(6,"0")}`;}}
export function createFirestoreAccountingRepository(db:Firestore,businessId:string):AccountingRepository{if(!db)throw new ValidationError("Firestore database is not initialized.");assertId(businessId,"businessId");return{runInTransaction:<T>(work:(tx:AccountingTransaction)=>Promise<T>)=>runTransaction(db,rawTx=>work(new FirestoreAccountingTransaction(db,rawTx,businessId)))};}
