import { NextResponse } from "next/server";
import type { Firestore } from "firebase-admin/firestore";
import { getAdminServices } from "@/infrastructure/firebase/admin";
import { createAdminAccountingRepository } from "@/infrastructure/firebase/adminAccountingRepository";
import { executeOpeningStock, executeStockAdjustment, executeStockTransfer, executeStockLedger } from "@/application/inventory/service";
import { firestoreSafe } from "@/core/accounting/firestoreSafe";
import type { BusinessMember } from "@/types";
import type { StockValuationMethod } from "@/core/accounting/valuation";
export const runtime="nodejs";
const err=(message:string,status=400)=>NextResponse.json({success:false,error:message},{status});
async function auth(request:Request){const{auth,db}=getAdminServices();const h=request.headers.get("authorization")||"";if(!h.startsWith("Bearer "))throw new Error("Authentication is required.");return{db,token:await auth.verifyIdToken(h.slice(7))};}
async function member(db:Firestore,businessId:string,uid:string){const s=await db.collection("businesses").doc(businessId).collection("members").doc(uid).get();if(!s.exists)throw Object.assign(new Error("You are not a member of this business."),{statusCode:403});const m=s.data() as BusinessMember;if(m.status!=="active")throw Object.assign(new Error("Your business membership is not active."),{statusCode:403});return m;}
function allowed(m:BusinessMember,action:"view"|"adjust"|"transfer"|"opening"){if(m.role==="owner"||m.role==="admin")return true;if(action==="view")return!!m.permissions?.inventory?.view;if(action==="adjust"||action==="transfer")return!!m.permissions?.inventory?.edit||!!m.permissions?.inventory?.create;return!!m.permissions?.inventory?.create;}
async function fy(db:Firestore,businessId:string){const s=await db.collection("businesses").doc(businessId).collection("financialYears").where("locked","==",false).get();const docs=s.docs.sort((a,b)=>String(b.data()?.startDate||"").localeCompare(String(a.data()?.startDate||"")));if(!docs.length)throw new Error("No active financial year is configured for this business.");return docs[0].id;}
const deps={ids:{next:(p:string)=>`${p}-${crypto.randomUUID()}`},clock:{now:()=>new Date().toISOString()}};
const accounts={inventory:"acct-inventory",openingEquity:"acct-opening-balance",stockAdjustmentGain:"acct-stock-gain",stockAdjustmentLoss:"acct-stock-loss"};
function permissions(action:string){return action==="opening"?["OPENING_CREATE" as const]:action==="adjust"?["INVENTORY_ADJUST" as const]:action==="transfer"?["INVENTORY_TRANSFER" as const]:["INVENTORY_VIEW" as const];}
export async function GET(request:Request){try{const{db,token}=await auth(request);const u=new URL(request.url);const businessId=String(u.searchParams.get("businessId")||"").trim();const itemId=String(u.searchParams.get("itemId")||"").trim();if(!businessId)return err("Business ID is required.");const m=await member(db,businessId,token.uid);if(!allowed(m,"view"))return err("Permission denied: inventory view.",403);const financialYearId=await fy(db,businessId);if(itemId){const repo=createAdminAccountingRepository(businessId);const ledger=await executeStockLedger({repo,...deps},{businessId,userId:token.uid,financialYearId,idempotencyKey:`inventory-view-${crypto.randomUUID()}`,permissions:permissions("view")},itemId,u.searchParams.get("warehouseId")||undefined,u.searchParams.get("throughDate")||undefined);return NextResponse.json({success:true,ledger});}const snap=await db.collection("businesses").doc(businessId).collection("items").get();return NextResponse.json({success:true,items:snap.docs.map(d=>({id:d.id,...d.data()}))});}catch(e){const m=e instanceof Error?e.message:"Could not load inventory.";return err(m,(e as{statusCode?:number}).statusCode||400);}}
export async function POST(request:Request){try{const{db,token}=await auth(request);const body=await request.json() as Record<string,unknown>;const businessId=String(body.businessId||"").trim();const action=String(body.action||body.operation||"");if(!businessId)return err("Business ID is required.");const m=await member(db,businessId,token.uid);const check=action==="opening"?"opening":action==="adjust"?"adjust":action==="transfer"?"transfer":"view";if(check==="view")return err("Unsupported inventory action.");if(!allowed(m,check))return err(`Permission denied: inventory ${check}.`,403);const financialYearId=await fy(db,businessId);const repo=createAdminAccountingRepository(businessId);const idempotencyKey=String(body.idempotencyKey||"").trim()||`inventory-${crypto.randomUUID()}`;const raw=(body.input||body) as Record<string,unknown>;const input=firestoreSafe({...raw,date:raw.date||new Date().toISOString().slice(0,10),sourceId:raw.sourceId||idempotencyKey});const ctx={businessId,userId:token.uid,financialYearId,idempotencyKey,permissions:permissions(action)};let result:unknown;if(action==="opening")result=await executeOpeningStock({repo,...deps},ctx,{...input,accountMap:accounts,idempotencyKey} as never);else if(action==="adjust")result=await executeStockAdjustment({repo,...deps},ctx,{...input,accountMap:accounts,idempotencyKey} as never);else if(action==="transfer"){const settingsSnap=await db.collection("businesses").doc(businessId).collection("settings").doc("business").get();const settings=(settingsSnap.data()||{}) as Record<string,unknown>;const txSettings=(settings.transactions||{}) as Record<string,unknown>;const method:StockValuationMethod=txSettings.inventoryValuationMethod==="weighted_average"||settings.inventoryValuationMethod==="weighted_average"?"weighted_average":"fifo";result=await executeStockTransfer({repo,...deps},ctx,{...input,idempotencyKey,valuationMethod:method} as never);}else return err("Unsupported inventory action.");return NextResponse.json({success:true,result});}catch(e){const m=e instanceof Error?e.message:"Inventory operation failed.";return err(m,(e as{statusCode?:number}).statusCode||400);}}
export async function PATCH(request:Request){try{const{db,token}=await auth(request);const body=await request.json() as Record<string,unknown>;const businessId=String(body.businessId||"").trim();const itemId=String(body.itemId||"").trim();if(!businessId||!itemId)return err("Business ID and item ID are required.");const m=await member(db,businessId,token.uid);if(!(m.role==="owner"||m.role==="admin"||m.permissions?.items?.edit))return err("Permission denied: item edit.",403);const allowedFields=firestoreSafe({name:body.name,code:body.code,unit:body.unit,itemType:body.itemType,categoryId:body.categoryId,brand:body.brand,hsnSac:body.hsnSac,gstRate:body.gstRate,salePrice:body.salePrice,purchasePrice:body.purchasePrice,mrp:body.mrp,minStock:body.minStock,maxStock:body.maxStock,reorderLevel:body.reorderLevel,status:body.status});await db.collection("businesses").doc(businessId).collection("items").doc(itemId).set(firestoreSafe({businessId,itemId,...allowedFields,updatedAt:new Date().toISOString()}),{merge:true});return NextResponse.json({success:true});}catch(e){return err(e instanceof Error?e.message:"Could not update item.",(e as{statusCode?:number}).statusCode||400);}}
