import { NextResponse } from "next/server";
import { getAdminServices } from "@/infrastructure/firebase/admin";
import { buildPartyReconciliation } from "@/core/accounting/party";
import type { LedgerEntry, PartyAllocation } from "@/core/accounting/types";
export const runtime="nodejs";
function fail(message:string,status=400){return NextResponse.json({success:false,error:message},{status});}
export async function GET(r:Request){try{const{auth,db}=getAdminServices();const h=r.headers.get("authorization")||"";if(!h.startsWith("Bearer "))return fail("Authentication is required.",401);const token=await auth.verifyIdToken(h.slice(7));const u=new URL(r.url),businessId=String(u.searchParams.get("businessId")||"").trim(),kind=String(u.searchParams.get("kind")||"customer") as "customer"|"supplier"|"both",asOf=String(u.searchParams.get("asOf")||new Date().toISOString().slice(0,10));if(!businessId||!/[a-z]+/.test(kind))return fail("Business ID and party kind are required.");if(!["customer","supplier","both"].includes(kind))return fail("Party kind must be customer, supplier or both.");if(!/^\d{4}-\d{2}-\d{2}$/.test(asOf))return fail("As-of date must be YYYY-MM-DD.");const ref=db.collection("businesses").doc(businessId),member=await ref.collection("members").doc(token.uid).get();if(!member.exists||member.data()?.status!=="active")return fail("Active business membership is required.",403);const permissions=(member.data()?.permissions?.parties||{}) as Record<string,unknown>;if(member.data()?.role!=="owner"&&member.data()?.role!=="admin"&&permissions.view!==true)return fail("Permission denied: PARTY_VIEW.",403);
 const partiesSnap=await ref.collection("parties").get();const parties=partiesSnap.docs.map(d=>({id:d.id,...(d.data() as Record<string,unknown>)})).filter(p=>kind==="both"?true:p.kind===kind||p.kind==="both");const partyIds=new Set(parties.map(p=>p.id));const ledgerSnap=await ref.collection("ledgerEntries").where("date","<=",asOf).get();const entries=ledgerSnap.docs.map(d=>d.data() as LedgerEntry).filter(e=>partyIds.has(String(e.partyId||"")));const allocSnap=await ref.collection("partyAllocations").get();const allocations=allocSnap.docs.map(d=>d.data() as PartyAllocation).filter(a=>partyIds.has(a.partyId)&&a.date<=asOf);
 const rows=parties.map(p=>{const role=(p.kind===kind?p.kind:(kind==="supplier"?"supplier":"customer")) as "customer"|"supplier";const ownEntries=entries.filter(e=>e.partyId===p.id);const ownAlloc=allocations.filter(a=>a.partyId===p.id);const reconciliation=buildPartyReconciliation(ownEntries,ownAlloc,p.id,role);return{id:p.id,partyCode:String(p.partyCode||""),name:String(p.name||""),phone:String(p.phone||""),debit:reconciliation.ledgerDebit,credit:reconciliation.ledgerCredit,net:reconciliation.ledgerNet,outstanding:reconciliation.billOutstanding,advance:reconciliation.advance,creditLimit:Number(p.creditLimit||0),status:String(p.status||"active"),reconciled:reconciliation.reconciled};}).filter(x=>x.outstanding>0).sort((a,b)=>b.outstanding-a.outstanding);
 return NextResponse.json({success:true,kind,asOf,rows,total:rows.reduce((s,x)=>s+x.outstanding,0),reconciled:rows.every(x=>x.reconciled)});
 }catch(e){const message=e instanceof Error?e.message:"Could not load outstanding.";return fail(message,500)}}
