import { NextResponse } from "next/server";
import { getAdminServices } from "@/infrastructure/firebase/admin";
import { createAdminAccountingRepository } from "@/infrastructure/firebase/adminAccountingRepository";
import { postSaleReturn } from "@/core/accounting/returns";
import type { Account, VoucherLine, StockMovement } from "@/core/accounting/types";

export const runtime = "nodejs";
const errorResponse=(message:string,status=400)=>NextResponse.json({success:false,error:message},{status});
function fyFor(date:string){if(!/^\d{4}-\d{2}-\d{2}$/.test(date))throw new Error("Return date must be YYYY-MM-DD.");const y=Number(date.slice(0,4)),m=Number(date.slice(5,7)),start=m>=4?y:y-1;return{id:`fy-${start}-${String(start+1).slice(-2)}`,startDate:`${start}-04-01`,endDate:`${start+1}-03-31`};}
function assertMoney(value:number,name:string){if(!Number.isSafeInteger(value)||value<0)throw new Error(`${name} is invalid.`);return value;}
const num=(v:unknown)=>typeof v==="number"&&Number.isFinite(v)?v:Number(v??0);

export async function POST(request:Request){
  try{
    const{auth,db}=getAdminServices();const header=request.headers.get("authorization")||"";if(!header.startsWith("Bearer "))return errorResponse("Authentication is required.",401);const token=await auth.verifyIdToken(header.slice(7));const body=await request.json() as Record<string,unknown>;
    const businessId=String(body.businessId??"").trim(),originalVoucherId=String(body.originalVoucherId??"").trim(),saleDocumentId=String(body.saleDocumentId??"").trim(),date=String(body.date??"").trim(),idempotencyKey=String(body.idempotencyKey??"").trim(),mode=String(body.mode??"") as "credit"|"cash"|"bank";
    if(!businessId||!originalVoucherId||!saleDocumentId||!date||!idempotencyKey)return errorResponse("Business, original voucher, sale document, date and idempotency key are required.");if(!["credit","cash","bank"].includes(mode))return errorResponse("Invalid return settlement mode.");
    const businessRef=db.collection("businesses").doc(businessId);const memberSnap=await businessRef.collection("members").doc(token.uid).get();if(!memberSnap.exists)return errorResponse("You are not a member of this business.",403);const member=memberSnap.data() as {status?:string;role?:string;permissions?:Record<string,unknown>};if(member.status!=="active")return errorResponse("Your business membership is not active.",403);const permissions=(member.permissions?.sales??{}) as Record<string,unknown>;if(!(member.role==="owner"||member.role==="admin"||permissions.create===true))return errorResponse("Permission denied: SALE_RETURN_CREATE.",403);
    const fy=fyFor(date);const [originalSnap,fySnap,accountsSnap,saleSnap,lineSnap,movementSnap]=await Promise.all([
      businessRef.collection("vouchers").doc(originalVoucherId).get(),businessRef.collection("financialYears").doc(fy.id).get(),businessRef.collection("accounts").get(),businessRef.collection("sales").doc(saleDocumentId).get(),businessRef.collection("voucherLines").where("voucherId","==",originalVoucherId).get(),businessRef.collection("stockMovements").where("sourceId","==",originalVoucherId).get()
    ]);
    if(!fySnap.exists)return errorResponse("Financial year is not initialized for this business.");if(!originalSnap.exists)return errorResponse("Original voucher was not found.");const original=originalSnap.data() as Record<string,unknown>;if(String(original.businessId??"")!==businessId||String(original.voucherType??"")!=="SALE"||String(original.status??"")!=="posted")return errorResponse("Only a posted sale from this business can be returned.");if(!saleSnap.exists)return errorResponse("Original sale document was not found.");
    const accounts=accountsSnap.docs.map(d=>({id:d.id,...d.data()} as Account));const byCode=(code:string)=>accounts.find(a=>a.code===code)?.id;const sales=byCode("4000");if(!sales)return errorResponse("Sales account is not configured.");
    const outputCgst=byCode("2101"),outputSgst=byCode("2102"),outputIgst=byCode("2103"),outputCess=byCode("2104");const lines=lineSnap.docs.map(d=>d.data() as VoucherLine);
    const taxable=lines.filter(l=>l.accountId===sales).reduce((s,l)=>s+l.credit-l.debit,0);const cgst=outputCgst?lines.filter(l=>l.accountId===outputCgst).reduce((s,l)=>s+l.credit-l.debit,0):0;const sgst=outputSgst?lines.filter(l=>l.accountId===outputSgst).reduce((s,l)=>s+l.credit-l.debit,0):0;const igst=outputIgst?lines.filter(l=>l.accountId===outputIgst).reduce((s,l)=>s+l.credit-l.debit,0):0;const cess=outputCess?lines.filter(l=>l.accountId===outputCess).reduce((s,l)=>s+l.credit-l.debit,0):0;const taxRate=taxable>0?Number((((cgst+sgst+igst)/taxable)*100).toFixed(6)):0;const cessRate=taxable>0?Number(((cess/taxable)*100).toFixed(6)):0;const intraState=cgst>0||sgst>0;
    const sale=saleSnap.data() as Record<string,unknown>;const saleItems=Array.isArray(sale.items)?sale.items as Array<Record<string,unknown>>:[];const originalItems=new Map<string,Record<string,unknown>>();for(const item of saleItems){const itemId=String(item.itemId??"");if(itemId&&!originalItems.has(itemId))originalItems.set(itemId,item);}
    const movements=movementSnap.docs.map(d=>d.data() as StockMovement).filter(m=>m.sourceType==="sale");if(!movements.length)return errorResponse("Original sale has no stock movements available for return.");
    const requested=Array.isArray(body.items)?body.items as Array<Record<string,unknown>>:[];if(!requested.length)return errorResponse("At least one return item is required.");let returnTaxableRupees=0;
    const items=requested.map(raw=>{const itemId=String(raw.itemId??"");const quantity=num(raw.quantity);if(!itemId||!Number.isInteger(quantity)||quantity<=0)throw new Error("Return item and quantity must be a positive whole quantity.");const originalItem=originalItems.get(itemId);if(!originalItem)throw new Error(`Item ${itemId} was not found on the original sale.`);const soldQuantity=num(originalItem.quantity);const unitPrice=num(originalItem.price);if(quantity>soldQuantity)throw new Error(`Return quantity for ${itemId} exceeds the original quantity.`);const matching=movements.filter(m=>m.itemId===itemId);if(!matching.length)throw new Error(`No original stock movement was found for ${itemId}.`);const requestedWarehouse=typeof raw.warehouseId==="string"&&raw.warehouseId?raw.warehouseId:undefined;const warehouses=[...new Set(matching.map(m=>m.warehouseId||"default"))];const warehouseId=requestedWarehouse|| (warehouses.length===1?warehouses[0]:undefined);if(!warehouseId)throw new Error(`Select the warehouse for ${itemId}; the original sale used multiple warehouses.`);if(!matching.some(m=>(m.warehouseId||"default")===warehouseId))throw new Error(`Warehouse ${warehouseId} was not used by the original sale for ${itemId}.`);const batchId=typeof raw.batchId==="string"&&raw.batchId?raw.batchId:undefined;const batchNumber=typeof raw.batchNumber==="string"&&raw.batchNumber?raw.batchNumber:undefined;const candidate=matching.filter(m=>(m.warehouseId||"default")===warehouseId);const batchSet=[...new Set(candidate.map(m=>m.batchId||""))];if(!batchId&&batchSet.filter(Boolean).length===1){const only=candidate.find(m=>m.batchId);if(only){returnTaxableRupees+=quantity*unitPrice;return{itemId,quantity,warehouseId,batchId:only.batchId,batchNumber:only.batchNumber,manufactureDate:only.manufactureDate,expiryDate:only.expiryDate,serialNumbers:typeof raw.serialNumbers!=="undefined"?raw.serialNumbers as string[]:undefined};}}returnTaxableRupees+=quantity*unitPrice;return{itemId,quantity,warehouseId,batchId,batchNumber,serialNumbers:typeof raw.serialNumbers!=="undefined"?raw.serialNumbers as string[]:undefined};});
    if(!(returnTaxableRupees>0))return errorResponse("Return taxable value must be positive.");const taxableValuePaise=assertMoney(Math.round(returnTaxableRupees*100),"Return taxable value");const customerId=typeof body.customerId==="string"&&body.customerId?body.customerId:undefined;
    let settlementAccountId:string|undefined;if(mode==="credit"){if(!customerId)return errorResponse("Customer is required for a credit return.");const partySnap=await businessRef.collection("parties").doc(customerId).get();if(!partySnap.exists)return errorResponse("Customer was not found.");const party=partySnap.data() as Record<string,unknown>;if(String(party.businessId??"")!==businessId||String(party.kind??"")!=="customer")return errorResponse("Selected party is not a customer of this business.");if(party.status!==undefined&&party.status!=="active")return errorResponse("Selected customer is inactive.");settlementAccountId=typeof party.ledgerAccountId==="string"?party.ledgerAccountId:undefined;if(!settlementAccountId)return errorResponse("Customer has no linked ledger account.");}
    else {const saleBank=typeof sale.bankAccountId==="string"&&sale.bankAccountId?sale.bankAccountId:undefined;const candidate=mode==="bank"?saleBank:undefined;settlementAccountId=candidate||lines.find(l=>l.debit>0&&l.accountId!==sales&&l.accountId!==outputCgst&&l.accountId!==outputSgst&&l.accountId!==outputIgst&&l.accountId!==outputCess)?.accountId;if(!settlementAccountId)return errorResponse(`Could not determine the original ${mode} settlement account. Open the sale and verify its payment account.`);const settlement=accounts.find(a=>a.id===settlementAccountId);if(!settlement||!settlement.active||settlement.type!=="asset")return errorResponse("The original settlement account is missing or inactive.");}
    const repo=createAdminAccountingRepository(businessId);const result=await postSaleReturn(repo,{businessId,financialYearId:fy.id,date,userId:token.uid,partyId:customerId,taxableValue:taxableValuePaise,taxRate,intraState,cessRate,narration:typeof body.narration==="string"?body.narration:undefined,originalVoucherId,idempotencyKey,mode,accountMap:{party:settlementAccountId,cash:mode==="cash"?settlementAccountId:undefined,bank:mode==="bank"?settlementAccountId:undefined,salesReturn:byCode("4900"),sales,inventory:byCode("1300"),cogs:byCode("5100"),outputCgst,outputSgst,outputIgst,outputCess},items},{ids:{next:prefix=>`${prefix}-${crypto.randomUUID()}`},clock:{now:()=>new Date().toISOString()}});
    return NextResponse.json({success:true,result});
  }catch(error){const message=error instanceof Error?error.message:"Could not post sales return.";const status=/authentication|token|credential/i.test(message)?401:/permission|member/i.test(message)?403:/idempotency|duplicate|conflict/i.test(message)?409:400;return errorResponse(message,status);}
}
