import { NextResponse } from "next/server";
import { getAdminServices } from "@/infrastructure/firebase/admin";
import { createAdminAccountingRepository } from "@/infrastructure/firebase/adminAccountingRepository";
import { postSaleReturn } from "@/core/accounting/returns";
import type { Account, VoucherLine } from "@/core/accounting/types";

export const runtime = "nodejs";

const errorResponse=(message:string,status=400)=>NextResponse.json({success:false,error:message},{status});
function fyFor(date:string){if(!/^\d{4}-\d{2}-\d{2}$/.test(date))throw new Error("Return date must be YYYY-MM-DD.");const y=Number(date.slice(0,4)),m=Number(date.slice(5,7)),start=m>=4?y:y-1;return{id:`fy-${start}-${String(start+1).slice(-2)}`,startDate:`${start}-04-01`,endDate:`${start+1}-03-31`};}
function assertMoney(value:number,name:string){if(!Number.isSafeInteger(value)||value<0)throw new Error(`${name} is invalid.`);return value;}

export async function POST(request:Request){
  try{
    const{auth,db}=getAdminServices();const header=request.headers.get("authorization")||"";if(!header.startsWith("Bearer "))return errorResponse("Authentication is required.",401);const token=await auth.verifyIdToken(header.slice(7));const body=await request.json() as Record<string,unknown>;
    const businessId=String(body.businessId??"").trim(),originalVoucherId=String(body.originalVoucherId??"").trim(),saleDocumentId=String(body.saleDocumentId??"").trim(),date=String(body.date??"").trim(),idempotencyKey=String(body.idempotencyKey??"").trim(),mode=String(body.mode??"") as "credit"|"cash"|"bank";
    if(!businessId||!originalVoucherId||!saleDocumentId||!date||!idempotencyKey)return errorResponse("Business, original voucher, sale document, date and idempotency key are required.");if(!["credit","cash","bank"].includes(mode))return errorResponse("Invalid return settlement mode.");
    const businessRef=db.collection("businesses").doc(businessId);const memberSnap=await businessRef.collection("members").doc(token.uid).get();if(!memberSnap.exists)return errorResponse("You are not a member of this business.",403);const member=memberSnap.data() as {status?:string;role?:string;permissions?:Record<string,unknown>};if(member.status!=="active")return errorResponse("Your business membership is not active.",403);const permissions=(member.permissions?.sales??{}) as Record<string,unknown>;if(!(member.role==="owner"||member.role==="admin"||permissions.create===true))return errorResponse("Permission denied: SALE_RETURN_CREATE.",403);
    const fy=fyFor(date);const [originalSnap,fySnap,accountsSnap,saleSnap]=await Promise.all([businessRef.collection("vouchers").doc(originalVoucherId).get(),businessRef.collection("financialYears").doc(fy.id).get(),businessRef.collection("accounts").get(),businessRef.collection("sales").doc(saleDocumentId).get()]);
    if(!fySnap.exists)return errorResponse("Financial year is not initialized for this business.");if(!originalSnap.exists)return errorResponse("Original voucher was not found.");const original=originalSnap.data() as Record<string,unknown>;if(String(original.businessId??"")!==businessId||String(original.voucherType??"")!=="SALE"||String(original.status??"")!=="posted")return errorResponse("Only a posted sale from this business can be returned.");if(!saleSnap.exists)return errorResponse("Original sale document was not found.");
    const accounts=accountsSnap.docs.map(d=>({id:d.id,...d.data()} as Account));const byCode=(code:string)=>accounts.find(a=>a.code===code)?.id;const sales=byCode("4000");if(!sales)return errorResponse("Sales account is not configured.");const outputCgst=byCode("2101"),outputSgst=byCode("2102"),outputIgst=byCode("2103"),outputCess=byCode("2104");const lineSnap=await businessRef.collection("voucherLines").where("voucherId","==",originalVoucherId).get();const lines=lineSnap.docs.map(d=>d.data() as VoucherLine);const taxable=lines.filter(l=>l.accountId===sales).reduce((s,l)=>s+l.credit-l.debit,0);const cgst=outputCgst?lines.filter(l=>l.accountId===outputCgst).reduce((s,l)=>s+l.credit-l.debit,0):0;const sgst=outputSgst?lines.filter(l=>l.accountId===outputSgst).reduce((s,l)=>s+l.credit-l.debit,0):0;const igst=outputIgst?lines.filter(l=>l.accountId===outputIgst).reduce((s,l)=>s+l.credit-l.debit,0):0;const cess=outputCess?lines.filter(l=>l.accountId===outputCess).reduce((s,l)=>s+l.credit-l.debit,0):0;const taxRate=taxable>0?Number((((cgst+sgst+igst)/taxable)*100).toFixed(6)):0;const cessRate=taxable>0?Number(((cess/taxable)*100).toFixed(6)):0;const intraState=cgst>0||sgst>0;
    const sale=saleSnap.data() as Record<string,unknown>;const saleItems=Array.isArray(sale.items)?sale.items as Array<Record<string,unknown>>:[];const originalItems=new Map(saleItems.map(item=>[String(item.itemId??""),item]));const requested=Array.isArray(body.items)?body.items as Array<Record<string,unknown>>:[];if(!requested.length)return errorResponse("At least one return item is required.");let returnTaxableRupees=0;const items=requested.map(raw=>{const itemId=String(raw.itemId??"");const quantity=Number(raw.quantity??0);if(!itemId||!Number.isFinite(quantity)||quantity<=0)throw new Error("Return item and quantity must be valid.");const originalItem=originalItems.get(itemId);if(!originalItem)throw new Error(`Item ${itemId} was not found on the original sale.`);const soldQuantity=Number(originalItem.quantity??0),unitPrice=Number(originalItem.price??0);if(!Number.isFinite(soldQuantity)||quantity>soldQuantity)throw new Error(`Return quantity for ${itemId} exceeds the original quantity.`);returnTaxableRupees+=quantity*unitPrice;return{itemId,quantity,warehouseId:typeof raw.warehouseId==="string"&&raw.warehouseId?raw.warehouseId:"MAIN"};});
    if(!(returnTaxableRupees>0))return errorResponse("Return taxable value must be positive.");const taxableValuePaise=assertMoney(Math.round(returnTaxableRupees*100),"Return taxable value");const customerId=typeof body.customerId==="string"&&body.customerId?body.customerId:undefined;const bankAccountId=typeof body.bankAccountId==="string"&&body.bankAccountId?body.bankAccountId:undefined;const repo=createAdminAccountingRepository(businessId);const result=await postSaleReturn(repo,{businessId,financialYearId:fy.id,date,userId:token.uid,partyId:customerId,taxableValue:taxableValuePaise,taxRate,intraState,cessRate,narration:typeof body.narration==="string"?body.narration:undefined,originalVoucherId,idempotencyKey,mode,accountMap:{party:byCode("1200"),cash:byCode("1000"),bank:bankAccountId||byCode("1010"),salesReturn:byCode("4900"),sales,inventory:byCode("1300"),cogs:byCode("5100"),outputCgst,outputSgst,outputIgst,outputCess},items},{ids:{next:prefix=>`${prefix}-${crypto.randomUUID()}`},clock:{now:()=>new Date().toISOString()}});
    return NextResponse.json({success:true,result});
  }catch(error){const message=error instanceof Error?error.message:"Could not post sales return.";const status=/authentication|token|credential/i.test(message)?401:/permission|member/i.test(message)?403:/idempotency|duplicate|conflict/i.test(message)?409:400;return errorResponse(message,status);}
}
