import { NextResponse } from "next/server";
import { Timestamp } from "firebase-admin/firestore";
import { randomUUID } from "node:crypto";
import { getAdminServices } from "@/infrastructure/firebase/admin";
import { createAdminAccountingRepository } from "@/infrastructure/firebase/adminAccountingRepository";
import { postCashBankEntry, postCashBankTransfer } from "@/core/accounting/cashBank";
import { reversePostedVoucher } from "@/core/accounting/voucherReversal";
export const runtime="nodejs";
function fail(message:string,status=400){return NextResponse.json({success:false,error:message},{status});}
async function auth(request:Request){const {auth,db}=getAdminServices();const h=request.headers.get("authorization")||"";if(!h.startsWith("Bearer "))throw Object.assign(new Error("Authentication is required."),{status:401});const token=await auth.verifyIdToken(h.slice(7));return{db,token};}
async function membership(db:any,businessId:string,uid:string){const s=await db.collection("businesses").doc(businessId).collection("members").doc(uid).get();if(!s.exists||s.data()?.status!=="active")throw Object.assign(new Error("You are not an active member of this business."),{status:403});return s.data()||{};}
function allowed(member:any,action:"create"|"edit"){if(member.role==="owner"||member.role==="admin")return true;return member.permissions?.cashBank?.[action]===true;}
function key(body:Record<string,unknown>){const k=String(body.idempotencyKey||"").trim();if(k.length<16||k.length>128)throw new Error("A valid idempotency key is required.");return k;}
const deps=()=>({ids:{next:(prefix:string)=>`${prefix}-${randomUUID()}`},clock:{now:()=>new Date().toISOString()}});
async function currentFy(db:any,businessId:string){const s=await db.collection("businesses").doc(businessId).collection("financialYears").where("locked","==",false).orderBy("startDate","desc").limit(1).get();if(s.empty)throw new Error("No open financial year is configured for this business.");return String(s.docs[0].id);}
export async function GET(request:Request){try{const {db,token}=await auth(request);const u=new URL(request.url),businessId=(u.searchParams.get("businessId")||"").trim();if(!businessId)return fail("Business ID is required.");await membership(db,businessId,token.uid);const ref=db.collection("businesses").doc(businessId),fyId=await currentFy(db,businessId);const [cashSnap,ledgerSnap,accountsSnap]=await Promise.all([ref.collection("bankAccounts").where("status","==","active").get(),ref.collection("ledgerEntries").where("financialYearId","==",fyId).get(),ref.collection("accounts").where("active","==",true).get()]);const cashAccounts=cashSnap.docs.map((d:any)=>({accountId:d.id,...d.data()}));const balance=new Map<string,number>();for(const l of ledgerSnap.docs){const x=l.data() as any;const n=String(x.accountId||"");if(n)balance.set(n,(balance.get(n)||0)+Number(x.debit||0)-Number(x.credit||0));}const enriched=cashAccounts.map((a:any)=>({...a,currentBalance:Number(balance.get(a.ledgerAccountId)||a.openingBalance||0)}));const glAccounts=accountsSnap.docs.map((d:any)=>({accountId:d.id,...d.data()})).sort((a:any,b:any)=>String(a.name).localeCompare(String(b.name)));const ledger=ledgerSnap.docs.map((d:any)=>({lineId:d.id,...d.data()})).sort((a:any,b:any)=>String(b.date).localeCompare(String(a.date))).slice(0,300);return NextResponse.json({success:true,financialYearId:fyId,accounts:enriched,glAccounts,ledger});}catch(e:any){return fail(e?.message||"Unable to load cash and bank data.",e?.status||500)}}
export async function POST(request:Request){try{const {db,token}=await auth(request);const body=await request.json() as Record<string,any>,businessId=String(body.businessId||"").trim();if(!businessId)return fail("Business ID is required.");const member=await membership(db,businessId,token.uid),action=String(body.action||"") as any;if(["entry","transfer","account"].includes(action)&&!allowed(member,"create"))return fail("Cash & Bank create permission denied.",403);if(action==="reverse"&&!allowed(member,"edit"))return fail("Cash & Bank edit permission denied.",403);const financialYearId=String(body.financialYearId||await currentFy(db,businessId)),repo=createAdminAccountingRepository(businessId);
 if(action==="entry"){const accountId=String(body.accountId||""),snap=await db.collection("businesses").doc(businessId).collection("bankAccounts").doc(accountId).get();if(!snap.exists)return fail("Cash/bank account not found.");const a=snap.data() as any;const result=await postCashBankEntry(repo,{businessId,financialYearId,date:String(body.date||""),userId:token.uid,idempotencyKey:key(body),accountId,ledgerAccountId:String(a.ledgerAccountId||""),type:body.type,amount:Number(body.amount),contraAccountId:String(body.contraAccountId||""),narration:String(body.name||"Cash/Bank transaction"),reference:String(body.reference||""),notes:String(body.notes||"")},deps());return NextResponse.json({success:true,result});}
 if(action==="transfer"){const fromId=String(body.fromAccountId||""),toId=String(body.toAccountId||"");const [fs,ts]=await Promise.all([db.collection("businesses").doc(businessId).collection("bankAccounts").doc(fromId).get(),db.collection("businesses").doc(businessId).collection("bankAccounts").doc(toId).get()]);if(!fs.exists||!ts.exists)return fail("Both cash/bank accounts are required.");const f=fs.data() as any,t=ts.data() as any;const result=await postCashBankTransfer(repo,{businessId,financialYearId,date:String(body.date||""),userId:token.uid,idempotencyKey:key(body),fromAccountId:fromId,fromLedgerAccountId:String(f.ledgerAccountId||""),toAccountId:toId,toLedgerAccountId:String(t.ledgerAccountId||""),amount:Number(body.amount),narration:String(body.notes||"Cash/Bank transfer"),reference:String(body.reference||""),notes:String(body.notes||"")},deps());return NextResponse.json({success:true,result});}
 if(action==="account"){const accountId=`${String(body.kind||"bank")}-${randomUUID()}`,ledgerAccountId=`cashbank-${randomUUID()}`,ref=db.collection("businesses").doc(businessId),now=Timestamp.now(),amount=Number(body.openingBalance||0);if(!Number.isSafeInteger(amount)||amount<0)return fail("Opening balance must be a non-negative integer amount.");const name=String(body.displayName||"Cash/Bank Account").trim();if(!name)return fail("Account name is required.");const batch=db.batch();batch.set(ref.collection("accounts").doc(ledgerAccountId),{id:ledgerAccountId,businessId,code:`CB-${Date.now()}`,name,type:"asset",parentId:body.kind==="cash"?"acct-cash":"acct-bank",systemAccount:false,active:true,openingDebit:amount,openingCredit:0,createdAt:now.toDate().toISOString(),updatedAt:now.toDate().toISOString()});batch.set(ref.collection("bankAccounts").doc(accountId),{accountId,displayName:name,kind:body.kind==="cash"?"cash":"bank",ledgerAccountId,openingBalance:amount,openingBalanceDate:String(body.openingBalanceDate||new Date().toISOString().slice(0,10)),printQrOnInvoice:Boolean(body.printQrOnInvoice),printDetailsOnInvoice:Boolean(body.printDetailsOnInvoice),accountNumber:String(body.accountNumber||""),ifscCode:String(body.ifscCode||""),upiId:String(body.upiId||""),bankName:String(body.bankName||""),accountHolderName:String(body.accountHolderName||""),status:"active",createdBy:token.uid,createdAt:now,updatedAt:now});await batch.commit();return NextResponse.json({success:true,accountId,ledgerAccountId});}
 if(action==="reverse"){const result=await reversePostedVoucher(repo,{businessId,financialYearId,voucherId:String(body.voucherId||""),userId:token.uid,idempotencyKey:key(body),date:String(body.date||new Date().toISOString().slice(0,10)),narration:String(body.narration||"Cash/Bank transaction reversal")},deps());return NextResponse.json({success:true,result});}
 return fail("Unknown Cash & Bank action.");}catch(e:any){return fail(e?.message||"Cash & Bank operation failed.",e?.status||400)}}