import { NextResponse } from "next/server";
import { Timestamp } from "firebase-admin/firestore";
import { createHash, randomUUID } from "node:crypto";
import { getAdminServices } from "@/infrastructure/firebase/admin";
import { createAdminAccountingRepository } from "@/infrastructure/firebase/adminAccountingRepository";
import { postCashBankEntry, postCashBankTransfer } from "@/core/accounting/cashBank";
export const runtime="nodejs";
const ROLE={cashBankCreate:true,cashBankEdit:true,cashBankDelete:true};
function fail(message:string,status=400){return NextResponse.json({success:false,error:message},{status});}
async function auth(request:Request){const {auth,db}=getAdminServices();const h=request.headers.get("authorization")||"";if(!h.startsWith("Bearer "))throw Object.assign(new Error("Authentication is required."),{status:401});const token=await auth.verifyIdToken(h.slice(7));return{db,token};}
async function membership(db:any,businessId:string,uid:string){const s=await db.collection("businesses").doc(businessId).collection("members").doc(uid).get();if(!s.exists||s.data()?.status!=="active")throw Object.assign(new Error("You are not an active member of this business."),{status:403});return s.data()||{};}
function key(body:Record<string,unknown>){return String(body.idempotencyKey||randomUUID());}
function ids(){return{next:(prefix:string)=>`${prefix}-${randomUUID()}`};}
function clock(){return{now:()=>new Date().toISOString()};}
export async function GET(request:Request){try{const {db,token}=await auth(request);const u=new URL(request.url),businessId=(u.searchParams.get("businessId")||"").trim();if(!businessId)return fail("Business ID is required.");await membership(db,businessId,token.uid);const ref=db.collection("businesses").doc(businessId);const [accountsSnap,ledgerSnap,vouchersSnap]=await Promise.all([ref.collection("bankAccounts").where("status","==","active").get(),ref.collection("ledgerEntries").get(),ref.collection("vouchers").orderBy("date","desc").limit(100).get()]);const accounts=accountsSnap.docs.map((d:any)=>({accountId:d.id,...d.data()}));const balance=new Map<string,number>();for(const l of ledgerSnap.docs){const x=l.data() as any;const n=(x.accountId||"");if(!n)continue;balance.set(n,(balance.get(n)||0)+Number(x.debit||0)-Number(x.credit||0));}const enriched=accounts.map((a:any)=>({...a,currentBalance:Number(balance.get(a.ledgerAccountId)||0)}));const ledger=ledgerSnap.docs.map((d:any)=>({lineId:d.id,...d.data()})).sort((a:any,b:any)=>String(b.date).localeCompare(String(a.date))).slice(0,300);const vouchers=vouchersSnap.docs.map((d:any)=>({id:d.id,...d.data()}));return NextResponse.json({success:true,accounts:enriched,ledger,vouchers});}catch(e:any){return fail(e?.message||"Unable to load cash and bank data.",e?.status||500)}}
export async function POST(request:Request){try{const {db,token}=await auth(request);const body=await request.json() as Record<string,any>;const businessId=String(body.businessId||"").trim();if(!businessId)return fail("Business ID is required.");const member=await membership(db,businessId,token.uid);const action=String(body.action||"");const permissions=member.permissions||{};if(action==="entry"&&! (permissions.cashBank?.create??ROLE.cashBankCreate))return fail("Cash & Bank create permission denied.",403);if(action==="transfer"&&! (permissions.cashBank?.create??ROLE.cashBankCreate))return fail("Cash & Bank create permission denied.",403);if(action==="account"&&! (permissions.cashBank?.create??ROLE.cashBankCreate))return fail("Cash & Bank create permission denied.",403);
  const repo=createAdminAccountingRepository(businessId), deps={ids:ids(),clock:clock()};
  if(action==="entry"){
    const accountId=String(body.accountId||""),account=await db.collection("businesses").doc(businessId).collection("bankAccounts").doc(accountId).get();if(!account.exists)return fail("Cash/bank account not found.");const a=account.data() as any;const ledgerAccountId=String(a.ledgerAccountId||"");if(!ledgerAccountId)return fail("Cash/bank account is not linked to a ledger account.");const result=await postCashBankEntry(repo,{businessId,financialYearId:String(body.financialYearId||""),date:String(body.date||""),userId:token.uid,idempotencyKey:key(body),accountId,ledgerAccountId,type:body.type,amount:Number(body.amount),contraAccountId:String(body.contraAccountId||""),narration:String(body.name||body.narration||"Cash/Bank transaction"),reference:String(body.reference||""),notes:String(body.notes||"")},deps);return NextResponse.json({success:true,result});
  }
  if(action==="transfer"){
    const fromId=String(body.fromAccountId||""),toId=String(body.toAccountId||"");const [fs,ts]=await Promise.all([db.collection("businesses").doc(businessId).collection("bankAccounts").doc(fromId).get(),db.collection("businesses").doc(businessId).collection("bankAccounts").doc(toId).get()]);if(!fs.exists||!ts.exists)return fail("Both cash/bank accounts are required.");const f=fs.data() as any,t=ts.data() as any;const result=await postCashBankTransfer(repo,{businessId,financialYearId:String(body.financialYearId||""),date:String(body.date||""),userId:token.uid,idempotencyKey:key(body),fromAccountId:fromId,fromLedgerAccountId:String(f.ledgerAccountId||""),toAccountId:toId,toLedgerAccountId:String(t.ledgerAccountId||""),amount:Number(body.amount),narration:String(body.notes||"Cash/Bank transfer"),reference:String(body.reference||""),notes:String(body.notes||"")},deps);return NextResponse.json({success:true,result});
  }
  if(action==="account"){
    const accountId=`${String(body.kind||"bank")}-${randomUUID()}`;const ledgerAccountId=`cashbank-${randomUUID()}`;const batch=db.batch();const ref=db.collection("businesses").doc(businessId);const now=Timestamp.now();const amount=Number(body.openingBalance||0);if(!Number.isSafeInteger(amount)||amount<0)return fail("Opening balance must be a non-negative integer amount.");batch.set(ref.collection("accounts").doc(ledgerAccountId),{id:ledgerAccountId,businessId,code:`CB-${Date.now()}`,name:String(body.displayName||"Cash/Bank Account"),type:"asset",parentId:body.kind==="cash"?"acct-cash":"acct-bank",systemAccount:false,active:true,openingDebit:amount,openingCredit:0,createdAt:now.toDate().toISOString(),updatedAt:now.toDate().toISOString()});batch.set(ref.collection("bankAccounts").doc(accountId),{accountId,displayName:String(body.displayName||"Cash/Bank Account").trim(),kind:body.kind==="cash"?"cash":"bank",ledgerAccountId,openingBalance:amount,openingBalanceDate:String(body.openingBalanceDate||new Date().toISOString().slice(0,10)),printQrOnInvoice:Boolean(body.printQrOnInvoice),printDetailsOnInvoice:Boolean(body.printDetailsOnInvoice),accountNumber:String(body.accountNumber||""),ifscCode:String(body.ifscCode||""),upiId:String(body.upiId||""),bankName:String(body.bankName||""),accountHolderName:String(body.accountHolderName||""),status:"active",createdBy:token.uid,createdAt:now,updatedAt:now});await batch.commit();return NextResponse.json({success:true,accountId,ledgerAccountId});
  }
  return fail("Unknown Cash & Bank action.");
 }catch(e:any){return fail(e?.message||"Cash & Bank operation failed.",e?.status||400)}}
