"use client";

import { useCallback, useEffect, useState } from "react";
import Sidebar from "../Components/Sidebar/page";
import TopNav from "../Components/TopNav/page";
import AuthGate from "../Components/Auth/AuthGate";
import { firebaseAuth } from "../../lib/firebase";
import { useBusiness } from "../../context/BusinessContext";

type Customer={id:string;name?:string};
type Payment={id:string;voucherNumber?:string;date?:string;direction:"in"|"out";amount:number;customerId?:string|null;customerName?:string;method?:string;status?:string;accountName?:string};
const emptyForm={customerId:"",amount:"",direction:"in" as "in"|"out",method:"Cash",bankAccountId:"",note:"",date:new Date().toISOString().slice(0,10)};

async function authHeaders(){if(!firebaseAuth?.currentUser)throw new Error("You must be signed in.");return{Authorization:`Bearer ${await firebaseAuth.currentUser.getIdToken()}`,"Content-Type":"application/json"};}

export default function PaymentsPage(){
 const {activeBusinessId,can}=useBusiness();const canView=can("payments","view"),canCreate=can("payments","create");
 const [customers,setCustomers]=useState<Customer[]>([]);const [payments,setPayments]=useState<Payment[]>([]);const[form,setForm]=useState(emptyForm);const[loading,setLoading]=useState(true);const[saving,setSaving]=useState(false);const[error,setError]=useState("");
 const load=useCallback(async()=>{if(!activeBusinessId||!firebaseAuth?.currentUser){setLoading(false);return;}setLoading(true);try{const response=await fetch(`/api/accounting/payments?businessId=${encodeURIComponent(activeBusinessId)}`,{headers:await authHeaders(),cache:"no-store"});const data=await response.json();if(!response.ok||!data.success)throw new Error(String(data.error??"Could not load payments."));setCustomers(data.data.customers as Customer[]);setPayments(data.data.transactions as Payment[]);setError("");}catch(e){setError(e instanceof Error?e.message:"Could not load payments.");}finally{setLoading(false);}},[activeBusinessId]);
 useEffect(()=>{void load();},[load]);
 function update(field:keyof typeof form){return(event:React.ChangeEvent<HTMLInputElement|HTMLSelectElement>)=>setForm(current=>({...current,[field]:event.target.value}));}
 async function save(event:React.FormEvent){event.preventDefault();if(!activeBusinessId)return setError("Select a business first.");if(!form.customerId)return setError("Select a customer.");const amount=Number(form.amount);if(!Number.isFinite(amount)||amount<=0)return setError("Enter a positive amount.");if(form.method!=="Cash"&&!form.bankAccountId)return setError("Select a bank account for non-cash payment.");setSaving(true);setError("");try{const headers=await authHeaders();const response=await fetch("/api/accounting/payments",{method:"POST",headers,body:JSON.stringify({businessId:activeBusinessId,date:form.date,customerId:form.customerId,direction:form.direction,amountMinor:Math.round(amount*100),method:form.method,bankAccountId:form.bankAccountId||undefined,note:form.note,idempotencyKey:`payment-${crypto.randomUUID()}`})});const data=await response.json();if(!response.ok||!data.success)throw new Error(String(data.error??"Could not save payment."));setForm(emptyForm);await load();}catch(e){setError(e instanceof Error?e.message:"Could not save payment.");}finally{setSaving(false);}}
 if(!canView)return <AuthGate><div className="p-10 text-red-600">You do not have permission to view payments.</div></AuthGate>;
 return <AuthGate><div className="flex min-h-screen bg-[#f7f8fc]"><Sidebar/><main className="min-w-0 flex-1 px-6 pb-8 pt-0 lg:px-10"><TopNav/><div className="mx-auto max-w-[1200px]"><div className="mb-8"><p className="mb-2 text-sm font-medium text-[#465fff]">Accounts receivable</p><h1 className="text-3xl font-bold tracking-tight text-[#1c2940]">Payments</h1><p className="mt-2 text-sm text-[#667085]">Post customer receipts and payments through the Accounting Core.</p></div>{error&&<div role="alert" className="mb-5 rounded-lg border border-[#fecdca] bg-[#fef3f2] px-4 py-3 text-sm text-[#b42318]">{error}</div>}{canCreate&&<section className="mb-6 rounded-xl border border-[#e4e7ec] bg-white p-5 shadow-sm"><h2 className="mb-4 font-semibold text-[#101828]">Record payment</h2><form onSubmit={save} className="grid gap-4 sm:grid-cols-2 lg:grid-cols-6"><label className="text-sm font-medium text-[#344054] lg:col-span-2">Customer<select required value={form.customerId} onChange={update("customerId")} className="mt-1 h-10 w-full rounded-lg border border-[#d0d5dd] bg-white px-3"><option value="">Select customer</option>{customers.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></label><label className="text-sm font-medium text-[#344054]">Date<input required type="date" value={form.date} onChange={update("date")} className="mt-1 h-10 w-full rounded-lg border border-[#d0d5dd] px-3"/></label><label className="text-sm font-medium text-[#344054]">Direction<select value={form.direction} onChange={update("direction")} className="mt-1 h-10 w-full rounded-lg border border-[#d0d5dd] bg-white px-3"><option value="in">Payment in</option><option value="out">Payment out</option></select></label><label className="text-sm font-medium text-[#344054]">Amount<input required min="0.01" step="0.01" type="number" value={form.amount} onChange={update("amount")} className="mt-1 h-10 w-full rounded-lg border border-[#d0d5dd] px-3"/></label><label className="text-sm font-medium text-[#344054]">Method<select value={form.method} onChange={update("method")} className="mt-1 h-10 w-full rounded-lg border border-[#d0d5dd] bg-white px-3"><option>Cash</option><option>UPI</option><option>Card</option><option>Bank transfer</option></select></label><label className="text-sm font-medium text-[#344054] sm:col-span-2 lg:col-span-3">Bank account ID (for non-cash)<input value={form.bankAccountId} onChange={update("bankAccountId")} placeholder="acct-bank or configured bank account" className="mt-1 h-10 w-full rounded-lg border border-[#d0d5dd] px-3"/></label><label className="text-sm font-medium text-[#344054] sm:col-span-2 lg:col-span-2">Note<input value={form.note} onChange={update("note")} className="mt-1 h-10 w-full rounded-lg border border-[#d0d5dd] px-3"/></label><button disabled={saving} type="submit" className="h-10 self-end rounded-lg bg-[#465fff] px-4 text-sm font-semibold text-white disabled:opacity-50">{saving?"Posting…":"Post payment"}</button></form></section>}
 <section className="overflow-hidden rounded-xl border border-[#e4e7ec] bg-white shadow-sm"><div className="border-b border-[#eaecf0] p-5"><h2 className="font-semibold text-[#101828]">Payment history</h2></div><div className="overflow-x-auto"><table className="w-full min-w-[850px] text-left text-sm"><thead className="bg-[#f9fafb] text-xs font-semibold uppercase tracking-wide text-[#667085]"><tr><th className="px-5 py-3">Date</th><th className="px-5 py-3">Voucher</th><th className="px-5 py-3">Customer</th><th className="px-5 py-3">Direction</th><th className="px-5 py-3">Method</th><th className="px-5 py-3">Amount</th><th className="px-5 py-3">Account</th></tr></thead><tbody className="divide-y divide-[#eaecf0]">{loading?<tr><td colSpan={7} className="p-10 text-center">Loading…</td></tr>:payments.map(p=><tr key={p.id}><td className="px-5 py-4">{p.date||"—"}</td><td className="px-5 py-4 font-semibold">{p.voucherNumber||"—"}</td><td className="px-5 py-4">{p.customerName||customers.find(c=>c.id===p.customerId)?.name||"Customer"}</td><td className="px-5 py-4">{p.direction==="out"?"Payment out":"Payment in"}</td><td className="px-5 py-4">{p.method||"—"}</td><td className="px-5 py-4 font-medium">₹{(Number(p.amount||0)/100).toLocaleString("en-IN",{minimumFractionDigits:2})}</td><td className="px-5 py-4">{p.accountName||"—"}</td></tr>)}</tbody></table>{!loading&&!payments.length&&<p className="p-10 text-center text-sm text-[#667085]">No payments recorded.</p>}</div></section></div></main></div></AuthGate>;
}
