import { NextResponse } from "next/server";
import type { Firestore } from "firebase-admin/firestore";
import { getAdminServices } from "@/infrastructure/firebase/admin";
import { findPotentialDuplicates } from "@/core/accounting/partyFeatures";
export const runtime="nodejs";
const fail=(message:string,status=400)=>NextResponse.json({success:false,error:message},{status});
async function ctx(request:Request){const{auth,db}=getAdminServices();const h=request.headers.get("authorization")||"";if(!h.startsWith("Bearer "))throw Object.assign(new Error("Authentication is required."),{statusCode:401});return{db,token:await auth.verifyIdToken(h.slice(7))};}
async function access(db:Firestore,businessId:string,uid:string,write=false){const m=await db.collection("businesses").doc(businessId).collection("members").doc(uid).get();if(!m.exists||m.data()?.status!=="active")throw Object.assign(new Error("Active business membership is required."),{statusCode:403});const d=m.data()||{};const ok=d.role==="owner"||d.role==="admin"||Boolean(d.permissions?.parties?.[write?"delete":"view"]);if(!ok)throw Object.assign(new Error(`Permission denied: PARTY_${write?"ARCHIVE":"VIEW"}.`),{statusCode:403});}
export async function GET(request:Request){try{const{db,token}=await ctx(request);const u=new URL(request.url);const businessId=String(u.searchParams.get("businessId")||"").trim();const partyId=String(u.searchParams.get("partyId")||"").trim();const kind=String(u.searchParams.get("kind")||"customer");if(!businessId||!partyId)return fail("Business ID and party ID are required.");if(kind!=="customer"&&kind!=="supplier")return fail("Party kind must be customer or supplier.");await access(db,businessId,token.uid);const ref=db.collection("businesses").doc(businessId);const target=await ref.collection("parties").doc(partyId).get();if(!target.exists||target.data()?.businessId!==businessId||target.data()?.kind!==kind)return fail("Party not found.",404);const snap=await ref.collection("parties").where("kind","==",kind).get();const t=target.data()||{};const candidates=findPotentialDuplicates({name:String(t.name||""),phone:String(t.phone||""),email:String(t.email||""),gstin:String((t.gst||{}).gstin||"")},snap.docs.filter(d=>d.id!==partyId).map(d=>{const x=d.data();return{id:d.id,name:String(x.name||""),phone:String(x.phone||""),email:String(x.email||""),gstin:String((x.gst||{}).gstin||"")};}));return NextResponse.json({success:true,candidates});}catch(e){return fail(e instanceof Error?e.message:"Could not detect duplicates.",(e as{statusCode?:number}).statusCode||500);}}
export async function POST(request:Request){try{const{db,token}=await ctx(request);const body=await request.json() as Record<string,unknown>;const businessId=String(body.businessId||"").trim(),sourceId=String(body.sourcePartyId||"").trim(),targetId=String(body.targetPartyId||"").trim();if(!businessId||!sourceId||!targetId)return fail("Business ID, source party and target party are required.");if(sourceId===targetId)return fail("Source and target party must be different.");await access(db,businessId,token.uid,true);const ref=db.collection("businesses").doc(businessId);const[source,target]=await Promise.all([ref.collection("parties").doc(sourceId).get(),ref.collection("parties").doc(targetId).get()]);if(!source.exists||!target.exists)return fail("Both parties must exist.",404);const s=source.data()||{},t=target.data()||{};if(s.businessId!==businessId||t.businessId!==businessId||s.kind!==t.kind)return fail("Parties must belong to the same business and party type.");if(s.mergedIntoPartyId)return fail("Source party is already merged.");if(t.mergedIntoPartyId)return fail("Target party must be an active master.");const now=new Date().toISOString();await ref.collection("parties").doc(sourceId).update({status:"inactive",mergedIntoPartyId:targetId,updatedAt:now,mergedAt:now,mergedBy:token.uid});const auditId=`merge-${crypto.randomUUID()}`;await ref.collection("auditLogs").doc(auditId).set({id:auditId,businessId,entityType:"party",entityId:sourceId,action:"PARTY_MERGED",userId:token.uid,timestamp:now,before:s,after:{...s,status:"inactive",mergedIntoPartyId:targetId},metadata:{targetPartyId:targetId,accountingHistoryPreserved:true}});return NextResponse.json({success:true,sourcePartyId:sourceId,targetPartyId:targetId,status:"inactive",message:"Party merged safely. Historical accounting records were not rewritten."});}catch(e){return fail(e instanceof Error?e.message:"Could not merge parties.",(e as{statusCode?:number}).statusCode||500);}}
