export type NavigationItem={label:string;href:string;icon?:string;description?:string;children?:NavigationItem[]};
export const navigation:NavigationItem[]=[
{label:"Dashboard",href:"/",icon:"dashboard"},
{label:"Parties",href:"/customers",icon:"parties",children:[{label:"Customers",href:"/customers"},{label:"Suppliers",href:"/suppliers"},{label:"Customer Ledger",href:"/reports/parties/customer-ledger"},{label:"Supplier Ledger",href:"/reports/parties/supplier-ledger"},{label:"Outstanding",href:"/reports/parties/outstanding"},{label:"Ageing",href:"/reports/parties/ageing"}]},
{label:"Items",href:"/items",icon:"items"},
{label:"Inventory",href:"/inventory",icon:"inventory",children:[{label:"Stock Summary",href:"/inventory"},{label:"Opening Stock",href:"/inventory/opening-stock"},{label:"Stock Adjustment",href:"/inventory/adjustment"},{label:"Stock Transfer",href:"/inventory/transfer"},{label:"Stock Ledger",href:"/inventory/ledger"},{label:"Batch / Expiry",href:"/inventory/batch-expiry"},{label:"Serial Numbers",href:"/inventory/serial-numbers"},{label:"Stock Valuation",href:"/inventory/valuation"},{label:"Manufacturing / BOM",href:"/items/manufacturing"},{label:"Production Planning",href:"/manufacturing/planning"},{label:"Production Entry",href:"/production"},{label:"Production Register",href:"/production/register"},{label:"Manufacturing Reports",href:"/manufacturing/reports"}]},
{label:"Sales",href:"/sales",icon:"sales",children:[{label:"Invoices",href:"/sales"},{label:"Quotations",href:"/quotations"}]},
{label:"Expenses",href:"/expenses",icon:"expenses"},{label:"Cash & Bank",href:"/cash-bank",icon:"cash-bank"},{label:"Payments",href:"/payments",icon:"payments"},
{label:"Reports",href:"/reports/party-wise-statement",icon:"reports",children:[{label:"Party Wise Statement",href:"/reports/party-wise-statement"},{label:"Party Reports",href:"/reports/parties"},{label:"Outstanding",href:"/reports/parties/outstanding"},{label:"Ageing",href:"/reports/parties/ageing"},{label:"All Transactions",href:"/reports/all-transactions"},{label:"Day Book",href:"/reports/day-book"},{label:"Inventory Reports",href:"/reports/inventory"}]},
];
export function isNavigationActive(pathname:string,item:NavigationItem){if(item.href==="/")return pathname==="/";return pathname===item.href||pathname.startsWith(`${item.href}/`);}
