import { NextResponse } from "next/server";
import type { Firestore } from "firebase-admin/firestore";
import { getAdminServices } from "@/infrastructure/firebase/admin";
import { createAdminAccountingRepository } from "@/infrastructure/firebase/adminAccountingRepository";
import { postProduction, cancelProduction } from "@/core/accounting/productionEntry";
import type { AccountingPermission } from "@/core/accounting/authorization";
import type { BusinessMember } from "@/types";

export const runtime="nodejs";
const fail=(message:string,status=400)=>NextResponse.json({success:false,error:message},{status});
const text=(v:unknown)=>String(v??"").trim();
async function auth(request:Request){const{auth,db}=getAdminServices();const h=request.headers.get("authorization")||"";if(!h.startsWith("Bearer "))throw Object.assign(new Error("Authentication is required."),{statusCode:401});return{db,token:await auth.verifyIdToken(h.slice(7))};}
async function member(db:Firestore,businessId:string,uid:string){const s=await db.collection("businesses").doc(businessId).collection("members").doc(uid).get();if(!s.exists)throw Object.assign(new Error("You are not a member of this business."),{statusCode:403});const m=s.data() as BusinessMember;if(m.status!=="active")throw Object.assign(new Error("Your business membership is not active."),{statusCode:403});return m;}
function permissions(m:BusinessMember,action:"create"|"cancel"):AccountingPermission[]{if(m.role==="owner"||m.role==="admin")return action==="create"?["PRODUCTION_CREATE"]:["PRODUCTION_CANCEL"];if(action==="create"&&(m.permissions?.items?.create||m.permissions?.inventory?.create))return["PRODUCTION_CREATE"];if(action==="cancel"&&(m.permissions?.items?.edit||m.permissions?.inventory?.edit))return["PRODUCTION_CANCEL"];return[];}
async function activeFY(db:Firestore,businessId:string){const s=await db.collection("businesses").doc(businessId).collection("financialYears").where("locked","==",false).get();return s.docs.sort((a,b)=>String(b.data()?.startDate||"").localeCompare(String(a.data()?.startDate||"")))[0]||null;}
const deps={ids:{next:(p:string)=>`${p}-${crypto.randomUUID()}`},clock:{now:()=>new Date().toISOString()}};
export async function GET(request:Request){try{const{db,token}=await auth(request);const u=new URL(request.url);const businessId=text(u.searchParams.get("businessId"));if(!businessId)return fail("Business ID is required.");const m=await member(db,businessId,token.uid);if(!permissions(m,"create").length&&!permissions(m,"cancel").length)return fail("Permission denied: production view.",403);const fy=await activeFY(db,businessId);if(!fy)return fail("No active financial year is configured.");const s=await db.collection("businesses").doc(businessId).collection("productionVouchers").where("financialYearId","==",fy.id).limit(200).get();const productions=s.docs.map(d=>({id:d.id,...d.data()})).sort((a:any,b:any)=>String(b.date||"").localeCompare(String(a.date||"")));return NextResponse.json({success:true,financialYearId:fy.id,productions});}catch(e){return fail(e instanceof Error?e.message:"Unable to load production.",(e as{statusCode?:number}).statusCode||400);}}
export async function POST(request:Request){try{const{db,token}=await auth(request);const body=await request.json() as Record<string,unknown>;const businessId=text(body.businessId);const action=text(body.action)||"create";if(!businessId)return fail("Business ID is required.");const m=await member(db,businessId,token.uid);const repo=createAdminAccountingRepository(businessId);if(action==="cancel"){const productionId=text(body.productionId);if(!productionId)return fail("Production ID is required.");const p=permissions(m,"cancel");if(!p.length)return fail("Permission denied: production cancellation.",403);const result=await cancelProduction(repo,{businessId,productionId,userId:token.uid,permissions:p},deps);return NextResponse.json({success:true,result});}if(action!=="create")return fail("Unsupported production action.");const p=permissions(m,"create");if(!p.length)return fail("Permission denied: production entry.",403);const itemId=text(body.itemId),financialYearId=text(body.financialYearId),date=text(body.date)||new Date().toISOString().slice(0,10),idempotencyKey=text(body.idempotencyKey),quantity=Number(body.quantity);if(!itemId||!financialYearId||idempotencyKey.length<16)return fail("Item, financial year and a valid idempotency key are required.");if(!/^\d{4}-\d{2}-\d{2}$/.test(date)||!Number.isFinite(quantity)||quantity<=0)return fail("Valid production date and quantity are required.");const itemSnap=await db.collection("businesses").doc(businessId).collection("items").doc(itemId).get();if(!itemSnap.exists)return fail("Finished item not found.",404);const item=itemSnap.data() as Record<string,unknown>;const config=item.manufacturing as import("@/core/accounting/manufacturing").ManufacturingConfig|undefined;if(!config?.enabled)return fail("Selected item is not configured as a manufactured item.");const result=await postProduction(repo,{businessId,financialYearId,date,userId:token.uid,itemId,quantity,warehouseId:text(body.warehouseId)||undefined,materialInventoryAccountId:text(body.materialInventoryAccountId),finishedGoodsAccountId:text(body.finishedGoodsAccountId)||undefined,wipAccountId:text(body.wipAccountId)||undefined,config,idempotencyKey},deps);return NextResponse.json({success:true,result});}catch(e){const message=e instanceof Error?e.message:"Production operation failed.";const status=(e as{statusCode?:number}).statusCode||(/permission/i.test(message)?403:/not found/i.test(message)?404:/already|duplicate|idempotency/i.test(message)?409:400);return fail(message,status);}}
