"use client";
import { useEffect, useState } from "react";
import Sidebar from "../../Components/Sidebar/page";
import TopNav from "../../Components/TopNav/page";
import AuthGate from "../../Components/Auth/AuthGate";
import { auth } from "../../../lib/firebase";
import { useBusiness } from "../../../context/BusinessContext";

export default function OpeningStockPage(){
 const {activeBusinessId,businessName,loading}=useBusiness(); const [items,setItems]=useState<any[]>([]); const [itemId,setItemId]=useState(""); const [qty,setQty]=useState(""); const [rate,setRate]=useState(""); const [warehouseId,setWarehouseId]=useState(""); const [note,setNote]=useState(""); const [saving,setSaving]=useState(false); const [message,setMessage]=useState("");
 const token=async()=>auth.currentUser?.getIdToken();
 useEffect(()=>{if(loading||!activeBusinessId)return; (async()=>{const t=await token(); if(!t)return; const r=await fetch(`/api/items?businessId=${activeBusinessId}`,{headers:{Authorization:`Bearer ${t}`}}); const b=await r.json(); if(r.ok)setItems(b.items||[])})()},[activeBusinessId,loading]);
 async function submit(e:React.FormEvent){e.preventDefault();setMessage(""); if(!itemId||Number(qty)<=0||Number(rate)<0){setMessage("Select an item and enter valid quantity and rate.");return} setSaving(true);try{const t=await token();if(!t)throw Error("Please sign in again.");const r=await fetch("/api/inventory",{method:"POST",headers:{"Content-Type":"application/json",Authorization:`Bearer ${t}`},body:JSON.stringify({businessId:activeBusinessId,operation:"opening",itemId,quantity:Number(qty),unitCost:Number(rate)*100,warehouseId:warehouseId||undefined,note:note||undefined})});const b=await r.json();if(!r.ok)throw Error(b.error||"Unable to post opening stock");setMessage("Opening stock posted successfully.");setQty("");setRate("");setNote("")}catch(e){setMessage(e instanceof Error?e.message:"Unable to post opening stock")}finally{setSaving(false)}}
 return <AuthGate><div className="flex min-h-screen bg-slate-50"><Sidebar/><main className="min-w-0 flex-1 px-4 pb-10 sm:px-8"><TopNav/><div className="mx-auto max-w-4xl py-8"><p className="text-sm font-semibold text-indigo-600">{businessName||"Business"} · Inventory</p><h1 className="mt-1 text-3xl font-bold text-slate-900">Opening Stock</h1><p className="mt-2 text-sm text-slate-500">Enter initial stock through the accounting inventory engine. Opening stock creates a ledger movement and valuation layer.</p>{message&&<div className="mt-5 rounded-xl border bg-white p-4 text-sm">{message}</div>}<form onSubmit={submit} className="mt-6 rounded-2xl border bg-white p-6 shadow-sm"><div className="grid gap-5 md:grid-cols-2"><label className="text-sm font-medium">Item<select value={itemId} onChange={e=>setItemId(e.target.value)} className="mt-1 h-11 w-full rounded-xl border px-3" required><option value="">Select item</option>{items.map(i=><option key={i.id} value={i.id}>{i.name} · {i.code}</option>)}</select></label><label className="text-sm font-medium">Warehouse ID <input value={warehouseId} onChange={e=>setWarehouseId(e.target.value)} placeholder="Optional" className="mt-1 h-11 w-full rounded-xl border px-3"/></label><label className="text-sm font-medium">Quantity<input type="number" min="0.000001" step="any" value={qty} onChange={e=>setQty(e.target.value)} className="mt-1 h-11 w-full rounded-xl border px-3" required/></label><label className="text-sm font-medium">Unit cost (₹)<input type="number" min="0" step="0.01" value={rate} onChange={e=>setRate(e.target.value)} className="mt-1 h-11 w-full rounded-xl border px-3" required/></label><label className="text-sm font-medium md:col-span-2">Narration / Note<textarea value={note} onChange={e=>setNote(e.target.value)} className="mt-1 min-h-24 w-full rounded-xl border p-3" placeholder="Opening balance as on financial year start"/></label></div><div className="mt-6 flex justify-end"><button disabled={saving} className="rounded-xl bg-indigo-600 px-6 py-3 font-semibold text-white disabled:opacity-50">{saving?"Posting...":"Post Opening Stock"}</button></div></form></div></main></div></AuthGate>;
}