import { NextResponse } from "next/server";
import { getAdminServices } from "@/infrastructure/firebase/admin";
import type { Firestore } from "firebase-admin/firestore";

export const runtime = "nodejs";
type PartyKind = "customer" | "supplier";
function fail(message:string,status=400){return NextResponse.json({success:false,error:message},{status});}
async function auth(request:Request){const {auth,db}=getAdminServices();const h=request.headers.get("authorization")||"";if(!h.startsWith("Bearer "))throw Object.assign(new Error("Authentication is required."),{statusCode:401});return{db,token:await auth.verifyIdToken(h.slice(7))};}
async function member(db:Firestore,businessId:string,uid:string){const s=await db.collection("businesses").doc(businessId).collection("members").doc(uid).get();if(!s.exists||s.data()?.status!=="active")throw Object.assign(new Error("Active business membership is required."),{statusCode:403});return s.data() as {role?:string;permissions?:Record<string,unknown>};}
function canView(m:{role?:string;permissions?:Record<string,unknown>}){return m.role==="owner"||m.role==="admin"||((m.permissions?.parties||{}) as Record<string,unknown>).view===true;}
function dateOnly(v:unknown){return String(v||"").slice(0,10);}
export async function GET(request:Request){try{const {db,token}=await auth(request);const u=new URL(request.url);const businessId=String(u.searchParams.get("businessId")||"").trim();const partyId=String(u.searchParams.get("partyId")||"").trim();const kind=String(u.searchParams.get("kind")||"") as PartyKind;const from=String(u.searchParams.get("from")||"");const to=String(u.searchParams.get("to")||"");const asOf=String(u.searchParams.get("asOf")||to||new Date().toISOString().slice(0,10));if(!businessId||!partyId)return fail("Business ID and party ID are required.");if(kind!=="customer"&&kind!=="supplier")return fail("Party kind must be customer or supplier.");const m=await member(db,businessId,token.uid);if(!canView(m))return fail("Permission denied: PARTY_VIEW.",403);const ref=db.collection("businesses").doc(businessId);const ps=await ref.collection("parties").doc(partyId).get();if(!ps.exists)return fail("Party not found.",404);const party={id:ps.id,...ps.data()} as Record<string,unknown>&{kind:PartyKind;businessId:string};if(party.businessId!==businessId||party.kind!==kind)return fail("Party business or type mismatch.");const snap=await ref.collection("ledgerEntries").where("partyId","==",partyId).get();const ledger=snap.docs.map(d=>({id:d.id,...d.data()} as Record<string,unknown>)).filter(x=>{const d=dateOnly(x.date);return(!from||d>=from)&&(!to||d<=to)}).sort((a,b)=>`${dateOnly(a.date)}:${String(a.createdAt||"")}`.localeCompare(`${dateOnly(b.date)}:${String(b.createdAt||"")}`));const all=snap.docs.map(d=>d.data() as Record<string,unknown>).filter(x=>dateOnly(x.date)<=asOf);const debit=all.reduce((s,x)=>s+Number(x.debit||0),0);const credit=all.reduce((s,x)=>s+Number(x.credit||0),0);const net=debit-credit;const outstanding=kind==="customer"?Math.max(net,0):Math.max(-net,0);return NextResponse.json({success:true,party,ledger,balance:{debit,credit,net,side:net>0?"debit":net<0?"credit":"zero",outstanding},asOf});}catch(e){const message=e instanceof Error?e.message:"Could not load party ledger.";return fail(message,(e as {statusCode?:number}).statusCode||(/authentication|token/i.test(message)?401:400));}}
