import { describe, expect, it } from "vitest";
import { assertBalanced, validateVoucherLines } from "./ledger";
import { calculateTax, reverseTax } from "./gst";
import { valueFifo, valueWeightedAverage } from "./valuation";
import { allocateAgainstOutstanding } from "./party";
import { savePartyMaster } from "./partyMaster";
import { buildBalanceSheet, buildProfitLoss, buildTrialBalance, reconcileAccounting } from "./reports";
import { postContra, postExpense, postPayment, postPurchase, postReceipt } from "./transactions";
import { postSaleEntry } from "./saleEntry";
import { postSaleReturn, postPurchaseReturn } from "./returns";
import { InMemoryAccountingRepository, fixedClock, testIds } from "./inMemoryRepository";
import { postStockAdjustment, postStockTransfer } from "./stockOperations";
import type { Account, FinancialYear, StockMovement } from "./types";

const account=(id:string,code:string,name:string,type:Account["type"]):Account=>({id,businessId:"b",code,name,type,parentId:null,systemAccount:true,active:true,openingDebit:0,openingCredit:0,createdAt:"2026-04-01T00:00:00.000Z",updatedAt:"2026-04-01T00:00:00.000Z"});
const movement=(overrides:Partial<StockMovement>):StockMovement=>({id:"m",businessId:"b",financialYearId:"fy",date:"2026-04-01",itemId:"i",warehouseId:"default",direction:"in",quantity:10,unitCost:500,value:5000,sourceType:"purchase",sourceId:"p",createdBy:"u",createdAt:"2026-04-01T00:00:00.000Z",...overrides});
const seedRepo=()=>{const repo=new InMemoryAccountingRepository();const fy:FinancialYear={id:"fy",businessId:"b",name:"FY 2026-27",startDate:"2026-04-01",endDate:"2027-03-31",locked:false};repo.financialYears.set(fy.id,fy);for(const a of [account("cash","1000","Cash","asset"),account("bank","1010","Bank","asset"),account("debtors","1200","Sundry Debtors","asset"),account("inventory","1300","Inventory","asset"),account("cgst-in","1401","Input CGST","asset"),account("sgst-in","1402","Input SGST","asset"),account("sales","4000","Sales","income"),account("sales-return","4900","Sales Return","contra_revenue"),account("cogs","5000","COGS","expense"),account("purchases","5100","Purchases","expense"),account("cgst-out","2101","Output CGST","liability"),account("sgst-out","2102","Output SGST","liability"),account("creditors","2000","Sundry Creditors","liability"),account("expense","5200","General Expense","expense"),account("gain","7300","Stock Gain","income"),account("loss","5400","Stock Loss","expense"),account("equity","3000","Capital","equity"),account("acct-opening-balance","3100","Opening Balance Adjustment","equity")])repo.accounts.set(a.id,a);repo.businessDocuments.set("parties/customer-1",{id:"customer-1",businessId:"b",partyCode:"CUS-001",name:"Customer 1",kind:"customer",status:"active",ledgerAccountId:"debtors"});repo.businessDocuments.set("parties/supplier-1",{id:"supplier-1",businessId:"b",partyCode:"SUP-001",name:"Supplier 1",kind:"supplier",status:"active",ledgerAccountId:"creditors"});return repo;};
const base={businessId:"b",financialYearId:"fy",userId:"u",date:"2026-04-02"} as const;const deps={ids:testIds("reg"),clock:fixedClock("2026-04-02T12:00:00.000Z")};const saleAccounts={party:"debtors",sales:"sales",cash:"cash",bank:"bank",outputCgst:"cgst-out",outputSgst:"sgst-out",inventory:"inventory",cogs:"cogs"};const purchaseAccounts={party:"creditors",purchases:"purchases",cash:"cash",bank:"bank",inputCgst:"cgst-in",inputSgst:"sgst-in",inventory:"inventory"};
async function createScenario(){const repo=seedRepo();const purchase=await postPurchase(repo,{...base,date:"2026-04-01",supplierId:"supplier-1",taxableValue:100000,taxRate:18,intraState:true,mode:"credit",accountMap:purchaseAccounts,itemMovements:[{itemId:"i",quantity:10,unitCost:10000}],idempotencyKey:"purchase-1"},deps);const sale=await postSaleEntry(repo,{...base,customerId:"customer-1",grossValue:150000,taxRate:18,intraState:true,paymentMode:"credit",paidAmount:0,accountMap:saleAccounts,itemMovements:[{itemId:"i",quantity:5}],idempotencyKey:"sale-1",documentId:"sale-doc-1"},deps);return{repo,purchase,sale};}

describe("accounting primitives",()=>{
 it("enforces balanced double-entry",()=>{expect(()=>assertBalanced([{debit:1000,credit:0},{debit:0,credit:1000}])).not.toThrow();expect(()=>assertBalanced([{debit:1000,credit:0},{debit:0,credit:900}])).toThrow();});
 it("rejects a line carrying both debit and credit",()=>{expect(()=>validateVoucherLines([{lineId:"1",voucherId:"v",businessId:"b",lineNo:1,accountId:"a",debit:100,credit:50}])).toThrow();});
 it("calculates GST and exact reversal",()=>{const tax=calculateTax({taxableValue:10000,rate:18,intraState:true});expect(tax).toMatchObject({cgst:900,sgst:900,igst:0,cess:0,totalTax:1800,total:11800});expect(reverseTax(tax)).toMatchObject({cgst:-900,sgst:-900,total:-11800});});
 it("allocates receipts oldest-first",()=>{const result=allocateAgainstOutstanding(7000,[{voucherId:"a",voucherNumber:"1",date:"2026-04-01",original:5000,allocated:0,outstanding:5000},{voucherId:"b",voucherNumber:"2",date:"2026-04-02",original:10000,allocated:0,outstanding:10000}]);expect(result.allocations).toEqual([{voucherId:"a",amount:5000},{voucherId:"b",amount:2000}]);expect(result.unallocated).toBe(0);});
 it("keeps FIFO and weighted-average valuation semantics distinct",()=>{const layers=[movement({id:"1",quantity:10,unitCost:500,value:5000}),movement({id:"2",quantity:10,unitCost:600,value:6000}),movement({id:"3",direction:"out",quantity:12,unitCost:0,value:0,sourceType:"sale",sourceId:"s"})];expect(valueFifo(layers)).toEqual({quantity:8,value:4800,unitCost:600});expect(valueWeightedAverage(layers)).toEqual({quantity:8,value:4400,unitCost:550});});
 it("posts a party opening balance into the opening ledger atomically",async()=>{const repo=seedRepo();const party=await savePartyMaster(repo,{ids:testIds("party"),clock:fixedClock("2026-04-01T01:00:00.000Z")},{businessId:"b",partyCode:"CUS-OPEN-001",name:"Opening Customer",kind:"customer",phone:"",email:"",address:{line1:"",city:"Khagaria",state:"Bihar",pincode:"851204",country:"India"},gst:{type:"unregistered"},openingBalance:50000,openingBalanceType:"debit",creditLimit:0,status:"active",ledgerAccountId:"debtors"},"customer","u","fy","party-create-opening-1");expect(party.openingVoucherId).toBeTruthy();const voucher=repo.vouchers.get(party.openingVoucherId!);expect(voucher?.voucherType).toBe("OPENING");expect(voucher?.totalDebit).toBe(50000);expect(voucher?.totalCredit).toBe(50000);});
});

describe("end-to-end accounting flows",()=>{
 it("posts purchase -> sale -> receipt/payment and keeps ledgers balanced",async()=>{const{repo,purchase,sale}=await createScenario();expect(purchase.voucher.voucherType).toBe("PURCHASE");expect(sale.voucher.voucherType).toBe("SALE");const receipt=await postReceipt(repo,{...base,date:"2026-04-03",partyId:"customer-1",amount:50000,mode:"cash",accountMap:saleAccounts},deps);const payment=await postPayment(repo,{...base,date:"2026-04-03",partyId:"supplier-1",amount:25000,mode:"cash",accountMap:purchaseAccounts},deps);const contra=await postContra(repo,{...base,date:"2026-04-03",fromAccountId:"cash",toAccountId:"bank",amount:10000},deps);const expense=await postExpense(repo,{...base,date:"2026-04-03",expenseAccountId:"expense",amount:5000,mode:"cash",accountMap:saleAccounts},deps);for(const result of[receipt,payment,contra,expense])expect(result.voucher.totalDebit).toBe(result.voucher.totalCredit);const entries=[...repo.ledgerEntries.values()];const accounts=[...repo.accounts.values()];expect(buildTrialBalance(accounts,entries).balanced).toBe(true);expect(buildBalanceSheet(accounts,entries).balanced).toBe(true);expect(reconcileAccounting(accounts,entries).balanced).toBe(true);expect(buildProfitLoss(accounts,entries).profit).toBe(95000);});
 it("keeps stock quantity correct after sale return",async()=>{const{repo,sale}=await createScenario();const result=await postSaleReturn(repo,{...base,date:"2026-04-04",partyId:"customer-1",taxableValue:60000,taxRate:18,intraState:true,mode:"credit",originalVoucherId:sale.voucher.id,idempotencyKey:"sale-return-1",accountMap:{...saleAccounts,salesReturn:"sales-return"},items:[{itemId:"i",quantity:2}]},deps);expect(result.voucher.totalDebit).toBe(result.voucher.totalCredit);const stock=[...repo.stockMovements.values()].filter(m=>m.itemId==="i");expect(stock.reduce((sum,m)=>sum+(m.direction==="in"?m.quantity:-m.quantity),0)).toBe(7);});
 it("keeps stock quantity correct after purchase return following a sale",async()=>{const{repo,purchase}=await createScenario();const result=await postPurchaseReturn(repo,{...base,date:"2026-04-04",supplierId:"supplier-1",partyId:"supplier-1",taxableValue:20000,taxRate:18,intraState:true,mode:"credit",originalVoucherId:purchase.voucher.id,idempotencyKey:"purchase-return-1",accountMap:purchaseAccounts,items:[{itemId:"i",quantity:2}]},deps);expect(result.voucher.totalDebit).toBe(result.voucher.totalCredit);const stock=[...repo.stockMovements.values()].filter(m=>m.itemId==="i");expect(stock.reduce((sum,m)=>sum+(m.direction==="in"?m.quantity:-m.quantity),0)).toBe(3);});
 it("handles stock adjustment and warehouse transfer",async()=>{const repo=seedRepo();repo.stockMovements.set("opening",movement({id:"opening",quantity:10,unitCost:1000,value:10000}));const adjustment=await postStockAdjustment(repo,{businessId:"b",financialYearId:"fy",itemId:"i",warehouseId:"default",date:"2026-04-05",quantityDelta:-2,unitCost:1000,sourceId:"adjust-1",createdBy:"u",idempotencyKey:"adjust-1",accountMap:{inventory:"inventory",stockAdjustmentGain:"gain",stockAdjustmentLoss:"loss"}},deps);expect(adjustment.voucher.totalDebit).toBe(adjustment.voucher.totalCredit);const transfer=await postStockTransfer(repo,{businessId:"b",financialYearId:"fy",itemId:"i",fromWarehouseId:"default",toWarehouseId:"w2",quantity:3,unitCost:1000,sourceId:"transfer-1",createdBy:"u",date:"2026-04-05",idempotencyKey:"transfer-1"},deps);expect(transfer.stockMovements).toHaveLength(2);});
});

describe("report and control boundaries",()=>{it("rejects a locked financial year at posting time",async()=>{const repo=seedRepo();repo.financialYears.set("fy",{...repo.financialYears.get("fy")!,locked:true});await expect(postExpense(repo,{...base,expenseAccountId:"expense",amount:1000,mode:"cash",accountMap:saleAccounts},deps)).rejects.toThrow(/locked|financial year/i);});it("rejects report periods that are reversed",()=>{const accounts=[...seedRepo().accounts.values()];expect(()=>buildTrialBalance(accounts,[],{fromDate:"2026-05-01",toDate:"2026-04-01"})).toThrow();expect(()=>buildProfitLoss(accounts,[],{fromDate:"2026-05-01",toDate:"2026-04-01"})).toThrow();});});
