import { describe, expect, it } from "vitest";
import { InMemoryAccountingRepository, fixedClock, testIds } from "./inMemoryRepository";
import { createCashBankAccount, postCashBankEntry, postCashBankTransfer } from "./cashBank";
import { reversePostedVoucher } from "./voucherReversal";

const setup=()=>{const repo=new InMemoryAccountingRepository();const now=fixedClock("2026-09-01T12:00:00.000Z");const ids=testIds("cb");const businessId="biz-1",financialYearId="fy-2026-27";repo.financialYears.set(financialYearId,{id:financialYearId,businessId,name:"FY 2026-27",startDate:"2026-04-01",endDate:"2027-03-31",locked:false});for(const [id,name,type,openingDebit] of [["bank-a","Bank A","asset",100000],["bank-b","Bank B","asset",50000],["cash-a","Cash","asset",25000],["expense","Expense","expense",0]] as const)repo.accounts.set(id,{id,businessId,code:id,name,type,parentId:null,systemAccount:false,active:true,openingDebit,openingCredit:0,createdAt:now.now(),updatedAt:now.now()});repo.businessDocuments.set("bankAccounts/bank-a",{accountId:"bank-a",businessId,displayName:"Bank A",kind:"bank",ledgerAccountId:"bank-a",status:"active",openingBalance:100000});repo.businessDocuments.set("bankAccounts/bank-b",{accountId:"bank-b",businessId,displayName:"Bank B",kind:"bank",ledgerAccountId:"bank-b",status:"active",openingBalance:50000});repo.businessDocuments.set("bankAccounts/cash-a",{accountId:"cash-a",businessId,displayName:"Cash",kind:"cash",ledgerAccountId:"cash-a",status:"active",openingBalance:25000});return{repo,now,ids,businessId,financialYearId};};

const depsFrom=(s:ReturnType<typeof setup>)=>({ids:s.ids,clock:s.now});

describe("cash bank accounting",()=>{
 it("creates a new account with canonical master data",async()=>{const s=setup();const result=await createCashBankAccount(s.repo,{accountId:"bank-c",displayName:"Bank C",ledgerAccountId:"bank-c",kind:"bank",openingBalance:0,openingBalanceDate:"2026-09-01",createdBy:"u1"},depsFrom(s));expect(result).toEqual({accountId:"bank-c",ledgerAccountId:"bank-c"});expect(s.repo.businessDocuments.get("bankAccounts/bank-c")).toMatchObject({displayName:"Bank C",kind:"bank",ledgerAccountId:"bank-c",status:"active"});});
 it("rejects duplicate account creation",async()=>{const s=setup();await expect(createCashBankAccount(s.repo,{accountId:"bank-a",displayName:"Duplicate",ledgerAccountId:"bank-a",kind:"bank",openingBalance:0,openingBalanceDate:"2026-09-01",createdBy:"u1"},depsFrom(s))).rejects.toThrow(/already exists/i);});
 it("posts deposit exactly once for the same idempotency key",async()=>{const s=setup();const input={businessId:s.businessId,financialYearId:s.financialYearId,date:"2026-09-01",userId:"u1",idempotencyKey:"cb-idempotency-123",accountId:"bank-a",ledgerAccountId:"bank-a",type:"deposit" as const,amount:10000,contraAccountId:"expense",narration:"Deposit"};const a=await postCashBankEntry(s.repo,input,depsFrom(s));const b=await postCashBankEntry(s.repo,input,depsFrom(s));expect(a.voucher.id).toBe(b.voucher.id);expect(s.repo.vouchers.size).toBe(1);expect([...s.repo.ledgerEntries.values()].filter(x=>x.voucherId===a.voucher.id)).toHaveLength(2);});
 it("posts withdrawal with the bank credited",async()=>{const s=setup();const result=await postCashBankEntry(s.repo,{businessId:s.businessId,financialYearId:s.financialYearId,date:"2026-09-01",userId:"u1",idempotencyKey:"cb-withdraw-123456",accountId:"bank-a",ledgerAccountId:"bank-a",type:"withdrawal",amount:7000,contraAccountId:"expense",narration:"Withdrawal"},depsFrom(s));const lines=await s.repo.getVoucherLines(result.voucher.id);expect(lines.find(l=>l.accountId==="bank-a")?.credit).toBe(7000);expect(lines.find(l=>l.accountId==="expense")?.debit).toBe(7000);});
 it("posts an atomic contra transfer between cash bank ledgers",async()=>{const s=setup();const result=await postCashBankTransfer(s.repo,{businessId:s.businessId,financialYearId:s.financialYearId,date:"2026-09-01",userId:"u1",idempotencyKey:"cb-transfer-123456",fromAccountId:"bank-a",fromLedgerAccountId:"bank-a",toAccountId:"bank-b",toLedgerAccountId:"bank-b",amount:2500},depsFrom(s));const lines=await s.repo.getVoucherLines(result.voucher.id);expect(lines.find(l=>l.accountId==="bank-a")?.credit).toBe(2500);expect(lines.find(l=>l.accountId==="bank-b")?.debit).toBe(2500);expect(result.voucher.voucherType).toBe("CONTRA");});
 it("preserves account master data after a transfer",async()=>{const s=setup();await postCashBankTransfer(s.repo,{businessId:s.businessId,financialYearId:s.financialYearId,date:"2026-09-01",userId:"u1",idempotencyKey:"cb-transfer-master-1234",fromAccountId:"bank-a",fromLedgerAccountId:"bank-a",toAccountId:"bank-b",toLedgerAccountId:"bank-b",amount:2500},depsFrom(s));expect(s.repo.businessDocuments.get("bankAccounts/bank-a")).toMatchObject({displayName:"Bank A",kind:"bank",ledgerAccountId:"bank-a",status:"active",lastVoucherId:expect.any(String)});expect(s.repo.businessDocuments.get("bankAccounts/bank-b")).toMatchObject({displayName:"Bank B",kind:"bank",ledgerAccountId:"bank-b",status:"active",lastVoucherId:expect.any(String)});});
 it("rejects inactive source or destination",async()=>{const s=setup();s.repo.businessDocuments.set("bankAccounts/bank-b",{...s.repo.businessDocuments.get("bankAccounts/bank-b")!,status:"inactive"});await expect(postCashBankTransfer(s.repo,{businessId:s.businessId,financialYearId:s.financialYearId,date:"2026-09-01",userId:"u1",idempotencyKey:"cb-transfer-inactive",fromAccountId:"bank-a",fromLedgerAccountId:"bank-a",toAccountId:"bank-b",toLedgerAccountId:"bank-b",amount:1000},depsFrom(s))).rejects.toThrow(/active/i);});
 it("rejects ledger/account mismatches and same-account transfers",async()=>{const s=setup();await expect(postCashBankTransfer(s.repo,{businessId:s.businessId,financialYearId:s.financialYearId,date:"2026-09-01",userId:"u1",idempotencyKey:"cb-transfer-mismatch",fromAccountId:"bank-a",fromLedgerAccountId:"wrong-ledger",toAccountId:"bank-b",toLedgerAccountId:"bank-b",amount:1000},depsFrom(s))).rejects.toThrow(/ledger account mismatch/i);await expect(postCashBankTransfer(s.repo,{businessId:s.businessId,financialYearId:s.financialYearId,date:"2026-09-01",userId:"u1",idempotencyKey:"cb-transfer-same-account",fromAccountId:"bank-a",fromLedgerAccountId:"bank-a",toAccountId:"bank-a",toLedgerAccountId:"bank-a",amount:1000},depsFrom(s))).rejects.toThrow(/different/i);});
 it("reverses a cash/bank voucher atomically",async()=>{const s=setup();const posted=await postCashBankEntry(s.repo,{businessId:s.businessId,financialYearId:s.financialYearId,date:"2026-09-01",userId:"u1",idempotencyKey:"cb-reversal-original",accountId:"bank-a",ledgerAccountId:"bank-a",type:"deposit",amount:10000,contraAccountId:"expense",narration:"Deposit"},depsFrom(s));const reversal=await reversePostedVoucher(s.repo,{businessId:s.businessId,financialYearId:s.financialYearId,voucherId:posted.voucher.id,userId:"u2",idempotencyKey:"cb-reversal-123456",date:"2026-09-02"},depsFrom(s));expect(reversal.voucher.voucherType).toBe("RECEIPT_REVERSAL");expect(s.repo.vouchers.get(posted.voucher.id)?.status).toBe("cancelled");const reverseLines=await s.repo.getVoucherLines(reversal.voucher.id);expect(reverseLines.find(l=>l.accountId==="bank-a")?.credit).toBe(10000);expect(reverseLines.find(l=>l.accountId==="expense")?.debit).toBe(10000);});
});
