import { describe, expect, it } from "vitest";
import { InMemoryAccountingRepository, fixedClock, testIds } from "./inMemoryRepository";
import { postCashBankEntry, postCashBankTransfer } from "./cashBank";

const setup=()=>{const repo=new InMemoryAccountingRepository();const now=fixedClock();const ids=testIds("cb");const businessId="biz-1",financialYearId="fy-2026-27";repo.financialYears.set(financialYearId,{id:financialYearId,businessId,name:"FY 2026-27",startDate:"2026-04-01",endDate:"2027-03-31",locked:false});for(const [id,name] of [["bank-a","Bank A"],["bank-b","Bank B"],["expense","Expense"]])repo.accounts.set(id,{id,businessId,code:id,name,type:id.startsWith("bank")?"asset":"expense",parentId:null,systemAccount:false,active:true,openingDebit:0,openingCredit:0,createdAt:now.now(),updatedAt:now.now()});repo.businessDocuments.set("bankAccounts/bank-a",{accountId:"bank-a",businessId,displayName:"Bank A",kind:"bank",ledgerAccountId:"bank-a",status:"active",openingBalance:0});repo.businessDocuments.set("bankAccounts/bank-b",{accountId:"bank-b",businessId,displayName:"Bank B",kind:"bank",ledgerAccountId:"bank-b",status:"active",openingBalance:0});return{repo,now,ids,businessId,financialYearId};};

describe("cash bank accounting",()=>{
 it("posts deposit exactly once for the same idempotency key",async()=>{const s=setup();const input={businessId:s.businessId,financialYearId:s.financialYearId,date:"2026-09-01",userId:"u1",idempotencyKey:"cb-idempotency-123",accountId:"bank-a",ledgerAccountId:"bank-a",type:"deposit" as const,amount:10000,contraAccountId:"expense",narration:"Deposit"};const a=await postCashBankEntry(s.repo,input,{ids:s.ids,clock:s.now});const b=await postCashBankEntry(s.repo,input,{ids:s.ids,clock:s.now});expect(a.voucher.id).toBe(b.voucher.id);expect(s.repo.vouchers.size).toBe(1);});
 it("posts an atomic contra transfer between cash bank ledgers",async()=>{const s=setup();const result=await postCashBankTransfer(s.repo,{businessId:s.businessId,financialYearId:s.financialYearId,date:"2026-09-01",userId:"u1",idempotencyKey:"cb-transfer-123456",fromAccountId:"bank-a",fromLedgerAccountId:"bank-a",toAccountId:"bank-b",toLedgerAccountId:"bank-b",amount:2500}, {ids:s.ids,clock:s.now});const lines=await s.repo.getVoucherLines(result.voucher.id);expect(lines.reduce((n,l)=>n+l.debit,0)).toBe(2500);expect(lines.reduce((n,l)=>n+l.credit,0)).toBe(2500);});
});
