import {describe,expect,it} from "vitest";
import {InMemoryAccountingRepository,fixedClock,testIds} from "./inMemoryRepository";
import {postExpenseEntry} from "./expenseEntry";
import {reversePostedVoucher} from "./voucherReversal";

function setup(){const repo=new InMemoryAccountingRepository();const clock=fixedClock("2026-09-01T12:00:00.000Z");const ids=testIds("expense");const businessId="biz-1",financialYearId="fy-2026-27";repo.financialYears.set(financialYearId,{id:financialYearId,businessId,name:"FY 2026-27",startDate:"2026-04-01",endDate:"2027-03-31",locked:false});for(const [id,type] of [["expense", "expense"],["acct-cash","asset"],["bank-a","asset"]] as const)repo.accounts.set(id,{id,businessId,code:id,name:id,type,parentId:null,systemAccount:true,active:true,openingDebit:0,openingCredit:0,createdAt:clock.now(),updatedAt:clock.now()});return{repo,clock,ids,businessId,financialYearId};}
const deps=(s:ReturnType<typeof setup>)=>({ids:s.ids,clock:s.clock});

describe("expense accounting",()=>{
 it("posts a balanced cash expense and persists minor-unit amount",async()=>{const s=setup();const r=await postExpenseEntry(s.repo,{businessId:s.businessId,financialYearId:s.financialYearId,date:"2026-09-01",userId:"u1",expenseAccountId:"expense",amount:12550,mode:"cash",cashAccountId:"acct-cash",idempotencyKey:"expense-create-123456",documentId:"exp-1",documentPayload:{expenseNumber:"001"}},deps(s));expect(r.voucher.totalDebit).toBe(12550);expect(r.voucher.totalCredit).toBe(12550);expect(s.repo.businessDocuments.get("expenses/exp-1")?.amountMinor).toBe(12550);expect(r.lines.map(x=>[x.accountId,x.debit,x.credit])).toEqual([["expense",12550,0],["acct-cash",0,12550]]);});
 it("is idempotent and does not create a second expense document",async()=>{const s=setup();const input={businessId:s.businessId,financialYearId:s.financialYearId,date:"2026-09-01",userId:"u1",expenseAccountId:"expense",amount:10000,mode:"cash" as const,cashAccountId:"acct-cash",idempotencyKey:"expense-retry-123456",documentId:"exp-1",documentPayload:{expenseNumber:"001"}};const a=await postExpenseEntry(s.repo,input,deps(s));const b=await postExpenseEntry(s.repo,input,deps(s));expect(b.voucher.id).toBe(a.voucher.id);expect([...s.repo.vouchers.values()]).toHaveLength(1);expect([...s.repo.businessDocuments.keys()].filter(k=>k.startsWith("expenses/")).length).toBe(1);});
 it("reverses the posted expense with exact opposite lines",async()=>{const s=setup();const posted=await postExpenseEntry(s.repo,{businessId:s.businessId,financialYearId:s.financialYearId,date:"2026-09-01",userId:"u1",expenseAccountId:"expense",amount:25000,mode:"cash",cashAccountId:"acct-cash",idempotencyKey:"expense-original-123456",documentId:"exp-1"},deps(s));const reversed=await reversePostedVoucher(s.repo,{businessId:s.businessId,financialYearId:s.financialYearId,voucherId:posted.voucher.id,userId:"u2",idempotencyKey:"expense-reversal-123456",date:"2026-09-02"},deps(s));expect(reversed.voucher.status).toBe("posted");expect(s.repo.vouchers.get(posted.voucher.id)?.status).toBe("cancelled");expect(reversed.lines).toHaveLength(2);expect(reversed.lines[0].debit).toBe(0);expect(reversed.lines[0].credit).toBe(25000);expect(reversed.lines[1].debit).toBe(25000);expect(reversed.lines[1].credit).toBe(0);});
});
