import { collection, doc, query, where, runTransaction, type Firestore, type Transaction } from "firebase/firestore";
import type { AccountingRepository, AccountingTransaction, Account, AuditEvent, FinancialYear, LedgerEntry, ReturnDocument, StockMovement, Voucher, VoucherLine } from "./types";
import { ValidationError } from "./errors";
const businessPath=(businessId:string)=>`businesses/${businessId}`; const ref=(db:Firestore,businessId:string,collectionName:string,id:string)=>doc(db,businessPath(businessId),collectionName,id);
function toAccount(data:Record<string,unknown>,id:string):Account{return{id,businessId:String(data.businessId),code:String(data.code??""),name:String(data.name??""),type:data.type as Account["type"],parentId:(data.parentId as string|null|undefined)??null,systemAccount:Boolean(data.systemAccount),active:data.active!==false,openingDebit:Number(data.openingDebit??0),openingCredit:Number(data.openingCredit??0),createdAt:String(data.createdAt??""),updatedAt:String(data.updatedAt??"")};}
class FirestoreAccountingTransaction implements AccountingTransaction{
 constructor(private readonly db:Firestore,private readonly tx:Transaction,private readonly businessId:string){}
 async getFinancialYear(id:string):Promise<FinancialYear|null>{const s=await this.tx.get(ref(this.db,this.businessId,"financialYears",id));return s.exists()?s.data() as FinancialYear:null;}
 async getAccount(id:string):Promise<Account|null>{const s=await this.tx.get(ref(this.db,this.businessId,"accounts",id));return s.exists()?toAccount(s.data() as Record<string,unknown>,s.id):null;}
 async getVoucher(id:string):Promise<Voucher|null>{const s=await this.tx.get(ref(this.db,this.businessId,"vouchers",id));return s.exists()?s.data() as Voucher:null;}
 async getVoucherLines(voucherId:string):Promise<VoucherLine[]>{const s=await this.tx.get(query(collection(this.db,businessPath(this.businessId),"voucherLines"),where("voucherId","==",voucherId)));return s.docs.map(d=>d.data() as VoucherLine).sort((a,b)=>a.lineNo-b.lineNo);}
 async getVouchersByReference(referenceType:string,referenceId:string):Promise<Voucher[]>{const s=await this.tx.get(query(collection(this.db,businessPath(this.businessId),"vouchers"),where("referenceType","==",referenceType),where("referenceId","==",referenceId)));return s.docs.map(d=>d.data() as Voucher).filter(v=>v.status==="posted");}
 async getStockMovementsForSource(sourceId:string):Promise<StockMovement[]>{const s=await this.tx.get(query(collection(this.db,businessPath(this.businessId),"stockMovements"),where("sourceId","==",sourceId)));return s.docs.map(d=>d.data() as StockMovement);}
 async saveVoucher(voucher:Voucher):Promise<void>{this.tx.set(ref(this.db,this.businessId,"vouchers",voucher.id),voucher);}
 async saveVoucherLines(lines:VoucherLine[]):Promise<void>{for(const line of lines)this.tx.set(ref(this.db,this.businessId,"voucherLines",line.lineId),line);}
 async saveLedgerEntries(entries:LedgerEntry[]):Promise<void>{for(const entry of entries)this.tx.set(ref(this.db,this.businessId,"ledgerEntries",entry.lineId),entry);}
 async saveStockMovements(movements:StockMovement[]):Promise<void>{for(const movement of movements)this.tx.set(ref(this.db,this.businessId,"stockMovements",movement.id),movement);}
 async saveReturnDocument(document:ReturnDocument):Promise<void>{if(document.businessId!==this.businessId)throw new ValidationError("Business mismatch while saving return document.");this.tx.set(ref(this.db,this.businessId,"returnDocuments",document.id),document);}
 async saveAuditEvent(event:AuditEvent):Promise<void>{this.tx.set(ref(this.db,this.businessId,"auditLogs",event.id),event);}
 async allocateVoucherNumber(input:{businessId:string;financialYearId:string;voucherType:string;prefix?:string}):Promise<string>{if(input.businessId!==this.businessId)throw new ValidationError("Business mismatch while allocating voucher number.");const sequenceId=`${input.financialYearId}_${input.voucherType}`.replace(/[^a-zA-Z0-9_-]/g,"_");const sequenceRef=ref(this.db,this.businessId,"voucherSequences",sequenceId);const snap=await this.tx.get(sequenceRef);const next=Number(snap.exists()?snap.data().nextNumber??1:1);if(!Number.isSafeInteger(next)||next<1)throw new ValidationError("Invalid voucher sequence state.");const prefix=input.prefix??input.voucherType.toUpperCase();this.tx.set(sequenceRef,{businessId:this.businessId,financialYearId:input.financialYearId,voucherType:input.voucherType,prefix,nextNumber:next+1,updatedAt:new Date().toISOString()},{merge:true});return`${prefix}-${String(next).padStart(6,"0")}`;}
}
export function createFirestoreAccountingRepository(db:Firestore,businessId:string):AccountingRepository{if(!businessId)throw new ValidationError("businessId is required.");return{runInTransaction:<T>(work:(tx:AccountingTransaction)=>Promise<T>)=>runTransaction(db,rawTx=>work(new FirestoreAccountingTransaction(db,rawTx,businessId))) };}
