import type { AccountingRepository, AccountingTransaction, Account, AtomicAccountingDocument, AuditEvent, FinancialYear, LedgerEntry, PartyAllocation, ReturnDocument, StockMovement, Voucher, VoucherLine } from "./types";
import { ValidationError } from "./errors";

export class InMemoryAccountingRepository implements AccountingRepository {
  readonly financialYears=new Map<string,FinancialYear>(); readonly accounts=new Map<string,Account>(); readonly vouchers=new Map<string,Voucher>(); readonly voucherLines=new Map<string,VoucherLine>(); readonly ledgerEntries=new Map<string,LedgerEntry>(); readonly stockMovements=new Map<string,StockMovement>(); readonly partyAllocations=new Map<string,PartyAllocation>(); readonly returnDocuments=new Map<string,ReturnDocument>(); readonly atomicDocuments=new Map<string,AtomicAccountingDocument>(); readonly businessDocuments=new Map<string,Record<string,unknown>>(); readonly auditLogs=new Map<string,AuditEvent>(); private readonly sequences=new Map<string,number>(); private transactionTail:Promise<void>=Promise.resolve();

  async runInTransaction<T>(work:(tx:AccountingTransaction)=>Promise<T>):Promise<T>{
    let release!:()=>void; const previous=this.transactionTail; this.transactionTail=new Promise<void>(resolve=>{release=resolve}); await previous;
    const snapshot={financialYears:new Map(this.financialYears),accounts:new Map(this.accounts),vouchers:new Map(this.vouchers),voucherLines:new Map(this.voucherLines),ledgerEntries:new Map(this.ledgerEntries),stockMovements:new Map(this.stockMovements),partyAllocations:new Map(this.partyAllocations),returnDocuments:new Map(this.returnDocuments),atomicDocuments:new Map(this.atomicDocuments),businessDocuments:new Map([...this.businessDocuments].map(([k,v])=>[k,{...v}])),auditLogs:new Map(this.auditLogs),sequences:new Map(this.sequences)};
    try{return await work(this);}catch(error){this.financialYears.clear();snapshot.financialYears.forEach((v,k)=>this.financialYears.set(k,v));this.accounts.clear();snapshot.accounts.forEach((v,k)=>this.accounts.set(k,v));this.vouchers.clear();snapshot.vouchers.forEach((v,k)=>this.vouchers.set(k,v));this.voucherLines.clear();snapshot.voucherLines.forEach((v,k)=>this.voucherLines.set(k,v));this.ledgerEntries.clear();snapshot.ledgerEntries.forEach((v,k)=>this.ledgerEntries.set(k,v));this.stockMovements.clear();snapshot.stockMovements.forEach((v,k)=>this.stockMovements.set(k,v));this.partyAllocations.clear();snapshot.partyAllocations.forEach((v,k)=>this.partyAllocations.set(k,v));this.returnDocuments.clear();snapshot.returnDocuments.forEach((v,k)=>this.returnDocuments.set(k,v));this.atomicDocuments.clear();snapshot.atomicDocuments.forEach((v,k)=>this.atomicDocuments.set(k,v));this.businessDocuments.clear();snapshot.businessDocuments.forEach((v,k)=>this.businessDocuments.set(k,v));this.auditLogs.clear();snapshot.auditLogs.forEach((v,k)=>this.auditLogs.set(k,v));this.sequences.clear();snapshot.sequences.forEach((v,k)=>this.sequences.set(k,v));throw error;}finally{release();}}
  async getFinancialYear(id:string){return this.financialYears.get(id)??null;} async getAccount(id:string){return this.accounts.get(id)??null;} async getVoucher(id:string){return this.vouchers.get(id)??null;}
  async getVoucherLines(voucherId:string){return[...this.voucherLines.values()].filter(v=>v.voucherId===voucherId).sort((a,b)=>a.lineNo-b.lineNo);}
  async getVouchersByReference(referenceType:string,referenceId:string){return[...this.vouchers.values()].filter(v=>v.referenceType===referenceType&&v.referenceId===referenceId&&v.status==="posted");}
  async getVoucherByIdempotencyKey(businessId:string,financialYearId:string,key:string){return[...this.vouchers.values()].find(v=>v.businessId===businessId&&v.financialYearId===financialYearId&&v.idempotencyKey===key)??null;}
  async getAtomicDocumentByIdempotencyKey(businessId:string,financialYearId:string,key:string){return[...this.atomicDocuments.values()].find(v=>v.businessId===businessId&&v.financialYearId===financialYearId&&v.idempotencyKey===key)??null;}
  async getStockMovementsForSource(sourceId:string){return[...this.stockMovements.values()].filter(m=>m.sourceId===sourceId);}
  async getStockMovementsForItem(itemId:string,warehouseId?:string,throughDate?:string){return[...this.stockMovements.values()].filter(m=>m.itemId===itemId&&(!warehouseId||m.warehouseId===warehouseId)&&(!throughDate||m.date<=throughDate)).sort((a,b)=>`${a.date}:${a.createdAt}:${a.id}`.localeCompare(`${b.date}:${b.createdAt}:${b.id}`));}
  async getPartyAllocationsForVoucher(voucherId:string){return[...this.partyAllocations.values()].filter(a=>a.fromVoucherId===voucherId||a.toVoucherId===voucherId);}
  async getBusinessDocument(collectionName:string,id:string){return this.businessDocuments.get(`${collectionName}/${id}`)??null;}
  async saveAccount(account:Account){if(!account.id||!account.businessId)throw new ValidationError("Account ID and business are required.");this.accounts.set(account.id,account);}
  async saveVoucher(voucher:Voucher){this.vouchers.set(voucher.id,voucher);} async saveVoucherLines(lines:VoucherLine[]){for(const l of lines)this.voucherLines.set(l.lineId,l);} async saveLedgerEntries(entries:LedgerEntry[]){for(const e of entries)this.ledgerEntries.set(e.lineId,e);}
  async saveStockMovements(movements:StockMovement[]){for(const m of movements)this.stockMovements.set(m.id,m);} async savePartyAllocations(allocations:PartyAllocation[]){for(const a of allocations)this.partyAllocations.set(a.id,a);} async saveReturnDocument(document:ReturnDocument){this.returnDocuments.set(document.id,document);} async saveAtomicDocument(document:AtomicAccountingDocument){if(this.atomicDocuments.has(document.id))throw new ValidationError("Atomic document already exists.");this.atomicDocuments.set(document.id,document);} async saveBusinessDocument(collectionName:string,id:string,data:Record<string,unknown>){if(!collectionName||!id)throw new ValidationError("Business document collection and ID are required.");this.businessDocuments.set(`${collectionName}/${id}`,{...(this.businessDocuments.get(`${collectionName}/${id}`)??{}),...data});} async saveAuditEvent(event:AuditEvent){this.auditLogs.set(event.id,event);}
  async allocateVoucherNumber(input:{businessId:string;financialYearId:string;voucherType:string;prefix?:string}){const key=`${input.businessId}:${input.financialYearId}:${input.voucherType}`;const next=this.sequences.get(key)??1;if(!Number.isSafeInteger(next)||next<1)throw new ValidationError("Invalid test sequence.");this.sequences.set(key,next+1);return`${input.prefix??input.voucherType.toUpperCase()}-${String(next).padStart(6,"0")}`;}
}
export const testIds=(prefix="id")=>{let n=0;return{next:(p:string)=>`${p}-${prefix}-${++n}`};}; export const fixedClock=(value="2026-08-30T12:00:00.000Z")=>({now:()=>value});
