import type { Account, LedgerEntry, Money, PartyAllocation, StockMovement, Voucher } from "./types";
import { buildPartyReconciliation } from "./party";
import { balanceFor } from "./stock";
import { reconcileGstLedger, type GstLedgerAccountMap } from "./taxReporting";

export type IntegritySeverity = "PASS" | "WARNING" | "ERROR" | "CRITICAL";
export type IntegrityCategory = "ACCOUNTING"|"PARTY"|"INVENTORY"|"SALES"|"PURCHASE"|"PAYMENTS"|"GST"|"CASH"|"BANK"|"DOCUMENTS"|"REVERSALS"|"SECURITY";
export interface IntegrityFinding { category:IntegrityCategory; entity:string; entityId:string; expected:unknown; actual:unknown; severity:IntegritySeverity; explanation:string; suggestedRemediation:string; }
export interface IntegrityResult { status:IntegritySeverity; checkedAt:string; findings:IntegrityFinding[]; summary:{pass:number;warning:number;error:number;critical:number}; }
export interface IntegritySnapshot {
  businessId:string; financialYearId:string; checkedAt:string; accounts:readonly Account[]; entries:readonly LedgerEntry[]; vouchers:readonly Voucher[];
  stockMovements?:readonly StockMovement[]; allocations?:readonly PartyAllocation[]; documents?:readonly IntegrityDocument[]; gstAccounts?:GstLedgerAccountMap;
  parties?:readonly IntegrityParty[]; payments?:readonly IntegrityPayment[]; cashAccountIds?:readonly string[]; bankAccountIds?:readonly string[];
  cashBookBalances?:readonly IntegrityAccountBalance[]; bankBookBalances?:readonly IntegrityAccountBalance[]; itemIds?:readonly string[];
  authorizedMutations?:readonly IntegrityMutation[];
}
export interface IntegrityDocument { id:string; type:string; businessId:string; financialYearId:string; invoiceNumber?:string; total?:Money; accountingTotal?:Money; partyId?:string; itemIds?:readonly string[]; accountIds?:readonly string[]; voucherId?:string; gst?:Money; }
export interface IntegrityParty { id:string; businessId:string; role:"customer"|"supplier"; status?:string; }
export interface IntegrityPayment { id:string; businessId:string; financialYearId:string; amount:Money; allocated:Money; unallocated:Money; voucherId?:string; }
export interface IntegrityAccountBalance { accountId:string; balance:Money; }
export interface IntegrityMutation { entity:string; entityId:string; businessId:string; authorized:boolean; action:string; }

const rank:Record<IntegritySeverity,number>={PASS:0,WARNING:1,ERROR:2,CRITICAL:3};
const sum=(xs:readonly LedgerEntry[],f:(x:LedgerEntry)=>number)=>xs.reduce((s,x)=>s+f(x),0);
const make=(category:IntegrityCategory,entity:string,entityId:string,expected:unknown,actual:unknown,severity:IntegritySeverity,explanation:string,suggestedRemediation:string):IntegrityFinding=>({category,entity,entityId,expected,actual,severity,explanation,suggestedRemediation});

export function runIntegrityCheck(input:IntegritySnapshot):IntegrityResult {
  const f:IntegrityFinding[]=[];const {businessId,financialYearId}=input;
  const entries=input.entries.filter(e=>e.businessId===businessId&&e.financialYearId===financialYearId);
  const vouchers=input.vouchers.filter(v=>v.businessId===businessId&&v.financialYearId===financialYearId);
  const accounts=input.accounts.filter(a=>a.businessId===businessId);const accountIds=new Set(accounts.map(a=>a.id));
  const partyMap=new Map((input.parties??[]).filter(p=>p.businessId===businessId).map(p=>[p.id,p]));
  const itemIds=new Set(input.itemIds??[]);

  const debit=sum(entries,e=>e.debit),credit=sum(entries,e=>e.credit);
  if(debit!==credit)f.push(make("ACCOUNTING","ledger",`${businessId}:${financialYearId}`,debit,credit,"CRITICAL","Debit and credit totals differ.","Trace affected vouchers and correct only through an authorized accounting reversal/correction workflow."));
  const byVoucher=new Map<string,LedgerEntry[]>();for(const e of entries){const a=byVoucher.get(e.voucherId)??[];a.push(e);byVoucher.set(e.voucherId,a);}
  for(const v of vouchers.filter(v=>v.status!=="cancelled")){const rows=byVoucher.get(v.id)??[];const d=sum(rows,e=>e.debit),c=sum(rows,e=>e.credit);if(d!==v.totalDebit||c!==v.totalCredit)f.push(make("ACCOUNTING","voucher",v.id,{debit:v.totalDebit,credit:v.totalCredit},{debit:d,credit:c},"CRITICAL","Voucher header does not equal its ledger lines.","Reconcile through the canonical transaction service."));}

  const partyIds=new Set(entries.flatMap(e=>e.partyId?[e.partyId]:[]));
  for(const id of partyIds){const p=partyMap.get(id);if(!p){f.push(make("PARTY","party",id,"same-business party",null,"CRITICAL","Ledger contains a missing/cross-business party reference.","Repair the master reference through an authorized workflow."));continue;}const r=buildPartyReconciliation(entries,(input.allocations??[]).filter(a=>a.businessId===businessId),id,p.role);if(!r.reconciled)f.push(make("PARTY","party",id,r.ledgerNet,{billOutstanding:r.billOutstanding,advance:r.advance,allocated:r.allocated},"ERROR","Party outstanding does not reconcile with ledger and allocations.","Reconcile bill-wise allocations through the settlement workflow."));}

  if(input.stockMovements){const ms=input.stockMovements.filter(m=>m.businessId===businessId&&m.financialYearId===financialYearId);for(const itemId of new Set(ms.map(m=>m.itemId))){const rows=ms.filter(m=>m.itemId===itemId);const b=balanceFor(rows,{businessId,financialYearId,itemId});const q=rows.reduce((s,m)=>s+(m.direction==="in"?m.quantity:-m.quantity),0);if(b.quantity!==q)f.push(make("INVENTORY","stock",itemId,q,b.quantity,"CRITICAL","Stock balance differs from stock movements.","Rebuild stock projections from movements; do not edit stock truth directly."));if(input.itemIds&&!itemIds.has(itemId))f.push(make("DOCUMENTS","stock-movement",itemId,"existing item",itemId,"ERROR","Stock movement references an unknown item.","Repair the item reference through the inventory workflow."));}}

  const docs=input.documents??[];for(const d of docs){if(d.businessId!==businessId||d.financialYearId!==financialYearId){f.push(make("SECURITY","document",d.id,`${businessId}:${financialYearId}`,`${d.businessId}:${d.financialYearId}`,"CRITICAL","Document crosses business/financial-year scope.","Block the reference and repair it through an authorized workflow."));continue;}if(d.voucherId){const v=input.vouchers.find(x=>x.id===d.voucherId);if(!v)f.push(make("DOCUMENTS","document",d.id,"existing voucher",null,"ERROR","Document references a missing voucher.","Repair the document-voucher reference through an authorized workflow."));else if(v.businessId!==businessId||v.financialYearId!==financialYearId)f.push(make("SECURITY","document",d.id,`${businessId}:${financialYearId}`,`${v.businessId}:${v.financialYearId}`,"CRITICAL","Document references another business/FY voucher.","Block and repair the cross-scope reference."));else if(d.total!==undefined&&d.total!==v.totalDebit)f.push(make(d.type.toUpperCase().includes("PURCHASE")?"PURCHASE":"SALES","document",d.id,v.totalDebit,d.total,"ERROR","Document total differs from accounting amount.","Reconcile through the canonical posting service."));}if(d.partyId&&!partyMap.has(d.partyId))f.push(make("DOCUMENTS","document",d.id,"valid party",d.partyId,"ERROR","Document has a missing/cross-business party.","Repair the party reference through the party workflow."));for(const itemId of d.itemIds??[])if(input.itemIds&&!itemIds.has(itemId))f.push(make("DOCUMENTS","document",d.id,"existing item",itemId,"ERROR","Document references an unknown item.","Repair the item reference through inventory workflow."));for(const id of d.accountIds??[])if(!accountIds.has(id))f.push(make("DOCUMENTS","document",d.id,"valid account",id,"ERROR","Document references an account outside this business.","Repair account mapping through chart-of-accounts workflow."));}
  const inv=new Map<string,IntegrityDocument[]>();for(const d of docs)if(d.businessId===businessId&&d.financialYearId===financialYearId&&d.invoiceNumber){const k=`${d.type}:${d.invoiceNumber.trim().toLowerCase()}`;const a=inv.get(k)??[];a.push(d);inv.set(k,a);}for(const [k,a] of inv)if(a.length>1)f.push(make("DOCUMENTS","invoice",a[0].id,"unique invoice number",a.map(x=>x.id),"ERROR",`Duplicate invoice number: ${k}.`,"Resolve using the numbering/document correction workflow without deleting posted history."));

  for(const p of input.payments??[])if(p.businessId===businessId&&p.financialYearId===financialYearId&&p.amount!==p.allocated+p.unallocated)f.push(make("PAYMENTS","payment",p.id,p.amount,p.allocated+p.unallocated,"ERROR","Payment amount differs from allocated plus unallocated amount.","Reconcile through the settlement/allocation workflow."));

  if(input.gstAccounts){const gst=reconcileGstLedger(entries,input.gstAccounts);for(const d of docs)if(d.businessId===businessId&&d.financialYearId===financialYearId&&d.gst!==undefined&&d.voucherId){const taxAccounts=new Set(Object.values(input.gstAccounts).filter(Boolean));const actual=sum(entries.filter(e=>e.voucherId===d.voucherId),e=>taxAccounts.has(e.accountId)?Math.abs(e.debit-e.credit):0);if(actual!==d.gst)f.push(make("GST","document",d.id,d.gst,actual,"ERROR","Invoice GST differs from GST ledger lines.","Reconcile through the central GST/accounting posting workflow."));}if(gst.output.total<0||gst.input.total<0)f.push(make("GST","tax-ledger",`${businessId}:${financialYearId},`,">= 0",gst,"ERROR","Configured GST account direction has a negative balance.","Verify mapping and reverse the incorrect transaction through an authorized workflow."));}

  function checkBook(category:IntegrityCategory,ids:readonly string[]|undefined,book:readonly IntegrityAccountBalance[]|undefined){if(!ids||!book)return;const set=new Set(ids);for(const b of book){if(!set.has(b.accountId))continue;const ledger=entries.filter(e=>e.accountId===b.accountId).reduce((s,e)=>s+e.debit-e.credit,0);if(ledger!==b.balance)f.push(make(category,category.toLowerCase(),b.accountId,ledger,b.balance,"CRITICAL",`${category} book differs from accounting ledger balance.`,`Rebuild ${category.toLowerCase()} book from ledger; never edit persisted financial truth directly.`));}}
  checkBook("CASH",input.cashAccountIds,input.cashBookBalances);checkBook("BANK",input.bankAccountIds,input.bankBookBalances);

  for(const v of vouchers){if(v.reversalOfVoucherId){const original=input.vouchers.find(x=>x.id===v.reversalOfVoucherId);if(!original)f.push(make("REVERSALS","voucher",v.id,"existing original",v.reversalOfVoucherId,"CRITICAL","Reversal references a missing original.","Repair through authorized reversal reconciliation."));else if(original.businessId!==businessId||original.financialYearId!==financialYearId)f.push(make("SECURITY","voucher",v.id,`${businessId}:${financialYearId}`,`${original.businessId}:${original.financialYearId}`,"CRITICAL","Reversal crosses business/FY boundaries.","Block and repair the cross-scope reference."));}}
  for(const v of vouchers.filter(v=>v.status==="cancelled")){const rs=vouchers.filter(x=>x.reversalOfVoucherId===v.id);if(rs.length===0)f.push(make("REVERSALS","voucher",v.id,1,0,"CRITICAL","Cancelled transaction has no recorded reversal.","Execute the coordinated cancellation/reversal workflow."));if(rs.length>1)f.push(make("REVERSALS","voucher",v.id,1,rs.length,"CRITICAL","Transaction has multiple reversals.","Freeze further mutation and reconcile duplicate reversals through authorized workflow."));}
  const scopedVoucherIds=new Set(vouchers.map(v=>v.id));for(const e of input.entries)if(scopedVoucherIds.has(e.voucherId)&&e.businessId!==businessId)f.push(make("SECURITY","ledger",e.id,businessId,e.businessId,"CRITICAL","Cross-business ledger reference detected.","Block access and investigate business isolation."));
  for(const m of input.authorizedMutations??[])if(m.businessId===businessId&&!m.authorized)f.push(make("SECURITY",m.entity,m.entityId,true,false,"CRITICAL",`Unauthorized ${m.action} mutation detected.`,"Revoke the mutation path, investigate, and replay only through an authorized workflow."));

  if(!f.length)f.push(make("ACCOUNTING","erp",`${businessId}:${financialYearId}`,"no contradictions",{},"PASS","No contradictions were found in the supplied authoritative snapshot.","No remediation required."));
  const summary={pass:f.filter(x=>x.severity==="PASS").length,warning:f.filter(x=>x.severity==="WARNING").length,error:f.filter(x=>x.severity==="ERROR").length,critical:f.filter(x=>x.severity==="CRITICAL").length};const status=(Object.keys(rank) as IntegritySeverity[]).sort((a,b)=>rank[b]-rank[a]).find(s=>summary[s.toLowerCase() as keyof typeof summary]>0)||"PASS";return{status,checkedAt:input.checkedAt,findings:f,summary};
}
