import type { AccountingRepository } from "./types";
import { ValidationError } from "./errors";

export type MasterItemType = "product" | "service";
export interface ItemMasterInput {
  businessId: string; itemId?: string; name: string; code: string; unit: string; itemType?: MasterItemType;
  categoryId?: string; brand?: string; hsnSac?: string; gstRate?: number;
  salePrice?: number; purchasePrice?: number; mrp?: number; minStock?: number; maxStock?: number; reorderLevel?: number;
  trackStock?: boolean; barcode?: string; status?: "Active" | "Inactive";
}
const text=(v:unknown)=>String(v??"").trim();
const money=(v:unknown,n:string)=>{const x=Number(v??0);if(!Number.isFinite(x)||x<0||!Number.isSafeInteger(x))throw new ValidationError(`${n} must be a non-negative minor-unit amount.`);return x;};
const qty=(v:unknown,n:string)=>{const x=Number(v??0);if(!Number.isFinite(x)||x<0)throw new ValidationError(`${n} must be a non-negative quantity.`);return x;};
export async function createItem(repo:AccountingRepository,input:ItemMasterInput,now:string){
  const name=text(input.name),code=text(input.code),unit=text(input.unit)||"Piece";if(!input.businessId||!name||!code)throw new ValidationError("Business, item name and item code are required.");
  return repo.runInTransaction(async tx=>{const existing=await tx.getBusinessDocument("items",code);if(existing)throw new ValidationError("Item code/SKU already exists.");const itemId=input.itemId||`item-${crypto.randomUUID()}`;const item={businessId:input.businessId,itemId,name,code,unit,itemType:input.itemType||"product",categoryId:text(input.categoryId)||undefined,brand:text(input.brand)||undefined,hsnSac:text(input.hsnSac)||undefined,gstRate:Number(input.gstRate??0),salePrice:money(input.salePrice,"Sale price"),purchasePrice:money(input.purchasePrice,"Purchase price"),mrp:money(input.mrp,"MRP"),minStock:qty(input.minStock,"Minimum stock"),maxStock:qty(input.maxStock,"Maximum stock"),reorderLevel:qty(input.reorderLevel,"Reorder level"),trackStock:input.trackStock!==false,barcode:text(input.barcode)||undefined,status:input.status||"Active",createdAt:now,updatedAt:now};await tx.saveBusinessDocument("items",itemId,item);return {id:itemId,...item};});
}
export async function updateItem(repo:AccountingRepository,input:ItemMasterInput,now:string){if(!input.businessId||!input.itemId)throw new ValidationError("Business and item ID are required.");return repo.runInTransaction(async tx=>{const current=await tx.getBusinessDocument("items",input.itemId!);if(!current)throw new ValidationError("Item not found.");const code=input.code===undefined?String(current.code||""):text(input.code);if(!code)throw new ValidationError("Item code/SKU is required.");if(code!==String(current.code||"")){const byCode=await tx.getBusinessDocument("items",code);if(byCode&&String(byCode.itemId||"")!==input.itemId)throw new ValidationError("Item code/SKU already exists.");}const patch={...current,name:input.name===undefined?current.name:text(input.name),code,unit:input.unit===undefined?current.unit:text(input.unit)||"Piece",itemType:input.itemType??current.itemType,categoryId:input.categoryId===undefined?current.categoryId:text(input.categoryId)||undefined,brand:input.brand===undefined?current.brand:text(input.brand)||undefined,hsnSac:input.hsnSac===undefined?current.hsnSac:text(input.hsnSac)||undefined,gstRate:input.gstRate===undefined?current.gstRate:Number(input.gstRate),salePrice:input.salePrice===undefined?current.salePrice:money(input.salePrice,"Sale price"),purchasePrice:input.purchasePrice===undefined?current.purchasePrice:money(input.purchasePrice,"Purchase price"),mrp:input.mrp===undefined?current.mrp:money(input.mrp,"MRP"),minStock:input.minStock===undefined?current.minStock:qty(input.minStock,"Minimum stock"),maxStock:input.maxStock===undefined?current.maxStock:qty(input.maxStock,"Maximum stock"),reorderLevel:input.reorderLevel===undefined?current.reorderLevel:qty(input.reorderLevel,"Reorder level"),trackStock:input.trackStock??current.trackStock,barcode:input.barcode===undefined?current.barcode:text(input.barcode)||undefined,status:input.status??current.status,updatedAt:now};delete (patch as Record<string,unknown>).stock;delete (patch as Record<string,unknown>).stockValue;await tx.saveBusinessDocument("items",input.itemId,patch);return {id:input.itemId,...patch};});
}
