import { ValidationError } from "./errors";
import type { PartyKind } from "./partyMaster";
import type { Money } from "./types";

export type PartyGroup={id:string;businessId:string;name:string;code:string;parentId?:string;kind?:PartyKind|"both";active:boolean;createdAt:string;updatedAt:string};
export type PartyAddressType="billing"|"shipping"|"registered"|"other";
export type PartyAddress={id:string;label:string;type:PartyAddressType;line1:string;line2?:string;city:string;district?:string;state:string;pincode:string;country:string;gstin?:string;isDefault:boolean};
export type PartyContact={id:string;name:string;designation?:string;phone?:string;email?:string;whatsapp?:string;isPrimary:boolean;active:boolean};
export type PaymentTerms={id:string;name:string;creditDays:number;earlyPaymentDiscountPercent?:number;earlyPaymentDiscountDays?:number;overdueInterestPercentPerMonth?:number;active:boolean};
export type PartyTaxConfiguration={placeOfSupplyState?:string;defaultTaxRate?:number;taxInclusivePricing?:boolean;reverseCharge?:boolean;tdsApplicable?:boolean;tdsSection?:string;tdsRate?:number;tcsApplicable?:boolean;tcsSection?:string;tcsRate?:number};
export type PartyPriceLevel={id:string;name:string;discountPercent?:number;active:boolean};
export type PartyFeatureProfile={groupId?:string;paymentTermsId?:string;priceLevelId?:string;addresses?:PartyAddress[];contacts?:PartyContact[];tax?:PartyTaxConfiguration;notes?:string;tags?:string[]};
export type BillReference={voucherId:string;voucherNumber:string;partyId:string;date:string;dueDate:string;originalAmount:Money;allocatedAmount:Money;kind:"invoice"|"debit_note"|"credit_note"|"opening"};
export type OutstandingBill=BillReference&{invoiceAgeDays:number;ageDays:number;overdueDays:number;bucket:"current"|"1-30"|"31-60"|"61-90"|"91-180"|"181-365"|"365+";outstanding:Money};
export type AgeingSummary={asOfDate:string;current:Money;days1to30:Money;days31to60:Money;days61to90:Money;days91to180:Money;days181to365:Money;days365Plus:Money;total:Money};
const GSTIN=/^[0-9]{2}[A-Z]{5}[0-9]{4}[A-Z][1-9A-Z]Z[0-9A-Z]$/;const PINCODE=/^[1-9][0-9]{5}$/;const EMAIL=/^[^\s@]+@[^\s@]+\.[^\s@]+$/;const PHONE=/^\+?[0-9\s()-]{10,15}$/;
function finitePercent(value:number|undefined,label:string){if(value!==undefined&&(!Number.isFinite(value)||value<0||value>100))throw new ValidationError(`${label} must be between 0 and 100%.`)}
export function validatePaymentTerms(input:PaymentTerms):PaymentTerms{if(!input.name.trim())throw new ValidationError("Payment terms name is required.");if(!Number.isInteger(input.creditDays)||input.creditDays<0||input.creditDays>3650)throw new ValidationError("Credit days must be an integer between 0 and 3650.");finitePercent(input.earlyPaymentDiscountPercent,"Early-payment discount");if(input.earlyPaymentDiscountDays!==undefined&&(!Number.isInteger(input.earlyPaymentDiscountDays)||input.earlyPaymentDiscountDays<0||input.earlyPaymentDiscountDays>input.creditDays))throw new ValidationError("Early-payment discount days must not exceed credit days.");finitePercent(input.overdueInterestPercentPerMonth,"Overdue interest rate");return{...input,name:input.name.trim()}}
export function validatePartyFeatureProfile(input:PartyFeatureProfile):PartyFeatureProfile{const addresses=input.addresses??[];if(addresses.length>50)throw new ValidationError("A party can have at most 50 addresses.");const contacts=input.contacts??[];if(contacts.length>50)throw new ValidationError("A party can have at most 50 contacts.");if(addresses.length&&!addresses.some(a=>a.isDefault))throw new ValidationError("At least one party address must be the default address.");if(addresses.filter(a=>a.isDefault).length>1)throw new ValidationError("Only one party address can be the default address.");if(contacts.filter(c=>c.isPrimary).length>1)throw new ValidationError("Only one party contact can be primary.");if((input.tags??[]).length>50||new Set((input.tags??[]).map(t=>t.trim().toLowerCase())).size!==(input.tags??[]).length)throw new ValidationError("Party tags must be unique and limited to 50.");for(const address of addresses){if(!address.label.trim())throw new ValidationError("Address label is required.");if(!address.city.trim()||!address.state.trim())throw new ValidationError("Address city and state are required.");if(!PINCODE.test(address.pincode.trim()))throw new ValidationError("Address pincode must be a valid Indian pincode.");if(address.gstin&&!GSTIN.test(address.gstin.trim().toUpperCase()))throw new ValidationError("Enter a valid GSTIN for the address.")}for(const contact of contacts){if(!contact.name.trim())throw new ValidationError("Contact name is required.");if(contact.phone&&!PHONE.test(contact.phone.trim()))throw new ValidationError("Enter a valid contact phone number.");if(contact.whatsapp&&!PHONE.test(contact.whatsapp.trim()))throw new ValidationError("Enter a valid WhatsApp number.");if(contact.email&&!EMAIL.test(contact.email.trim()))throw new ValidationError("Enter a valid contact email.")}const tax=input.tax;finitePercent(tax?.defaultTaxRate,"Default tax rate");finitePercent(tax?.tdsRate,"TDS rate");finitePercent(tax?.tcsRate,"TCS rate");if(tax?.tdsApplicable&&!tax.tdsSection?.trim())throw new ValidationError("TDS section is required when TDS is enabled.");if(tax?.tcsApplicable&&!tax.tcsSection?.trim())throw new ValidationError("TCS section is required when TCS is enabled.");if(input.notes&&input.notes.length>5000)throw new ValidationError("Party notes cannot exceed 5000 characters.");return input}
function utcDate(value:string):Date{if(!/^\d{4}-\d{2}-\d{2}$/.test(value))throw new ValidationError(`Invalid date: ${value}`);const date=new Date(`${value}T00:00:00Z`);if(Number.isNaN(date.getTime()))throw new ValidationError(`Invalid date: ${value}`);return date}
export function addCreditDays(invoiceDate:string,creditDays:number):string{if(!Number.isInteger(creditDays)||creditDays<0)throw new ValidationError("Credit days must be a non-negative integer.");const date=utcDate(invoiceDate);date.setUTCDate(date.getUTCDate()+creditDays);return date.toISOString().slice(0,10)}
export function daysBetween(from:string,to:string):number{return Math.max(0,Math.floor((utcDate(to).getTime()-utcDate(from).getTime())/86400000))}
export function ageingBucket(ageDays:number):OutstandingBill["bucket"]{if(ageDays<=0)return"current";if(ageDays<=30)return"1-30";if(ageDays<=60)return"31-60";if(ageDays<=90)return"61-90";if(ageDays<=180)return"91-180";if(ageDays<=365)return"181-365";return"365+"}
export function calculateBillWiseOutstanding(bills:BillReference[],asOfDate:string):OutstandingBill[]{utcDate(asOfDate);return bills.filter(b=>b.date<=asOfDate).map(bill=>{utcDate(bill.date);utcDate(bill.dueDate);if(!Number.isSafeInteger(bill.originalAmount)||bill.originalAmount<0)throw new ValidationError("Bill amount must be a non-negative minor-unit integer.");if(!Number.isSafeInteger(bill.allocatedAmount)||bill.allocatedAmount<0||bill.allocatedAmount>bill.originalAmount)throw new ValidationError(`Invalid allocation for voucher ${bill.voucherNumber}.`);const outstanding=bill.originalAmount-bill.allocatedAmount;const invoiceAgeDays=daysBetween(bill.date,asOfDate);const overdueDays=daysBetween(bill.dueDate,asOfDate);return{...bill,outstanding,invoiceAgeDays,ageDays:overdueDays,overdueDays,bucket:ageingBucket(overdueDays)}}).filter(bill=>bill.outstanding>0)}
export function summarizeAgeing(bills:OutstandingBill[],asOfDate:string):AgeingSummary{const summary:AgeingSummary={asOfDate,current:0,days1to30:0,days31to60:0,days61to90:0,days91to180:0,days181to365:0,days365Plus:0,total:0};for(const bill of bills){summary.total+=bill.outstanding;if(bill.bucket==="current")summary.current+=bill.outstanding;else if(bill.bucket==="1-30")summary.days1to30+=bill.outstanding;else if(bill.bucket==="31-60")summary.days31to60+=bill.outstanding;else if(bill.bucket==="61-90")summary.days61to90+=bill.outstanding;else if(bill.bucket==="91-180")summary.days91to180+=bill.outstanding;else if(bill.bucket==="181-365")summary.days181to365+=bill.outstanding;else summary.days365Plus+=bill.outstanding}return summary}
export type PartyDuplicateCandidate={partyId:string;name:string;phone?:string;email?:string;gstin?:string;score:number;reasons:string[]};
export function findPotentialDuplicates(target:{name:string;phone?:string;email?:string;gstin?:string},parties:Array<{id:string;name:string;phone?:string;email?:string;gstin?:string}>):PartyDuplicateCandidate[]{const normalize=(value?:string)=>(value??"").trim().toLowerCase().replace(/\s+/g," ");const targetName=normalize(target.name),targetPhone=normalize(target.phone),targetEmail=normalize(target.email),targetGstin=normalize(target.gstin);return parties.filter(p=>p.id).map(p=>{const reasons:string[]=[];let score=0;if(targetGstin&&targetGstin===normalize(p.gstin)){score+=100;reasons.push("same GSTIN")}if(targetPhone&&targetPhone===normalize(p.phone)){score+=70;reasons.push("same phone")}if(targetEmail&&targetEmail===normalize(p.email)){score+=60;reasons.push("same email")}if(targetName&&targetName===normalize(p.name)){score+=40;reasons.push("same name")}return{partyId:p.id,name:p.name,phone:p.phone,email:p.email,gstin:p.gstin,score,reasons}}).filter(p=>p.score>=40).sort((a,b)=>b.score-a.score)}
export type PartyImportRow={name:string;phone?:string;email?:string;gstin?:string;state?:string;city?:string;pincode?:string;creditLimit?:string;creditDays?:string;groupCode?:string};
export function validatePartyImportRow(row:PartyImportRow,rowNumber:number):PartyImportRow{if(!Number.isInteger(rowNumber)||rowNumber<1)throw new ValidationError("Import row number must be positive.");if(!row.name?.trim())throw new ValidationError(`Import row ${rowNumber}: party name is required.`);if(row.phone&&!PHONE.test(row.phone.trim()))throw new ValidationError(`Import row ${rowNumber}: invalid phone.`);if(row.email&&!EMAIL.test(row.email.trim()))throw new ValidationError(`Import row ${rowNumber}: invalid email.`);if(row.gstin&&!GSTIN.test(row.gstin.trim().toUpperCase()))throw new ValidationError(`Import row ${rowNumber}: invalid GSTIN.`);if(row.pincode&&!PINCODE.test(row.pincode.trim()))throw new ValidationError(`Import row ${rowNumber}: invalid pincode.`);if(row.creditLimit!==undefined&&(!/^\d+(\.\d{1,2})?$/.test(row.creditLimit.trim())||!Number.isFinite(Number(row.creditLimit))||Number(row.creditLimit)<0))throw new ValidationError(`Import row ${rowNumber}: invalid credit limit.`);if(row.creditDays!==undefined&&(!/^\d+$/.test(row.creditDays.trim())||Number(row.creditDays)>3650))throw new ValidationError(`Import row ${rowNumber}: invalid credit days.`);return row}
