import type { Account, LedgerEntry, Money } from "./types";
import { accountNormalBalance, calculateAccountBalance } from "./ledger";
import { ValidationError } from "./errors";
export interface ReportPeriod{fromDate?:string;toDate?:string;}
export interface TrialBalanceRow{accountId:string;code:string;name:string;debit:Money;credit:Money;balance:Money;}
export interface TrialBalance{rows:TrialBalanceRow[];totalDebit:Money;totalCredit:Money;difference:Money;balanced:boolean;}
export interface ProfitLoss{income:Money;expense:Money;profit:Money;}
export interface BalanceSheet{assets:Money;liabilities:Money;equity:Money;currentProfit:Money;totalLiabilitiesAndEquity:Money;difference:Money;balanced:boolean;}
export interface PartyStatementLine{date:string;voucherType:string;voucherNumber:string;description?:string;debit:Money;credit:Money;runningBalance:Money;voucherId:string;}
function validatePeriod(p:ReportPeriod){if(p.fromDate&&p.toDate&&p.fromDate>p.toDate)throw new ValidationError("Report fromDate cannot be after toDate.");}
function inPeriod(e:LedgerEntry,p:ReportPeriod){return(!p.fromDate||e.date>=p.fromDate)&&(!p.toDate||e.date<=p.toDate);}
function entriesFor(entries:readonly LedgerEntry[],accountId:string){return entries.filter(e=>e.accountId===accountId);}
export function buildTrialBalance(accounts:readonly Account[],entries:readonly LedgerEntry[],period:ReportPeriod={}):TrialBalance{validatePeriod(period);const rows=accounts.filter(a=>a.active).map(a=>{const own=entriesFor(entries,a.id).filter(e=>!period.toDate||e.date<=period.toDate);const debit=a.openingDebit+own.filter(e=>!period.fromDate||e.date>=period.fromDate).reduce((s,e)=>s+e.debit,0)+(period.fromDate?own.filter(e=>e.date<period.fromDate).reduce((s,e)=>s+e.debit,0):0);const credit=a.openingCredit+own.filter(e=>!period.fromDate||e.date>=period.fromDate).reduce((s,e)=>s+e.credit,0)+(period.fromDate?own.filter(e=>e.date<period.fromDate).reduce((s,e)=>s+e.credit,0):0);const balance=accountNormalBalance(a.type)==="debit"?debit-credit:credit-debit;return{accountId:a.id,code:a.code,name:a.name,debit:Math.max(balance,0),credit:Math.max(-balance,0),balance};});const totalDebit=rows.reduce((s,r)=>s+r.debit,0),totalCredit=rows.reduce((s,r)=>s+r.credit,0),difference=totalDebit-totalCredit;return{rows,totalDebit,totalCredit,difference,balanced:difference===0};}
export function buildProfitLoss(accounts:readonly Account[],entries:readonly LedgerEntry[],period:ReportPeriod={}):ProfitLoss{validatePeriod(period);const own=entries.filter(e=>inPeriod(e,period));let income=0,expense=0;for(const a of accounts){if(a.type!=="income"&&a.type!=="expense")continue;const es=entriesFor(own,a.id);const debit=es.reduce((s,e)=>s+e.debit,0),credit=es.reduce((s,e)=>s+e.credit,0),balance=accountNormalBalance(a.type)==="debit"?debit-credit:credit-debit;if(a.type==="income")income+=balance;else expense+=balance;}return{income,expense,profit:income-expense};}
export function buildBalanceSheet(accounts:readonly Account[],entries:readonly LedgerEntry[],period:ReportPeriod={}):BalanceSheet{validatePeriod(period);const through=entries.filter(e=>!period.toDate||e.date<=period.toDate);let assets=0,liabilities=0,equity=0;for(const a of accounts){const balance=calculateAccountBalance(a,entriesFor(through,a.id));if(a.type==="asset")assets+=balance;else if(a.type==="liability")liabilities+=balance;else if(a.type==="equity")equity+=balance;}const currentProfit=buildProfitLoss(accounts,entries,{fromDate:period.fromDate,toDate:period.toDate}).profit;const totalLiabilitiesAndEquity=liabilities+equity+currentProfit,difference=assets-totalLiabilitiesAndEquity;return{assets,liabilities,equity,currentProfit,totalLiabilitiesAndEquity,difference,balanced:difference===0};}
export interface Reconciliation{trialBalanceDifference:Money;balanceSheetDifference:Money;profit:Money;balanced:boolean;}
export function reconcileAccounting(accounts:readonly Account[],entries:readonly LedgerEntry[],period:ReportPeriod={}):Reconciliation{const tb=buildTrialBalance(accounts,entries,period),pl=buildProfitLoss(accounts,entries,period),bs=buildBalanceSheet(accounts,entries,period);return{trialBalanceDifference:tb.difference,balanceSheetDifference:bs.difference,profit:pl.profit,balanced:tb.balanced&&bs.balanced};}
export function buildPartyStatement(entries:readonly LedgerEntry[],partyId:string,fromDate:string,toDate:string):{opening:Money;lines:PartyStatementLine[];closing:Money}{if(fromDate>toDate)throw new ValidationError("Party statement fromDate cannot be after toDate.");const es=entries.filter(e=>e.partyId===partyId).sort((a,b)=>`${a.date}:${a.lineNo}:${a.voucherId}`.localeCompare(`${b.date}:${b.lineNo}:${b.voucherId}`));const opening=es.filter(e=>e.date<fromDate).reduce((s,e)=>s+e.debit-e.credit,0);let running=opening;const lines=es.filter(e=>e.date>=fromDate&&e.date<=toDate).map(e=>{running+=e.debit-e.credit;return{date:e.date,voucherType:e.voucherType,voucherNumber:e.voucherNumber,description:e.description,debit:e.debit,credit:e.credit,runningBalance:running,voucherId:e.voucherId};});return{opening,lines,closing:running};}
