import type { AccountingRepository, Money, PostingResult, VoucherLineInput, StockMovement } from "./types";
import { createStockMovement } from "./inventory";
import { calculateTax } from "./gst";
import { postVoucher } from "./voucher";
import { ValidationError } from "./errors";

export interface ReturnDeps { ids: { next(prefix: string): string }; clock: { now(): string } }
export interface ReturnItem { itemId: string; quantity: number; unitCost: Money; warehouseId?: string; }
export interface ReturnBase { businessId: string; financialYearId: string; date: string; userId: string; partyId: string; taxableValue: Money; taxRate: number; intraState: boolean; cessRate?: number; narration?: string; }
export interface ReturnAccounts { party: string; sales?: string; purchases?: string; cash?: string; bank?: string; inputCgst?: string; inputSgst?: string; inputIgst?: string; inputCess?: string; outputCgst?: string; outputSgst?: string; outputIgst?: string; outputCess?: string; }
const req=(v:string|undefined,n:string)=>{if(!v)throw new ValidationError(`Missing ${n} account.`);return v;};
const dr=(accountId:string,amount:Money,partyId?:string):VoucherLineInput=>({accountId,debit:amount,credit:0,partyId});
const cr=(accountId:string,amount:Money,partyId?:string):VoucherLineInput=>({accountId,debit:0,credit:amount,partyId});
function validateItems(items: readonly ReturnItem[]|undefined){if(!items?.length)throw new ValidationError("At least one return item is required.");for(const m of items){if(!m.itemId||!Number.isFinite(m.quantity)||m.quantity<=0)throw new ValidationError("Return item quantity must be greater than zero.");if(!Number.isSafeInteger(m.unitCost)||m.unitCost<0)throw new ValidationError("Return item cost must be a non-negative integer minor-unit amount.");}}
function validateValue(items:readonly ReturnItem[],taxableValue:Money){const value=items.reduce((s,m)=>s+m.quantity*m.unitCost,0);if(!Number.isSafeInteger(Math.round(value)))throw new ValidationError("Return stock value exceeds safe range.");if(Math.round(value)!==taxableValue)throw new ValidationError("Return taxable value must equal the value of returned stock lines.");}
function taxLines(t:ReturnBase, tax:any, a:ReturnAccounts, sale:boolean){const out:VoucherLineInput[]=[];if(tax.cgst)out.push(sale?dr(req(a.outputCgst,"output CGST"),tax.cgst):cr(req(a.inputCgst,"input CGST"),tax.cgst));if(tax.sgst)out.push(sale?dr(req(a.outputSgst,"output SGST"),tax.sgst):cr(req(a.inputSgst,"input SGST"),tax.sgst));if(tax.igst)out.push(sale?dr(req(a.outputIgst,"output IGST"),tax.igst):cr(req(a.inputIgst,"input IGST"),tax.igst));if(tax.cess)out.push(sale?dr(req(a.outputCess,"output cess"),tax.cess):cr(req(a.inputCess,"input cess"),tax.cess));return out;}
async function postReturn(repo:AccountingRepository,input:ReturnBase&{accountMap:ReturnAccounts;items:ReturnItem[]},deps:ReturnDeps,sale:boolean):Promise<PostingResult>{
 if(!input.partyId)throw new ValidationError("Party is required for a return."); if(!Number.isSafeInteger(input.taxableValue)||input.taxableValue<=0)throw new ValidationError("Return taxable value must be positive."); validateItems(input.items); validateValue(input.items,input.taxableValue);
 const tax=calculateTax({taxableValue:input.taxableValue,rate:input.taxRate,intraState:input.intraState,cessRate:input.cessRate});
 const lines:VoucherLineInput[]=sale?[dr(req(input.accountMap.sales,"sales return"),input.taxableValue),cr(input.accountMap.party,tax.total,input.partyId),...taxLines(input,tax,input.accountMap,true)]:[cr(req(input.accountMap.purchases,"purchase return"),input.taxableValue),dr(input.accountMap.party,tax.total,input.partyId),...taxLines(input,tax,input.accountMap,false)];
 return repo.runInTransaction(async tx=>{const result=await postVoucher(tx,{businessId:input.businessId,financialYearId:input.financialYearId,voucherType:sale?"SALE_RETURN":"PURCHASE_RETURN",prefix:sale?"SR":"PR",date:input.date,narration:input.narration,createdBy:input.userId,referenceType:sale?"sale_return":"purchase_return",lines},deps);const movements:StockMovement[]=input.items.map(m=>createStockMovement({businessId:input.businessId,financialYearId:input.financialYearId,date:input.date,itemId:m.itemId,warehouseId:m.warehouseId,direction:sale?"in":"out",quantity:m.quantity,unitCost:m.unitCost,sourceType:sale?"sale_return":"purchase_return",sourceId:result.voucher.id,createdBy:input.userId},deps.ids,deps.clock.now()));await tx.saveStockMovements(movements);return {...result,stockMovements:movements};});
}
export async function postSaleReturn(repo:AccountingRepository,input:ReturnBase&{accountMap:ReturnAccounts;items:ReturnItem[]},deps:ReturnDeps){return postReturn(repo,input,deps,true);}
export async function postPurchaseReturn(repo:AccountingRepository,input:ReturnBase&{accountMap:ReturnAccounts;items:ReturnItem[]},deps:ReturnDeps){return postReturn(repo,input,deps,false);}
