import type { AccountingRepository, Money, PostingResult, VoucherLineInput, PartyAllocation } from "./types";
import { postIdempotentVoucher } from "./atomic";
import { ValidationError } from "./errors";
import { assertMoney } from "./money";
import type { TransactionDeps } from "./transactions";
export interface SettlementAccounts { party:string; cash:string; bank:string; }
export interface SettlementInput { businessId:string; financialYearId:string; date:string; userId:string; partyId:string; amount:Money; mode:"cash"|"bank"; accountMap:SettlementAccounts; idempotencyKey:string; narration?:string; }
export interface ReceiptAllocationInput { fromVoucherId:string; amount:Money; }
const debit=(accountId:string,amount:Money,partyId?:string):VoucherLineInput=>({accountId,debit:amount,credit:0,...(partyId?{partyId}: {})});
const credit=(accountId:string,amount:Money,partyId?:string):VoucherLineInput=>({accountId,debit:0,credit:amount,...(partyId?{partyId}: {})});
function validate(input:SettlementInput){if(!input.businessId||!input.financialYearId||!input.userId||!input.partyId)throw new ValidationError("Settlement business, financial year, user and party are required.");if(!/^\d{4}-\d{2}-\d{2}$/.test(input.date))throw new ValidationError("Settlement date must be YYYY-MM-DD.");if(!input.idempotencyKey)throw new ValidationError("Settlement idempotency key is required.");assertMoney(input.amount,"Settlement amount");if(input.amount<=0)throw new ValidationError("Settlement amount must be positive.");}
export async function postReceiptIdempotent(repo:AccountingRepository,input:SettlementInput,deps:TransactionDeps):Promise<PostingResult>{validate(input);return repo.runInTransaction(tx=>postIdempotentVoucher(tx,{businessId:input.businessId,financialYearId:input.financialYearId,voucherType:"RECEIPT",prefix:"RC",date:input.date,narration:input.narration,createdBy:input.userId,referenceType:"receipt",referenceId:input.partyId,lines:[debit(input.mode==="cash"?input.accountMap.cash:input.accountMap.bank,input.amount),credit(input.accountMap.party,input.amount,input.partyId)],idempotencyKey:input.idempotencyKey},deps));}
export async function postPaymentIdempotent(repo:AccountingRepository,input:SettlementInput,deps:TransactionDeps):Promise<PostingResult>{validate(input);return repo.runInTransaction(tx=>postIdempotentVoucher(tx,{businessId:input.businessId,financialYearId:input.financialYearId,voucherType:"PAYMENT",prefix:"PY",date:input.date,narration:input.narration,createdBy:input.userId,referenceType:"payment",referenceId:input.partyId,lines:[debit(input.accountMap.party,input.amount,input.partyId),credit(input.mode==="cash"?input.accountMap.cash:input.accountMap.bank,input.amount)],idempotencyKey:input.idempotencyKey},deps));}
export async function postReceiptWithAllocations(repo:AccountingRepository,input:SettlementInput,allocations:ReceiptAllocationInput[],deps:TransactionDeps):Promise<PostingResult>{
 validate(input);const seen=new Set<string>();let total=0;for(const a of allocations){if(!a.fromVoucherId||seen.has(a.fromVoucherId))throw new ValidationError("Each sales bill may be allocated only once.");seen.add(a.fromVoucherId);if(!Number.isSafeInteger(a.amount)||a.amount<=0)throw new ValidationError("Bill allocation must be positive.");total+=a.amount;}if(total>input.amount)throw new ValidationError("Bill allocations cannot exceed amount received.");
 return repo.runInTransaction(async tx=>{const v=await postIdempotentVoucher(tx,{businessId:input.businessId,financialYearId:input.financialYearId,voucherType:"RECEIPT",prefix:"RC",date:input.date,narration:input.narration,createdBy:input.userId,referenceType:"receipt",referenceId:input.partyId,lines:[debit(input.mode==="cash"?input.accountMap.cash:input.accountMap.bank,input.amount),credit(input.accountMap.party,input.amount,input.partyId)],idempotencyKey:input.idempotencyKey},deps);for(const a of allocations){const bill=await tx.getVoucher(a.fromVoucherId);if(!bill||bill.status!=="posted"||bill.voucherType!=="SALE")throw new ValidationError("Selected bill is not a posted sales invoice.");const lines=await tx.getVoucherLines(bill.id);const party=lines.find(x=>x.partyId===input.partyId&&x.debit>0);if(!party)throw new ValidationError(`Bill ${bill.voucherNumber} does not belong to this customer.`);const prior=await tx.getPartyAllocationsForVoucher(bill.id);const used=prior.filter(x=>x.fromVoucherId===bill.id).reduce((s,x)=>s+x.amount,0);if(a.amount>party.debit-used)throw new ValidationError(`Allocation exceeds outstanding balance of ${bill.voucherNumber}.`);const record:PartyAllocation={id:deps.ids.next("allocation"),businessId:input.businessId,partyId:input.partyId,fromVoucherId:bill.id,toVoucherId:v.voucher.id,amount:a.amount,date:input.date,createdBy:input.userId,createdAt:deps.clock.now(),idempotencyKey:`${input.idempotencyKey}-${bill.id}`};await tx.savePartyAllocations([record]);}return v;});}
