export type AccountType="asset"|"liability"|"equity"|"income"|"expense"|"contra_revenue";export type NormalBalance="debit"|"credit";export type VoucherStatus="draft"|"posted"|"cancelled";export type Money=number;
export interface FinancialYear{id:string;businessId:string;name:string;startDate:string;endDate:string;locked:boolean;}export interface Account{id:string;businessId:string;code:string;name:string;type:AccountType;parentId?:string|null;systemAccount:boolean;active:boolean;openingDebit:Money;openingCredit:Money;createdAt:string;updatedAt:string;}
export interface VoucherLineInput{accountId:string;partyId?:string;description?:string;debit:Money;credit:Money;costCenterId?:string;itemId?:string;warehouseId?:string;taxCode?:string;}export interface VoucherLine extends VoucherLineInput{lineId:string;voucherId:string;businessId:string;lineNo:number;}export interface Voucher{id:string;businessId:string;financialYearId:string;voucherType:string;voucherNumber:string;date:string;status:VoucherStatus;referenceType?:string;referenceId?:string;narration?:string;totalDebit:Money;totalCredit:Money;createdBy:string;createdAt:string;updatedAt:string;cancelledAt?:string;cancelledBy?:string;reversalOfVoucherId?:string;idempotencyKey?:string;}export interface LedgerEntry extends VoucherLine{date:string;voucherType:string;voucherNumber:string;createdAt:string;}
export type StockDirection="in"|"out";export type StockSourceType="opening"|"purchase"|"purchase_return"|"sale"|"sale_return"|"sale_cancel"|"purchase_cancel"|"adjustment"|"transfer";export interface StockMovement{id:string;businessId:string;financialYearId:string;date:string;itemId:string;warehouseId?:string;direction:StockDirection;quantity:number;unitCost:Money;value:Money;sourceType:StockSourceType;sourceId:string;createdBy:string;createdAt:string;batchId?:string;batchNumber?:string;manufactureDate?:string;expiryDate?:string;serialNumbers?:string[];unitId?:string;quantityInBaseUnit?:number;}
export interface TaxBreakdown{taxableValue:Money;cgst:Money;sgst:Money;igst:Money;cess:Money;totalTax:Money;total:Money;}export interface TaxInput{taxableValue:Money;rate:number;intraState:boolean;cessRate?:number;}export interface PartyBalance{partyId:string;debit:Money;credit:Money;net:Money;side:"debit"|"credit"|"zero";}
export interface PartyAllocation{id:string;businessId:string;partyId:string;fromVoucherId:string;toVoucherId:string;amount:Money;date:string;createdBy:string;createdAt:string;idempotencyKey:string;}export interface AuditEvent{id:string;businessId:string;entityType:string;entityId:string;action:string;userId:string;timestamp:string;before?:Record<string,unknown>;after?:Record<string,unknown>;metadata?:Record<string,unknown>;}
export interface ReturnDocument{id:string;businessId:string;financialYearId:string;type:"SALE_RETURN"|"PURCHASE_RETURN";voucherId:string;originalVoucherId:string;partyId:string;date:string;createdBy:string;items:Array<{itemId:string;quantity:number;unitCost:Money;warehouseId?:string}>;taxableValue:Money;taxTotal:Money;createdAt:string;}
export type AccountingDocumentType="sale"|"purchase"|"sale_return"|"purchase_return"|"receipt"|"payment"|"contra"|"journal"|"opening"|"party_allocation";export interface AtomicAccountingDocument{id:string;businessId:string;financialYearId:string;type:AccountingDocumentType;voucherId:string;idempotencyKey:string;status:"posted";date:string;createdBy:string;createdAt:string;payload:Record<string,unknown>;}
export interface PostingResult{voucher:Voucher;lines:VoucherLine[];ledgerEntries:LedgerEntry[];stockMovements:StockMovement[];}export interface IdGenerator{next(prefix:string):string;}export interface Clock{now():string;}
export interface AccountingRepository{runInTransaction<T>(work:(tx:AccountingTransaction)=>Promise<T>):Promise<T>;}export interface AccountingTransaction{getFinancialYear(id:string):Promise<FinancialYear|null>;getAccount(id:string):Promise<Account|null>;getVoucher(id:string):Promise<Voucher|null>;getVoucherLines(voucherId:string):Promise<VoucherLine[]>;getVouchersByReference(referenceType:string,referenceId:string):Promise<Voucher[]>;getVoucherByIdempotencyKey(businessId:string,financialYearId:string,idempotencyKey:string):Promise<Voucher|null>;getAtomicDocumentByIdempotencyKey(businessId:string,financialYearId:string,idempotencyKey:string):Promise<AtomicAccountingDocument|null>;getStockMovementsForSource(sourceId:string):Promise<StockMovement[]>;getStockMovementsForItem(itemId:string,warehouseId?:string,throughDate?:string):Promise<StockMovement[]>;getPartyAllocationsForVoucher(voucherId:string):Promise<PartyAllocation[]>;getBusinessDocument(collectionName:string,id:string):Promise<Record<string,unknown>|null>;saveVoucher(voucher:Voucher):Promise<void>;saveVoucherLines(lines:VoucherLine[]):Promise<void>;saveLedgerEntries(entries:LedgerEntry[]):Promise<void>;saveStockMovements(movements:StockMovement[]):Promise<void>;savePartyAllocations(allocations:PartyAllocation[]):Promise<void>;saveReturnDocument(document:ReturnDocument):Promise<void>;saveAtomicDocument(document:AtomicAccountingDocument):Promise<void>;saveBusinessDocument(collectionName:string,id:string,data:Record<string,unknown>):Promise<void>;saveAuditEvent(event:AuditEvent):Promise<void>;allocateVoucherNumber(input:{businessId:string;financialYearId:string;voucherType:string;prefix?:string}):Promise<string>;}
