import type { Money, StockMovement } from "./types";
import { ValidationError } from "./errors";
export type StockValuationMethod = "fifo" | "weighted_average";
export interface ValuationResult { quantity:number; value:Money; unitCost:Money; }
export interface CostResult { quantity:number; cost:Money; unitCost:Money; }
function ordered(movements:readonly StockMovement[]):StockMovement[]{return [...movements].sort((a,b)=>`${a.date}:${a.createdAt}:${a.id}`.localeCompare(`${b.date}:${b.createdAt}:${b.id}`));}
export function valueWeightedAverage(movements:readonly StockMovement[]):ValuationResult{let qty=0,value=0;for(const m of ordered(movements)){if(m.quantity<=0||!Number.isFinite(m.quantity)||!Number.isSafeInteger(m.value)||m.value<0)throw new ValidationError("Invalid stock movement.");if(m.direction==="in"){qty+=m.quantity;value+=m.value;}else{if(m.quantity>qty)throw new ValidationError("Stock cannot go negative under weighted-average valuation.");const avg=qty?value/qty:0;value-=Math.round(m.quantity*avg);qty-=m.quantity;}}if(qty<0||!Number.isSafeInteger(Math.round(value)))throw new ValidationError("Invalid stock valuation result.");return{quantity:qty,value:Math.max(0,Math.round(value)),unitCost:qty?Math.round(value/qty):0};}
export function valueFifo(movements:readonly StockMovement[]):ValuationResult{const lots:Array<{quantity:number;unitCost:Money}>=[];for(const m of ordered(movements)){if(m.direction==="in")lots.push({quantity:m.quantity,unitCost:m.unitCost});else{let remaining=m.quantity;while(remaining>0&&lots.length){const lot=lots[0];const take=Math.min(remaining,lot.quantity);lot.quantity-=take;remaining-=take;if(lot.quantity===0)lots.shift();}if(remaining>0)throw new ValidationError("Stock cannot go negative under FIFO valuation.");}}const quantity=lots.reduce((s,l)=>s+l.quantity,0);const value=lots.reduce((s,l)=>s+l.quantity*l.unitCost,0);return{quantity,value,unitCost:quantity?Math.round(value/quantity):0};}
export function calculateOutgoingCost(movements:readonly StockMovement[],quantity:number,method:StockValuationMethod):CostResult{if(!Number.isFinite(quantity)||quantity<=0)throw new ValidationError("Outgoing quantity must be positive.");const before=ordered(movements);if(method==="fifo"){const lots:Array<{quantity:number;unitCost:Money}>=[];for(const m of before){if(m.direction==="in")lots.push({quantity:m.quantity,unitCost:m.unitCost});else{let r=m.quantity;while(r>0&&lots.length){const l=lots[0],take=Math.min(r,l.quantity);l.quantity-=take;r-=take;if(l.quantity===0)lots.shift();}if(r>0)throw new ValidationError("Historical stock is negative.");}}let remaining=quantity,cost=0;for(const l of lots){if(remaining<=0)break;const take=Math.min(remaining,l.quantity);cost+=take*l.unitCost;remaining-=take;}if(remaining>0)throw new ValidationError("Insufficient stock for sale.");return{quantity,cost,unitCost:Math.round(cost/quantity)};}const state=valueWeightedAverage(before);if(quantity>state.quantity)throw new ValidationError("Insufficient stock for sale.");const cost=Math.round(quantity*state.unitCost);return{quantity,cost,unitCost:Math.round(cost/quantity)};}
