import {NextResponse} from "next/server";
import type {Firestore} from "firebase-admin/firestore";
import {getAdminServices} from "@/infrastructure/firebase/admin";
import type {BusinessMember} from "@/types";
export const runtime="nodejs";
const fail=(e:string,s=400)=>NextResponse.json({success:false,error:e},{status:s});
async function access(request:Request){const {auth,db}=getAdminServices();const h=request.headers.get("authorization")||"";if(!h.startsWith("Bearer "))throw Error("Authentication is required.");const token=await auth.verifyIdToken(h.slice(7));const u=new URL(request.url),businessId=(u.searchParams.get("businessId")||"").trim();if(!businessId)throw Error("Business ID is required.");const m=await db.collection("businesses").doc(businessId).collection("members").doc(token.uid).get();if(!m.exists||((m.data() as BusinessMember).status!=="active"))throw Object.assign(Error("Business membership is not active."),{statusCode:403});const member=m.data() as BusinessMember;if(member.role!=="owner"&&member.role!=="admin"&&!member.permissions?.inventory?.view)throw Object.assign(Error("Permission denied: inventory reports."),{statusCode:403});return{db,businessId,uid:token.uid};}
async function year(db:Firestore,businessId:string){const s=await db.collection("businesses").doc(businessId).collection("financialYears").where("locked","==",false).get();const d=s.docs.sort((a,b)=>String(b.data()?.startDate||"").localeCompare(String(a.data()?.startDate||"")));if(!d.length)throw Error("No active financial year is configured.");return d[0].id;}
export async function GET(request:Request){try{const {db,businessId}=await access(request),u=new URL(request.url),view=u.searchParams.get("view")||"summary",itemId=(u.searchParams.get("itemId")||"").trim(),financialYearId=await year(db,businessId);const base=db.collection("businesses").doc(businessId);const [itemsSnap,movesSnap]=await Promise.all([base.collection("items").get(),base.collection("stockMovements").where("financialYearId","==",financialYearId).get()]);const items=itemsSnap.docs.map(d=>({id:d.id,...d.data()})) as Record<string,any>[];const movements=movesSnap.docs.map(d=>({id:d.id,...d.data()})) as Record<string,any>[];if(view==="ledger"){const rows=movements.filter(x=>!itemId||x.itemId===itemId).sort((a,b)=>String(a.date||a.createdAt||"").localeCompare(String(b.date||b.createdAt||"")));let balance=0;return NextResponse.json({success:true,financialYearId,view,rows:rows.map(x=>{const q=Number(x.quantity||0),inQty=x.direction==="in"?q:0,outQty=x.direction==="out"?q:0;balance+=inQty-outQty;return{...x,quantityIn:inQty,quantityOut:outQty,balanceQuantity:balance}})});}const byItem=new Map<string,any>();for(const i of items)byItem.set(i.id,{itemId:i.id,name:i.name,code:i.code,unit:i.unit,quantity:0,value:0,minStock:Number(i.minStock||0),reorderLevel:Number(i.reorderLevel??i.minStock??0)});for(const m of movements){const x=byItem.get(m.itemId);if(!x)continue;const sign=m.direction==="in"?1:-1;x.quantity+=Number(m.quantity||0)*sign;x.value+=Number(m.value||0)*sign;}let rows=[...byItem.values()];if(view==="low")rows=rows.filter(x=>x.quantity<=x.reorderLevel);if(view==="warehouse"){const map=new Map<string,any>();for(const m of movements){const w=String(m.warehouseId||"default");const key=`${m.itemId}:${w}`,x=map.get(key)||{itemId:m.itemId,warehouseId:w,quantity:0,value:0};x.quantity+=(m.direction==="in"?1:-1)*Number(m.quantity||0);x.value+=(m.direction==="in"?1:-1)*Number(m.value||0);map.set(key,x);}rows=[...map.values()].map(x=>({...x,name:items.find(i=>i.id===x.itemId)?.name||x.itemId}));}if(view==="expiry"||view==="batch"){rows=movements.filter(x=>x.batchNumber||x.batchId||x.expiryDate||x.serialNumbers).sort((a,b)=>String(a.expiryDate||"").localeCompare(String(b.expiryDate||"")));}return NextResponse.json({success:true,financialYearId,view,rows});}catch(e){return fail(e instanceof Error?e.message:"Could not load inventory report.",(e as any).statusCode||400);}}
