"use client";

import { useEffect, useMemo, useState } from "react";
import type { ReactNode } from "react";
import { firebaseAuth } from "@/lib/firebase";
import { useBusiness } from "@/context/BusinessContext";
import Sidebar from "@/app/Components/Sidebar/page";
import TopNav from "@/app/Components/TopNav/page";
import AuthGate from "@/app/Components/Auth/AuthGate";

type Account={accountId:string;businessId:string;displayName:string;kind:"cash"|"bank";ledgerAccountId:string;currentBalance:number;openingBalance?:number;openingBalanceDate?:string;bankName?:string;accountNumber?:string;ifscCode?:string;upiId?:string;accountHolderName?:string;status:"active"|"inactive";ledgerHealthy?:boolean;printQrOnInvoice?:boolean;printDetailsOnInvoice?:boolean};
type GL={accountId:string;name:string;type:string;active:boolean};
type Ledger={lineId:string;voucherId:string;date:string;voucherNumber?:string;voucherType?:string;accountId:string;description?:string;debit:number;credit:number};
type Modal="account"|"edit"|"entry"|"transfer"|null;

const money=(n:number)=>new Intl.NumberFormat("en-IN",{style:"currency",currency:"INR",maximumFractionDigits:2}).format((Number(n)||0)/100);
const today=()=>new Date().toISOString().slice(0,10);
async function api(path:string,body?:Record<string,unknown>){const user=firebaseAuth.currentUser;if(!user)throw new Error("You must be signed in.");const token=await user.getIdToken();const response=await fetch(path,{method:body?"POST":"GET",headers:{Authorization:`Bearer ${token}`,...(body?{"Content-Type":"application/json"}:{})},body:body?JSON.stringify(body):undefined,cache:"no-store"});const data=await response.json().catch(()=>({success:false,error:"Invalid server response."}));if(!response.ok||!data.success)throw new Error(data.error||"Request failed.");return data;}
function Icon({name}:{name:"cash"|"bank"|"transfer"|"plus"|"search"|"edit"|"undo"|"power"}){const paths={cash:"M4 7h16v12H4zM7 7V5h10v2M8 13h8M12 10v6",bank:"M3 10 12 4l9 6M5 10v8M9 10v8M15 10v8M19 10v8M3 18h18",transfer:"M7 7h10l-3-3m3 3-3 3M17 17H7l3 3m-3-3 3-3",plus:"M12 5v14M5 12h14",search:"m21 21-4.5-4.5M10.5 18a7.5 7.5 0 1 1 0-15 7.5 7.5 0 0 1 0 15Z",edit:"m4 20 4.3-1 10.1-10.1a2.1 2.1 0 0 0-3-3L5.3 16 4 20ZM14.8 7.2l2 2",undo:"M9 8H4v5m0-5 4 4",power:"M12 3v9m6.4-6.4a9 9 0 1 1-12.8 0"};return <svg className="h-4 w-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.8" strokeLinecap="round" strokeLinejoin="round" aria-hidden="true"><path d={paths[name]}/></svg>;}
function Field({label,children}:{label:string;children:ReactNode}){return <label className="block"><span className="mb-1.5 block text-xs font-semibold text-[#344054]">{label}</span>{children}</label>;}

export default function CashBankPage(){
 const {activeBusinessId,activeBusiness,can,loading:businessLoading}=useBusiness();
 const [accounts,setAccounts]=useState<Account[]>([]),[gl,setGl]=useState<GL[]>([]),[ledger,setLedger]=useState<Ledger[]>([]),[fy,setFy]=useState(""),[selected,setSelected]=useState<Account|null>(null);
 const [modal,setModal]=useState<Modal>(null),[kind,setKind]=useState<"cash"|"bank">("bank"),[entryType,setEntryType]=useState<"deposit"|"withdrawal">("deposit");
 const [query,setQuery]=useState(""),[showInactive,setShowInactive]=useState(false),[loading,setLoading]=useState(true),[error,setError]=useState(""),[saving,setSaving]=useState(false);
 const [form,setForm]=useState({displayName:"",openingBalance:"0",openingBalanceDate:today(),bankName:"",accountNumber:"",ifscCode:"",upiId:"",accountHolderName:""});
 const [entry,setEntry]=useState({name:"",amount:"",date:today(),reference:"",notes:"",contra:""});
 const [transfer,setTransfer]=useState({from:"",to:"",amount:"",date:today(),reference:"",notes:""});
 const canCreate=can("cashBank","create"),canEdit=can("cashBank","edit");
 async function load(){if(!activeBusinessId)return;setLoading(true);setError("");try{const data=await api(`/api/cash-bank?businessId=${encodeURIComponent(activeBusinessId)}&includeInactive=${showInactive}`);setAccounts(data.accounts||[]);setGl(data.glAccounts||[]);setLedger(data.ledger||[]);setFy(data.financialYearId||"");setSelected((prev)=> (data.accounts||[]).find((a:Account)=>a.accountId===prev?.accountId)||(data.accounts||[]).find((a:Account)=>a.status==="active")||(data.accounts||[])[0]||null);}catch(e){setError(e instanceof Error?e.message:"Unable to load Cash & Bank.");}finally{setLoading(false);}}
 useEffect(()=>{if(!businessLoading)void load();},[activeBusinessId,businessLoading,showInactive]);
 const filteredAccounts=useMemo(()=>{const q=query.trim().toLowerCase();return accounts.filter(a=>!q||`${a.displayName} ${a.bankName||""} ${a.accountNumber||""}`.toLowerCase().includes(q));},[accounts,query]);
 const activeAccounts=useMemo(()=>accounts.filter(a=>a.status==="active"),[accounts]);
 const selectedRows=useMemo(()=>selected?ledger.filter(x=>x.accountId===selected.ledgerAccountId).sort((a,b)=>`${a.date}:${a.voucherNumber||""}:${a.lineId}`.localeCompare(`${b.date}:${b.voucherNumber||""}:${b.lineId}`)):[],[selected,ledger]);
 const ledgerRows=useMemo(()=>{let running=Number(selected?.openingBalance||0);return selectedRows.map(x=>{running+=Number(x.debit||0)-Number(x.credit||0);return{...x,running};});},[selectedRows,selected]);
 const totals=useMemo(()=>({cash:accounts.filter(a=>a.kind==="cash"&&a.status==="active").reduce((s,a)=>s+a.currentBalance,0),bank:accounts.filter(a=>a.kind==="bank"&&a.status==="active").reduce((s,a)=>s+a.currentBalance,0)}),[accounts]);
 function reset(){setModal(null);setSaving(false);setError("");setEntry({name:"",amount:"",date:today(),reference:"",notes:"",contra:""});setTransfer({from:"",to:"",amount:"",date:today(),reference:"",notes:""});setForm({displayName:"",openingBalance:"0",openingBalanceDate:today(),bankName:"",accountNumber:"",ifscCode:"",upiId:"",accountHolderName:""});}
 function fillEdit(a:Account){setSelected(a);setKind(a.kind);setForm({displayName:a.displayName,openingBalance:String((Number(a.openingBalance||0)/100).toFixed(2)),openingBalanceDate:a.openingBalanceDate||today(),bankName:a.bankName||"",accountNumber:a.accountNumber||"",ifscCode:a.ifscCode||"",upiId:a.upiId||"",accountHolderName:a.accountHolderName||""});setModal("edit");setError("");}
 async function createAccount(){if(!activeBusinessId)return;try{setSaving(true);if(!form.displayName.trim())throw new Error("Account name is required.");await api("/api/cash-bank",{action:"account",businessId:activeBusinessId,kind,displayName:form.displayName,openingBalance:Number(form.openingBalance||0),openingBalanceDate:form.openingBalanceDate,bankName:form.bankName,accountNumber:form.accountNumber,ifscCode:form.ifscCode,upiId:form.upiId,accountHolderName:form.accountHolderName});reset();await load();}catch(e){setError(e instanceof Error?e.message:"Unable to create account.");}finally{setSaving(false);}}
 async function updateAccount(){if(!activeBusinessId||!selected)return;try{setSaving(true);await api("/api/cash-bank",{action:"account_update",businessId:activeBusinessId,accountId:selected.accountId,displayName:form.displayName,bankName:form.bankName,accountNumber:form.accountNumber,ifscCode:form.ifscCode,upiId:form.upiId,accountHolderName:form.accountHolderName});reset();await load();}catch(e){setError(e instanceof Error?e.message:"Unable to update account.");}finally{setSaving(false);}}
 async function toggleStatus(){if(!activeBusinessId||!selected)return;const next=selected.status==="active"?"inactive":"active";if(!window.confirm(`${next==="inactive"?"Deactivate":"Activate"} ${selected.displayName}?`))return;try{setSaving(true);await api("/api/cash-bank",{action:"account_status",businessId:activeBusinessId,accountId:selected.accountId,status:next});await load();}catch(e){setError(e instanceof Error?e.message:"Unable to change account status.");}finally{setSaving(false);}}
 async function submitEntry(){if(!activeBusinessId||!selected)return;try{setSaving(true);const amount=Number(entry.amount),contra=gl.find(a=>a.accountId===entry.contra);if(!entry.name.trim()||amount<=0||!contra)throw new Error("Enter a description, positive amount, and counter account.");await api("/api/cash-bank",{action:"entry",businessId:activeBusinessId,financialYearId:fy,accountId:selected.accountId,type:entryType,amount,name:entry.name,date:entry.date,reference:entry.reference,notes:entry.notes,contraAccountId:contra.accountId,idempotencyKey:`cb-${crypto.randomUUID()}`});reset();await load();}catch(e){setError(e instanceof Error?e.message:"Unable to post transaction.");}finally{setSaving(false);}}
 async function submitTransfer(){if(!activeBusinessId)return;try{setSaving(true);const amount=Number(transfer.amount);if(!transfer.from||!transfer.to||transfer.from===transfer.to||amount<=0)throw new Error("Select different active source/destination accounts and a positive amount.");await api("/api/cash-bank",{action:"transfer",businessId:activeBusinessId,financialYearId:fy,fromAccountId:transfer.from,toAccountId:transfer.to,amount,date:transfer.date,reference:transfer.reference,notes:transfer.notes,idempotencyKey:`cb-transfer-${crypto.randomUUID()}`});reset();await load();}catch(e){setError(e instanceof Error?e.message:"Unable to post transfer.");}finally{setSaving(false);}}
 async function reverse(voucherId:string){if(!activeBusinessId)return;if(!window.confirm("Reverse this Cash & Bank voucher? A reversal voucher will be posted; the original will remain in history."))return;try{setSaving(true);await api("/api/cash-bank",{action:"reverse",businessId:activeBusinessId,voucherId,date:today(),idempotencyKey:`cb-reversal-${crypto.randomUUID()}`});await load();}catch(e){setError(e instanceof Error?e.message:"Unable to reverse voucher.");}finally{setSaving(false);}}

 return <AuthGate><div className="flex min-h-screen bg-[#f8f9fb]"><Sidebar/><main className="min-w-0 flex-1 px-5 pb-10 sm:px-8 lg:px-10"><TopNav/><div className="mx-auto max-w-[1500px] py-5">
  <header className="flex flex-wrap items-end justify-between gap-4"><div><p className="text-sm font-semibold text-[#465fff]">{activeBusiness?.business.name||"Business"} · Money</p><h1 className="mt-1 text-3xl font-bold tracking-tight text-[#101828]">Cash & Bank</h1><p className="mt-1 text-sm text-[#667085]">Accounts, deposits, withdrawals, transfers and controlled reversals.</p></div>{canCreate&&<div className="flex gap-2"><button type="button" onClick={()=>setModal("transfer")} className="inline-flex h-10 items-center gap-2 rounded-lg border border-[#d0d5dd] bg-white px-4 text-sm font-semibold text-[#344054] shadow-sm"><Icon name="transfer"/>Transfer</button><button type="button" onClick={()=>setModal("account")} className="inline-flex h-10 items-center gap-2 rounded-lg bg-[#465fff] px-4 text-sm font-semibold text-white shadow-sm"><Icon name="plus"/>New Account</button></div>}</header>
  {error&&<div className="mt-4 flex items-center justify-between rounded-lg border border-[#fecdca] bg-[#fef3f2] px-4 py-3 text-sm text-[#b42318]"><span>{error}</span><button type="button" onClick={()=>setError("")} className="font-semibold">×</button></div>}
  <section className="mt-6 grid gap-4 sm:grid-cols-3"><Stat label="Total liquidity" value={money(totals.cash+totals.bank)} hint="Active cash + bank" icon="bank"/><Stat label="Cash in hand" value={money(totals.cash)} hint="Active cash accounts" icon="cash"/><Stat label="Bank balance" value={money(totals.bank)} hint="Active bank accounts" icon="bank"/></section>
  <section className="mt-6 rounded-xl border border-[#e4e7ec] bg-white shadow-sm"><div className="flex flex-wrap items-center justify-between gap-3 border-b border-[#eaecf0] px-5 py-4"><div><h2 className="font-bold text-[#101828]">Accounts</h2><p className="mt-0.5 text-xs text-[#98a2b3]">FY {fy||"—"} · {accounts.length} displayed</p></div><div className="flex items-center gap-3"><label className="flex items-center gap-2 text-xs font-medium text-[#667085]"><input type="checkbox" checked={showInactive} onChange={e=>setShowInactive(e.target.checked)}/>Show inactive</label><div className="relative"><span className="pointer-events-none absolute left-3 top-1/2 -translate-y-1/2 text-[#98a2b3]"><Icon name="search"/></span><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search accounts" className="h-9 w-56 rounded-lg border border-[#d0d5dd] pl-9 pr-3 text-sm outline-none"/></div></div></div>
   <div className="grid lg:grid-cols-[380px_1fr]"> <div className="border-b border-[#eaecf0] lg:border-b-0 lg:border-r">{loading?<div className="space-y-3 p-5">{[1,2,3].map(x=><div key={x} className="h-20 animate-pulse rounded-lg bg-[#f2f4f7]"/>)}</div>:!filteredAccounts.length?<div className="p-10 text-center text-sm text-[#667085]">No matching accounts.</div>:<div className="divide-y divide-[#eaecf0]">{filteredAccounts.map(a=><button key={a.accountId} type="button" onClick={()=>setSelected(a)} className={`w-full px-5 py-4 text-left hover:bg-[#f9fafb] ${selected?.accountId===a.accountId?"bg-[#f5f7ff]":""}`}><div className="flex items-start gap-3"><span className={`mt-0.5 flex h-9 w-9 shrink-0 items-center justify-center rounded-lg ${a.kind==="cash"?"bg-[#ecfdf3] text-[#039855]":"bg-[#edf2ff] text-[#465fff]"}`}><Icon name={a.kind}/></span><span className="min-w-0 flex-1"><span className="flex items-center justify-between gap-2"><span className="truncate text-sm font-semibold text-[#344054]">{a.displayName}</span><span className={`text-[11px] font-semibold ${a.status==="active"?"text-[#039855]":"text-[#98a2b3]"}`}>{a.status}</span></span><span className="mt-1 block text-xs text-[#98a2b3]">{a.kind==="bank"?(a.bankName||"Bank account"):"Cash account"}</span><span className="mt-2 block text-base font-bold text-[#101828]">{money(a.currentBalance)}</span></span></div></button>)}</div>}</div>
   <div className="min-w-0">{selected?<><div className="flex flex-wrap items-center justify-between gap-3 border-b border-[#eaecf0] px-5 py-4"><div><div className="flex items-center gap-2"><span className={`flex h-7 w-7 items-center justify-center rounded-md ${selected.kind==="cash"?"bg-[#ecfdf3] text-[#039855]":"bg-[#edf2ff] text-[#465fff]"}`}><Icon name={selected.kind}/></span><h3 className="font-bold text-[#101828]">{selected.displayName}</h3><span className={`rounded-full px-2 py-0.5 text-[10px] font-semibold ${selected.status==="active"?"bg-[#ecfdf3] text-[#027a48]":"bg-[#f2f4f7] text-[#667085]"}`}>{selected.status}</span></div><p className="mt-1 text-xs text-[#98a2b3]">{selected.kind==="bank"?`${selected.bankName||"Bank"}${selected.accountNumber?` · •••• ${selected.accountNumber.slice(-4)}`:""}`:"Cash account"}{!selected.ledgerHealthy&&<span className="ml-2 text-[#b42318]">· Ledger link needs repair</span>}</p></div><div className="flex flex-wrap gap-2">{canEdit&&<><button type="button" onClick={()=>fillEdit(selected)} className="inline-flex h-9 items-center gap-2 rounded-lg border border-[#d0d5dd] bg-white px-3 text-xs font-semibold text-[#344054]"><Icon name="edit"/>Edit</button><button type="button" disabled={saving} onClick={toggleStatus} className="inline-flex h-9 items-center gap-2 rounded-lg border border-[#d0d5dd] bg-white px-3 text-xs font-semibold text-[#344054]"><Icon name="power"/>{selected.status==="active"?"Deactivate":"Activate"}</button></>}{canCreate&&selected.status==="active"&&<><button type="button" onClick={()=>{setEntryType("deposit");setModal("entry");}} className="h-9 rounded-lg bg-[#039855] px-3 text-xs font-semibold text-white">+ Deposit</button><button type="button" onClick={()=>{setEntryType("withdrawal");setModal("entry");}} className="h-9 rounded-lg bg-[#d92d20] px-3 text-xs font-semibold text-white">− Withdrawal</button></>}</div></div>
    <div className="flex items-center justify-between border-b border-[#eaecf0] bg-[#fcfcfd] px-5 py-3"><div><span className="text-xs font-semibold uppercase tracking-wide text-[#667085]">Posted ledger</span>{ledger.length>300&&<p className="mt-0.5 text-[11px] text-[#b54708]">Only the newest 300 ledger lines are loaded.</p>}</div><div className="text-sm font-bold text-[#101828]">Closing {money(selected.currentBalance)}</div></div>
    <div className="overflow-x-auto"><table className="w-full min-w-[860px] text-sm"><thead className="bg-[#f9fafb] text-left text-xs font-semibold uppercase tracking-wide text-[#667085]"><tr><th className="px-4 py-3">Date</th><th className="px-4 py-3">Voucher</th><th className="px-4 py-3">Particulars</th><th className="px-4 py-3 text-right">Debit</th><th className="px-4 py-3 text-right">Credit</th><th className="px-4 py-3 text-right">Balance</th><th className="px-4 py-3 text-right">Action</th></tr></thead><tbody className="divide-y divide-[#eaecf0]">{ledgerRows.map(x=><tr key={x.lineId} className="hover:bg-[#f9fafb]"><td className="whitespace-nowrap px-4 py-3 text-[#667085]">{x.date}</td><td className="whitespace-nowrap px-4 py-3 font-medium text-[#344054]">{x.voucherNumber||"—"}</td><td className="max-w-[300px] truncate px-4 py-3 text-[#344054]">{x.description||x.voucherType||"—"}</td><td className="px-4 py-3 text-right font-medium text-[#039855]">{x.debit?money(x.debit):"—"}</td><td className="px-4 py-3 text-right font-medium text-[#d92d20]">{x.credit?money(x.credit):"—"}</td><td className="px-4 py-3 text-right font-semibold text-[#101828]">{money(x.running)}</td><td className="px-4 py-3 text-right">{canEdit&&x.voucherId?<button type="button" onClick={()=>reverse(x.voucherId)} className="inline-flex items-center gap-1 rounded-md border border-[#fecdca] px-2 py-1 text-[11px] font-semibold text-[#b42318]"><Icon name="undo"/>Reverse</button>:"—"}</td></tr>)}</tbody></table>{!ledgerRows.length&&<div className="p-12 text-center"><p className="font-semibold text-[#344054]">No posted entries</p><p className="mt-1 text-sm text-[#98a2b3]">Transactions for this account will appear here.</p></div>}</div></>:<div className="grid min-h-[430px] place-items-center p-10 text-center"><div><div className="mx-auto flex h-14 w-14 items-center justify-center rounded-full bg-[#f2f4f7] text-[#667085]"><Icon name="bank"/></div><h3 className="mt-4 font-semibold text-[#101828]">Select an account</h3><p className="mt-1 max-w-sm text-sm text-[#667085]">Choose a cash or bank account to inspect its ledger.</p></div></div>}</div></div>
  </section>
 </div></main>
 {modal&&<ModalShell title={modal==="account"?"Create account":modal==="edit"?"Edit account":modal==="transfer"?"Transfer money":`Record ${entryType}`} onClose={reset}>
  {modal==="account"||modal==="edit"?<><div className="grid grid-cols-2 gap-2"><button type="button" disabled={modal==="edit"} onClick={()=>setKind("bank")} className={`h-10 rounded-lg border text-sm font-semibold ${kind==="bank"?"border-[#465fff] bg-[#f5f7ff] text-[#465fff]":"border-[#d0d5dd] text-[#667085]"}`}>Bank account</button><button type="button" disabled={modal==="edit"} onClick={()=>setKind("cash")} className={`h-10 rounded-lg border text-sm font-semibold ${kind==="cash"?"border-[#465fff] bg-[#f5f7ff] text-[#465fff]":"border-[#d0d5dd] text-[#667085]"}`}>Cash account</button></div><Field label="Account name"><input className="input" value={form.displayName} onChange={e=>setForm({...form,displayName:e.target.value})}/></Field>{modal==="account"&&<Field label="Opening balance"><input className="input" type="number" min="0" value={form.openingBalance} onChange={e=>setForm({...form,openingBalance:e.target.value})}/></Field>} {modal==="account"&&<Field label="Opening balance date"><input className="input" type="date" value={form.openingBalanceDate} onChange={e=>setForm({...form,openingBalanceDate:e.target.value})}/></Field>}{kind==="bank"&&<div className="grid gap-4 sm:grid-cols-2"><Field label="Bank name"><input className="input" value={form.bankName} onChange={e=>setForm({...form,bankName:e.target.value})}/></Field><Field label="Account number"><input className="input" value={form.accountNumber} onChange={e=>setForm({...form,accountNumber:e.target.value})}/></Field><Field label="IFSC"><input className="input" value={form.ifscCode} onChange={e=>setForm({...form,ifscCode:e.target.value})}/></Field><Field label="UPI ID"><input className="input" value={form.upiId} onChange={e=>setForm({...form,upiId:e.target.value})}/></Field><Field label="Account holder"><input className="input" value={form.accountHolderName} onChange={e=>setForm({...form,accountHolderName:e.target.value})}/></Field></div>}{modal==="account"?<button disabled={saving} type="button" onClick={createAccount} className="w-full h-10 rounded-lg bg-[#465fff] text-sm font-semibold text-white">{saving?"Creating…":"Create account"}</button>:<button disabled={saving} type="button" onClick={updateAccount} className="w-full h-10 rounded-lg bg-[#465fff] text-sm font-semibold text-white">{saving?"Saving…":"Save changes"}</button>}</>:null}
  {modal==="transfer"&&<><Field label="From account"><select className="input" value={transfer.from} onChange={e=>setTransfer({...transfer,from:e.target.value})}><option value="">Select source</option>{activeAccounts.map(a=><option key={a.accountId} value={a.accountId}>{a.displayName}</option>)}</select></Field><Field label="To account"><select className="input" value={transfer.to} onChange={e=>setTransfer({...transfer,to:e.target.value})}><option value="">Select destination</option>{activeAccounts.map(a=><option key={a.accountId} value={a.accountId}>{a.displayName}</option>)}</select></Field><Field label="Amount"><input className="input" type="number" min="0.01" value={transfer.amount} onChange={e=>setTransfer({...transfer,amount:e.target.value})}/></Field><div className="grid grid-cols-2 gap-4"><Field label="Date"><input className="input" type="date" value={transfer.date} onChange={e=>setTransfer({...transfer,date:e.target.value})}/></Field><Field label="Reference"><input className="input" value={transfer.reference} onChange={e=>setTransfer({...transfer,reference:e.target.value})}/></Field></div><Field label="Notes"><textarea className="input min-h-20" value={transfer.notes} onChange={e=>setTransfer({...transfer,notes:e.target.value})}/></Field><button disabled={saving} type="button" onClick={submitTransfer} className="w-full h-10 rounded-lg bg-[#465fff] text-sm font-semibold text-white">{saving?"Posting…":"Post transfer"}</button></>}
  {modal==="entry"&&<><Field label="Description"><input className="input" value={entry.name} onChange={e=>setEntry({...entry,name:e.target.value})}/></Field><Field label="Amount"><input className="input" type="number" min="0.01" value={entry.amount} onChange={e=>setEntry({...entry,amount:e.target.value})}/></Field><Field label="Counter account"><select className="input" value={entry.contra} onChange={e=>setEntry({...entry,contra:e.target.value})}><option value="">Select counter account</option>{gl.filter(a=>a.accountId!==selected?.ledgerAccountId).map(a=><option key={a.accountId} value={a.accountId}>{a.name}</option>)}</select></Field><div className="grid grid-cols-2 gap-4"><Field label="Date"><input className="input" type="date" value={entry.date} onChange={e=>setEntry({...entry,date:e.target.value})}/></Field><Field label="Reference"><input className="input" value={entry.reference} onChange={e=>setEntry({...entry,reference:e.target.value})}/></Field></div><Field label="Notes"><textarea className="input min-h-20" value={entry.notes} onChange={e=>setEntry({...entry,notes:e.target.value})}/></Field><button disabled={saving} type="button" onClick={submitEntry} className={`w-full h-10 rounded-lg text-sm font-semibold text-white ${entryType==="deposit"?"bg-[#039855]":"bg-[#d92d20]"}`}>{saving?"Posting…":`Post ${entryType}`}</button></>}
 </ModalShell>}
 </div></AuthGate>;
}
function Stat({label,value,hint,icon}:{label:string;value:string;hint:string;icon:"cash"|"bank"}){return <div className="rounded-xl border border-[#e4e7ec] bg-white p-5 shadow-sm"><div className="flex items-center justify-between"><span className="text-sm font-medium text-[#667085]">{label}</span><span className="flex h-9 w-9 items-center justify-center rounded-lg bg-[#edf2ff] text-[#465fff]"><Icon name={icon}/></span></div><p className="mt-3 text-2xl font-bold text-[#101828]">{value}</p><p className="mt-1 text-xs text-[#98a2b3]">{hint}</p></div>}
function ModalShell({title,onClose,children}:{title:string;onClose:()=>void;children:ReactNode}){return <div className="fixed inset-0 z-50 flex items-center justify-center bg-[#101828]/45 p-4" onMouseDown={e=>{if(e.target===e.currentTarget)onClose();}}><div className="w-full max-w-lg overflow-hidden rounded-xl border border-[#e4e7ec] bg-white shadow-2xl"><div className="flex items-center justify-between border-b border-[#eaecf0] px-6 py-4"><h2 className="font-bold text-[#101828]">{title}</h2><button type="button" onClick={onClose} className="text-xl text-[#98a2b3]">×</button></div><div className="space-y-4 p-6">{children}</div></div></div>}
