import { describe, expect, it } from "vitest";
import { InMemoryAccountingRepository, fixedClock, testIds } from "../inMemoryRepository";
import { postVoucher, reverseVoucher, assertPostedVoucherImmutable } from "../voucher";
import { postIdempotentVoucher } from "../atomic";
import { AuthorizationError, PostedVoucherMutationError, ValidationError } from "../errors";
import { assertAuthorized } from "../authorization";
import type { Account, FinancialYear } from "../types";

const fy:FinancialYear={id:"fy-2026-27",businessId:"biz-1",name:"FY 2026-27",startDate:"2026-04-01",endDate:"2027-03-31",locked:false};
const account=(id:string,type:Account["type"]):Account=>({id,businessId:"biz-1",code:id,name:id,type,parentId:null,systemAccount:true,active:true,openingDebit:0,openingCredit:0,createdAt:"2026-04-01T00:00:00.000Z",updatedAt:"2026-04-01T00:00:00.000Z"});
function seed(repo:InMemoryAccountingRepository){repo.financialYears.set(fy.id,fy);repo.accounts.set("cash",account("cash","asset"));repo.accounts.set("sales",account("sales","income"));repo.accounts.set("expense",account("expense","expense"));}
function voucherInput(overrides:Partial<Parameters<typeof postVoucher>[1]>={}){return{businessId:"biz-1",financialYearId:fy.id,voucherType:"JOURNAL",date:"2026-08-30",createdBy:"user-1",lines:[{accountId:"cash",debit:1000,credit:0},{accountId:"sales",debit:0,credit:1000}],...overrides};}

describe("accounting core production hardening",()=>{
  it("rejects every unbalanced voucher at the domain boundary",async()=>{const r=new InMemoryAccountingRepository();seed(r);await expect(r.runInTransaction(tx=>postVoucher(tx,voucherInput({lines:[{accountId:"cash",debit:1000,credit:0},{accountId:"sales",debit:0,credit:900}]}),{ids:testIds(),clock:fixedClock()}))).rejects.toThrow(/Unbalanced voucher/);expect(r.vouchers.size).toBe(0);expect(r.ledgerEntries.size).toBe(0);});
  it("rejects inactive and foreign accounts",async()=>{const r=new InMemoryAccountingRepository();seed(r);r.accounts.get("cash")!.active=false;await expect(r.runInTransaction(tx=>postVoucher(tx,voucherInput(),{ids:testIds(),clock:fixedClock()}))).rejects.toThrow(/inactive/);r.accounts.set("foreign",{...account("foreign","asset"),businessId:"biz-2"});await expect(r.runInTransaction(tx=>postVoucher(tx,voucherInput({lines:[{accountId:"foreign",debit:1000,credit:0},{accountId:"sales",debit:0,credit:1000}]}),{ids:testIds(),clock:fixedClock()}))).rejects.toThrow(/another business/);});
  it("rejects wrong financial year and locked periods",async()=>{const r=new InMemoryAccountingRepository();seed(r);await expect(r.runInTransaction(tx=>postVoucher(tx,voucherInput({date:"2025-03-31"}),{ids:testIds(),clock:fixedClock()}))).rejects.toThrow(/outside the financial year/);r.financialYears.set(fy.id,{...fy,locked:true});await expect(r.runInTransaction(tx=>postVoucher(tx,voucherInput(),{ids:testIds(),clock:fixedClock()}))).rejects.toThrow(/locked/);});
  it("returns the exact same result for an identical duplicate submission",async()=>{const r=new InMemoryAccountingRepository();seed(r);const input={...voucherInput(),idempotencyKey:"sale-1"};const first=await r.runInTransaction(tx=>postIdempotentVoucher(tx,input,{ids:testIds(),clock:fixedClock()}));const second=await r.runInTransaction(tx=>postIdempotentVoucher(tx,input,{ids:testIds("other"),clock:fixedClock()}));expect(second.voucher.id).toBe(first.voucher.id);expect(r.vouchers.size).toBe(1);});
  it("rejects reuse of an idempotency key with a different payload",async()=>{const r=new InMemoryAccountingRepository();seed(r);await r.runInTransaction(tx=>postIdempotentVoucher(tx,{...voucherInput(),idempotencyKey:"same"},{ids:testIds(),clock:fixedClock()}));await expect(r.runInTransaction(tx=>postIdempotentVoucher(tx,{...voucherInput({narration:"different"}),idempotencyKey:"same"},{ids:testIds("other"),clock:fixedClock()}))).rejects.toThrow(/different accounting payload/);expect(r.vouchers.size).toBe(1);});
  it("never leaves partial state when a transaction fails",async()=>{const r=new InMemoryAccountingRepository();seed(r);await expect(r.runInTransaction(async tx=>{await postVoucher(tx,voucherInput(),{ids:testIds(),clock:fixedClock()});throw new Error("forced failure");})).rejects.toThrow("forced failure");expect(r.vouchers.size).toBe(0);expect(r.voucherLines.size).toBe(0);expect(r.ledgerEntries.size).toBe(0);});
  it("prevents editing a posted voucher",()=>{expect(()=>assertPostedVoucherImmutable({...({status:"posted"} as any)})).toThrow(PostedVoucherMutationError);expect(()=>assertPostedVoucherImmutable({...({status:"cancelled"} as any)})).not.toThrow();});
  it("reverses once, balances the opposite entry, preserves cancellation and rejects a second reversal",async()=>{const r=new InMemoryAccountingRepository();seed(r);const original=await r.runInTransaction(tx=>postVoucher(tx,voucherInput(),{ids:testIds(),clock:fixedClock()}));const reversal=await r.runInTransaction(tx=>reverseVoucher(tx,original.voucher.id,"user-2",{ids:testIds("rev"),clock:fixedClock()}));expect(reversal.lines[0].debit).toBe(original.lines[0].credit);expect(reversal.lines[0].credit).toBe(original.lines[0].debit);expect((await r.getVoucher(original.voucher.id))!.status).toBe("cancelled");await expect(r.runInTransaction(tx=>reverseVoucher(tx,original.voucher.id,"user-2",{ids:testIds("rev2"),clock:fixedClock()}))).rejects.toThrow(/already been reversed|cancelled/);expect(r.vouchers.size).toBe(2);});
  it("serializes concurrent sequence allocation without duplicate numbers",async()=>{const r=new InMemoryAccountingRepository();const values=await Promise.all(Array.from({length:25},()=>r.runInTransaction(tx=>tx.allocateVoucherNumber({businessId:"biz-1",financialYearId:fy.id,voucherType:"JOURNAL"}))));expect(new Set(values).size).toBe(25);expect(values).toContain("JOURNAL-000001");expect(values).toContain("JOURNAL-000025");});
  it("enforces authorization outside the UI",()=>{expect(()=>assertAuthorized({userId:"u",businessId:"biz-1",permissions:[]},"SALE_CREATE")).toThrow(AuthorizationError);expect(()=>assertAuthorized({userId:"u",businessId:"biz-1",permissions:["SALE_CREATE"]},"SALE_CREATE")).not.toThrow();});
  it("rejects an account carrying both opening debit and credit",async()=>{const r=new InMemoryAccountingRepository();const bad={...account("bad","asset"),openingDebit:100,openingCredit:100};await expect(r.runInTransaction(tx=>tx.saveAccount(bad))).rejects.toThrow();});
});
