import { describe, expect, it } from "vitest";
import { InMemoryAccountingRepository, fixedClock, testIds } from "../inMemoryRepository";
import { postExpenseEntry } from "../expenseEntry";
import type { Account, FinancialYear } from "../types";

const fy:FinancialYear={id:"fy-2026-27",businessId:"biz-1",name:"FY 2026-27",startDate:"2026-04-01",endDate:"2027-03-31",locked:false};
const account=(id:string,type:Account["type"]):Account=>({id,businessId:"biz-1",code:id,name:id,type,parentId:null,systemAccount:true,active:true,openingDebit:0,openingCredit:0,createdAt:"2026-04-01T00:00:00.000Z",updatedAt:"2026-04-01T00:00:00.000Z"});
function seed(){const r=new InMemoryAccountingRepository();r.financialYears.set(fy.id,fy);for(const [id,type] of [["expense","expense"],["cash","asset"],["bank","asset"],["payable","liability"],["cgst","asset"],["sgst","asset"]] as const)r.accounts.set(id,account(id,type));return r;}

describe("expense engine production hardening",()=>{
 it("posts cash expense as Dr Expense / Cr Cash",async()=>{const r=seed();const result=await postExpenseEntry(r,{businessId:"biz-1",financialYearId:fy.id,date:"2026-09-01",userId:"u1",expenseAccountId:"expense",amount:1000,mode:"cash",cashAccountId:"cash",documentId:"ex-1",idempotencyKey:"expense-key-0001"},{ids:testIds(),clock:fixedClock()});expect(result.voucher.totalDebit).toBe(1000);expect(result.voucher.totalCredit).toBe(1000);expect(result.lines.find(x=>x.accountId==="expense")?.debit).toBe(1000);expect(result.lines.find(x=>x.accountId==="cash")?.credit).toBe(1000);});
 it("posts credit expense to a liability account",async()=>{const r=seed();const result=await postExpenseEntry(r,{businessId:"biz-1",financialYearId:fy.id,date:"2026-09-01",userId:"u1",expenseAccountId:"expense",amount:1000,mode:"credit",payableAccountId:"payable",documentId:"ex-2",idempotencyKey:"expense-key-0002"},{ids:testIds(),clock:fixedClock()});expect(result.lines.find(x=>x.accountId==="payable")?.credit).toBe(1000);});
 it("posts input GST through the authoritative tax engine",async()=>{const r=seed();const result=await postExpenseEntry(r,{businessId:"biz-1",financialYearId:fy.id,date:"2026-09-01",userId:"u1",expenseAccountId:"expense",amount:10000,mode:"cash",cashAccountId:"cash",documentId:"ex-3",idempotencyKey:"expense-key-0003",tax:{rate:18,intraState:true},taxAccounts:{inputCgst:"cgst",inputSgst:"sgst"}},{ids:testIds(),clock:fixedClock()});expect(result.voucher.totalDebit).toBe(11800);expect(result.voucher.totalCredit).toBe(11800);expect(result.lines.find(x=>x.accountId==="cgst")?.debit).toBe(900);expect(result.lines.find(x=>x.accountId==="sgst")?.debit).toBe(900);});
 it("returns the same voucher on an identical idempotent retry",async()=>{const r=seed();const input={businessId:"biz-1",financialYearId:fy.id,date:"2026-09-01",userId:"u1",expenseAccountId:"expense",amount:1000,mode:"cash" as const,cashAccountId:"cash",documentId:"ex-4",idempotencyKey:"expense-key-0004"};const first=await postExpenseEntry(r,input,{ids:testIds(),clock:fixedClock()});const second=await postExpenseEntry(r,input,{ids:testIds("other"),clock:fixedClock()});expect(second.voucher.id).toBe(first.voucher.id);expect(r.vouchers.size).toBe(1);});
 it("rejects the same idempotency key for a different expense",async()=>{const r=seed();const input={businessId:"biz-1",financialYearId:fy.id,date:"2026-09-01",userId:"u1",expenseAccountId:"expense",amount:1000,mode:"cash" as const,cashAccountId:"cash",documentId:"ex-5",idempotencyKey:"expense-key-0005"};await postExpenseEntry(r,input,{ids:testIds(),clock:fixedClock()});await expect(postExpenseEntry(r,{...input,amount:1100,documentId:"ex-6"},{ids:testIds("other"),clock:fixedClock()})).rejects.toThrow(/different accounting payload/);});
 it("rejects inactive settlement and locked financial year",async()=>{const r=seed();r.accounts.get("cash")!.active=false;await expect(postExpenseEntry(r,{businessId:"biz-1",financialYearId:fy.id,date:"2026-09-01",userId:"u1",expenseAccountId:"expense",amount:1000,mode:"cash",cashAccountId:"cash",documentId:"ex-7",idempotencyKey:"expense-key-0007"},{ids:testIds(),clock:fixedClock()})).rejects.toThrow(/inactive/);r.accounts.get("cash")!.active=true;r.financialYears.set(fy.id,{...fy,locked:true});await expect(postExpenseEntry(r,{businessId:"biz-1",financialYearId:fy.id,date:"2026-09-01",userId:"u1",expenseAccountId:"expense",amount:1000,mode:"cash",cashAccountId:"cash",documentId:"ex-8",idempotencyKey:"expense-key-0008"},{ids:testIds(),clock:fixedClock()})).rejects.toThrow(/locked/);});
});
