import { describe, expect, it } from "vitest";
import { buildPartyReconciliation, allocateAgainstOutstanding } from "../party";
import { normalizePartyInput } from "../partyMaster";
import type { LedgerEntry, PartyAllocation } from "../types";
const entry=(voucherId:string,date:string,debit:number,credit:number,voucherType="SALE"):LedgerEntry=>({lineId:`l-${voucherId}`,voucherId,businessId:"b1",financialYearId:"fy1",accountId:"acct-debtors",partyId:"p1",description:voucherType,debit,credit,lineNo:1,date,voucherType,voucherNumber:voucherId,dueDate:date,createdAt:`${date}T00:00:00.000Z`});
const allocation=(fromVoucherId:string,toVoucherId:string,amount:number):PartyAllocation=>({id:`a-${fromVoucherId}-${toVoucherId}`,businessId:"b1",partyId:"p1",fromVoucherId,toVoucherId,amount,date:"2026-05-01",createdBy:"u1",createdAt:"2026-05-01T00:00:00.000Z",idempotencyKey:`key-${fromVoucherId}-${toVoucherId}`});
describe("party engine hardening",()=>{
 it("supports customer opening balance without an editable balance field",()=>{const p=normalizePartyInput({businessId:"b1",partyCode:"CUS-001",name:"Customer",ledgerAccountId:"acct-debtors",phone:"",email:"",address:{line1:"",city:"Khagaria",state:"Bihar",pincode:"851204",country:"India"},openingBalance:10000,openingBalanceType:"debit",creditLimit:50000,status:"active"},"customer");expect(p.openingBalance).toBe(10000);expect("currentBalance" in p).toBe(false);});
 it("supports a dual-role party with separate receivable/payable accounts",()=>{const p=normalizePartyInput({businessId:"b1",partyCode:"PTY-001",name:"Dual",receivableLedgerAccountId:"acct-debtors",payableLedgerAccountId:"acct-creditors",address:{line1:"",city:"Khagaria",state:"Bihar",pincode:"851204",country:"India"}},"both");expect(p.kind).toBe("both");expect(p.receivableLedgerAccountId).toBe("acct-debtors");expect(p.payableLedgerAccountId).toBe("acct-creditors");});
 it("reconciles a credit sale and partial receipt allocation",()=>{const entries=[entry("sale1","2026-04-01",10000,0),entry("receipt1","2026-04-10",0,4000,"RECEIPT")];const r=buildPartyReconciliation(entries,[allocation("receipt1","sale1",4000)],"p1","customer");expect(r.ledgerNet).toBe(6000);expect(r.billOutstanding).toBe(6000);expect(r.advance).toBe(0);expect(r.reconciled).toBe(true);});
 it("keeps unallocated receipt as advance",()=>{const entries=[entry("sale1","2026-04-01",10000,0),entry("receipt1","2026-04-10",0,12000,"RECEIPT")];const r=buildPartyReconciliation(entries,[allocation("receipt1","sale1",10000)],"p1","customer");expect(r.billOutstanding).toBe(0);expect(r.advance).toBe(2000);expect(r.reconciled).toBe(true);});
 it("supports a cash sale with no party activity",()=>{const r=buildPartyReconciliation([],[],"p1","customer");expect(r.ledgerNet).toBe(0);expect(r.billOutstanding).toBe(0);expect(r.reconciled).toBe(true);});
 it("supports supplier direction",()=>{const entries=[entry("purchase1","2026-04-01",0,15000,"PURCHASE"),entry("payment1","2026-04-10",15000,0,"PAYMENT")];const r=buildPartyReconciliation(entries,[allocation("payment1","purchase1",10000)],"p1","supplier");expect(r.ledgerNet).toBe(-15000);expect(r.billOutstanding).toBe(5000);expect(r.advance).toBe(0);expect(r.reconciled).toBe(true);});
 it("prevents allocation beyond a bill and reports remainder",()=>{const result=allocateAgainstOutstanding(12000,[{voucherId:"v1",voucherNumber:"S-1",date:"2026-04-01",original:10000,allocated:0,outstanding:10000}]);expect(result.allocations).toEqual([{voucherId:"v1",amount:10000}]);expect(result.unallocated).toBe(2000);});
});
