import { describe, expect, it } from "vitest";
import { InMemoryAccountingRepository, fixedClock, testIds } from "../inMemoryRepository";
import { postSaleEntry } from "../saleEntry";
import { postPurchase } from "../transactions";
import { postExpenseEntry } from "../expenseEntry";
import { cancelSalesDocument, cancelPurchaseDocument } from "../documentCancellation";
import type { Account, FinancialYear, StockMovement } from "../types";

const B="biz-qa", U="qa-user", FY="fy-2026-27", D="2026-08-30", NOW="2026-08-30T12:00:00.000Z";
const fy:FinancialYear={id:FY,businessId:B,name:"FY 2026-27",startDate:"2026-04-01",endDate:"2027-03-31",locked:false};
const account=(id:string,type:Account["type"]):Account=>({id,businessId:B,code:id,name:id,type,parentId:null,systemAccount:true,active:true,openingDebit:0,openingCredit:0,createdAt:NOW,updatedAt:NOW});
const deps={ids:testIds("qa"),clock:fixedClock(NOW)};
const saleMap={party:"receivable",sales:"sales",cash:"cash",bank:"bank",outputCgst:"out-cgst",outputSgst:"out-sgst",outputIgst:"out-igst",outputCess:"out-cess",inventory:"inventory",cogs:"cogs"};
const purchaseMap={party:"payable",cash:"cash",bank:"bank",inputCgst:"in-cgst",inputSgst:"in-sgst",inputIgst:"in-igst",inputCess:"in-cess",inventory:"inventory",cogs:"cogs"};
function seed(r:InMemoryAccountingRepository){r.financialYears.set(FY,fy);for(const [id,type] of [["cash","asset"],["bank","asset"],["inventory","asset"],["sales","income"],["cogs","expense"],["expense","expense"],["receivable","asset"],["payable","liability"],["out-cgst","liability"],["out-sgst","liability"],["out-igst","liability"],["out-cess","liability"],["in-cgst","asset"],["in-sgst","asset"],["in-igst","asset"],["in-cess","asset"]] as const)r.accounts.set(id,account(id,type));r.businessDocuments.set("parties/customer-1",{businessId:B,kind:"customer",status:"active",ledgerAccountId:"receivable"});r.businessDocuments.set("parties/supplier-1",{businessId:B,kind:"supplier",status:"active",ledgerAccountId:"payable"});}
function seedStock(r:InMemoryAccountingRepository,q=20){const m:StockMovement={id:"opening",businessId:B,financialYearId:FY,date:"2026-04-01",itemId:"item-1",warehouseId:"godown-1",direction:"in",quantity:q,unitCost:500,value:q*500,sourceType:"opening",createdBy:U,createdAt:NOW,sourceId:"opening"};r.stockMovements.set(m.id,m);}
function stockNet(r:InMemoryAccountingRepository){return [...r.stockMovements.values()].filter(m=>m.businessId===B&&m.financialYearId===FY&&m.itemId==="item-1").reduce((n,m)=>n+(m.direction==="in"?m.quantity:-m.quantity),0);}
function balanced(r:InMemoryAccountingRepository){for(const v of r.vouchers.values())expect(v.totalDebit).toBe(v.totalCredit);}

describe("BUSY SOFT production workflow QA",()=>{
 it("Sale integrates invoice→inventory→accounting→party→GST→payment→outstanding",async()=>{const r=new InMemoryAccountingRepository();seed(r);seedStock(r);const x=await postSaleEntry(r,{businessId:B,financialYearId:FY,userId:U,date:D,customerId:"customer-1",grossValue:10000,taxRate:18,intraState:true,paymentMode:"cash",paidAmount:5000,accountMap:saleMap,itemMovements:[{itemId:"item-1",quantity:5,warehouseId:"godown-1"}],idempotencyKey:"qa-sale-flow-000001",documentId:"sale-1"},deps);expect(x.voucher.voucherType).toBe("SALE");expect(stockNet(r)).toBe(15);const d=r.businessDocuments.get("sales/sale-1")!;expect(d.total).toBe(11800);expect(d.paidAmount).toBe(5000);expect(d.outstandingAmount).toBe(6800);expect([...r.ledgerEntries.values()].some(e=>e.accountId==="out-cgst")).toBe(true);balanced(r);});
 it("Sale duplicate click/network retry creates no second invoice or stock movement",async()=>{const r=new InMemoryAccountingRepository();seed(r);seedStock(r);const x={businessId:B,financialYearId:FY,userId:U,date:D,customerId:"customer-1",grossValue:10000,taxRate:18,intraState:true,paymentMode:"cash" as const,paidAmount:11800,accountMap:saleMap,itemMovements:[{itemId:"item-1",quantity:2,warehouseId:"godown-1"}],idempotencyKey:"qa-sale-retry-000001",documentId:"sale-retry"};await postSaleEntry(r,x,deps);const n={v:r.vouchers.size,m:r.stockMovements.size};await expect(postSaleEntry(r,x,deps)).rejects.toThrow(/already been posted|already exists/);expect(r.vouchers.size).toBe(n.v);expect(r.stockMovements.size).toBe(n.m);});
 it("Sale rejects invalid party, inactive account, wrong FY, locked period and insufficient stock",async()=>{const r=new InMemoryAccountingRepository();seed(r);seedStock(r,2);const x={businessId:B,financialYearId:FY,userId:U,date:D,customerId:"customer-1",grossValue:10000,taxRate:18,intraState:true,paymentMode:"cash" as const,paidAmount:11800,accountMap:saleMap,itemMovements:[{itemId:"item-1",quantity:1,warehouseId:"godown-1"}],idempotencyKey:"qa-sale-fail-000001",documentId:"sale-fail"};await expect(postSaleEntry(r,{...x,customerId:"missing"},deps)).rejects.toThrow(/does not exist/);r.accounts.get("cash")!.active=false;await expect(postSaleEntry(r,{...x,idempotencyKey:"qa-sale-fail-000002"},deps)).rejects.toThrow(/inactive/);r.accounts.get("cash")!.active=true;await expect(postSaleEntry(r,{...x,financialYearId:"wrong-fy",idempotencyKey:"qa-sale-fail-000003"},deps)).rejects.toThrow(/financial year|Financial year/);r.financialYears.set(FY,{...fy,locked:true});await expect(postSaleEntry(r,{...x,idempotencyKey:"qa-sale-fail-000004"},deps)).rejects.toThrow(/locked/);r.financialYears.set(FY,fy);await expect(postSaleEntry(r,{...x,itemMovements:[{itemId:"item-1",quantity:3,warehouseId:"godown-1"}],idempotencyKey:"qa-sale-fail-000005"},deps)).rejects.toThrow();});
 it("Purchase integrates inventory→accounting→supplier→GST→payment→outstanding and blocks duplicate supplier invoice",async()=>{const r=new InMemoryAccountingRepository();seed(r);const x={businessId:B,financialYearId:FY,userId:U,date:D,supplierId:"supplier-1",taxableValue:10000,grossValue:10000,taxRate:18,intraState:true,mode:"cash" as const,paidAmount:11800,supplierInvoiceNumber:"SUP-001",accountMap:purchaseMap,itemMovements:[{itemId:"item-1",quantity:20,unitCost:500,warehouseId:"godown-1"}],idempotencyKey:"qa-purchase-000001",documentId:"purchase-1"};const p=await postPurchase(r,x,deps);expect(p.voucher.voucherType).toBe("PURCHASE");expect(stockNet(r)).toBe(20);expect(p.voucher.totalDebit).toBe(p.voucher.totalCredit);expect(r.businessDocuments.has("purchaseSupplierInvoices/supplier-1:SUP-001")).toBe(true);await expect(postPurchase(r,{...x,idempotencyKey:"qa-purchase-000002",documentId:"purchase-2"},deps)).rejects.toThrow(/already recorded/);balanced(r);});
 it("Purchase cancellation refuses when later consumption would make stock negative",async()=>{const r=new InMemoryAccountingRepository();seed(r);const p=await postPurchase(r,{businessId:B,financialYearId:FY,userId:U,date:D,supplierId:"supplier-1",taxableValue:10000,grossValue:10000,taxRate:18,intraState:true,mode:"credit",supplierInvoiceNumber:"SUP-002",accountMap:purchaseMap,itemMovements:[{itemId:"item-1",quantity:20,unitCost:500,warehouseId:"godown-1"}],idempotencyKey:"qa-purchase-000003",documentId:"purchase-3"},deps);r.stockMovements.set("later",{id:"later",businessId:B,financialYearId:FY,date:D,itemId:"item-1",warehouseId:"godown-1",direction:"out",quantity:20,unitCost:500,value:10000,sourceType:"sale",createdBy:U,createdAt:NOW,sourceId:"later-sale"});await expect(cancelPurchaseDocument(r,{businessId:B,voucherId:p.voucher.id,userId:U,idempotencyKey:"qa-purchase-cancel-0001"},deps)).rejects.toThrow(/only .* units available/);});
 it("Expense integrates cash/bank→accounting→P&L",async()=>{const r=new InMemoryAccountingRepository();seed(r);const x=await postExpenseEntry(r,{businessId:B,financialYearId:FY,userId:U,date:D,expenseAccountId:"expense",amount:2500,mode:"cash",cashAccountId:"cash",idempotencyKey:"qa-expense-000001",documentId:"expense-1"},deps);expect(x.voucher.totalDebit).toBe(2500);expect(x.voucher.totalCredit).toBe(2500);expect([...r.ledgerEntries.values()].some(e=>e.accountId==="expense"&&e.debit===2500)).toBe(true);expect([...r.ledgerEntries.values()].some(e=>e.accountId==="cash"&&e.credit===2500)).toBe(true);expect(r.auditLogs.size).toBe(1);});
 it("Sale create→post→reverse restores stock and preserves cancellation history",async()=>{const r=new InMemoryAccountingRepository();seed(r);seedStock(r);const s=await postSaleEntry(r,{businessId:B,financialYearId:FY,userId:U,date:D,grossValue:10000,taxRate:18,intraState:true,paymentMode:"cash",paidAmount:11800,accountMap:saleMap,itemMovements:[{itemId:"item-1",quantity:5,warehouseId:"godown-1"}],idempotencyKey:"qa-sale-reverse-000001",documentId:"sale-reverse"},deps);await cancelSalesDocument(r,{businessId:B,voucherId:s.voucher.id,userId:U,date:D,idempotencyKey:"qa-sale-reverse-000002"},deps);expect((await r.getVoucher(s.voucher.id))?.status).toBe("cancelled");expect(stockNet(r)).toBe(20);expect(r.vouchers.size).toBe(2);expect(r.businessDocuments.has("saleCancellations/sale-reverse")).toBe(true);balanced(r);await expect(cancelSalesDocument(r,{businessId:B,voucherId:s.voucher.id,userId:U,idempotencyKey:"qa-sale-reverse-000003"},deps)).rejects.toThrow(/posted sale/);});
 it("Concurrent numbering is unique and failed transaction rolls back all state",async()=>{const r=new InMemoryAccountingRepository();seed(r);const nums=await Promise.all(Array.from({length:50},()=>r.runInTransaction(tx=>tx.allocateVoucherNumber({businessId:B,financialYearId:FY,voucherType:"SALE",prefix:"SI"}))));expect(new Set(nums).size).toBe(50);await expect(r.runInTransaction(async tx=>{await tx.saveBusinessDocument("sales","rollback",{businessId:B});await tx.saveAuditEvent({id:"rollback",businessId:B,entityType:"sale",entityId:"rollback",action:"CREATE",userId:U,timestamp:NOW});throw new Error("simulated timeout");})).rejects.toThrow("simulated timeout");expect(r.businessDocuments.has("sales/rollback")).toBe(false);expect(r.auditLogs.has("rollback")).toBe(false);});
});
