import { describe, expect, it } from "vitest";
import { buildDayBook, buildJournalRegister, buildSalesRegister, buildPurchaseRegister, buildLedger, buildCashBook, buildBankBook, reconcileStockSummary } from "../reportingEngine";
import { buildProfitLoss, buildBalanceSheet, buildTrialBalance } from "../reports";
import type { Account, LedgerEntry, StockMovement, Voucher } from "../types";

const account=(id:string,type:Account["type"]):Account=>({id,businessId:"biz-1",code:id,name:id,type,parentId:null,systemAccount:true,active:true,openingDebit:0,openingCredit:0,createdAt:"2026-04-01T00:00:00.000Z",updatedAt:"2026-04-01T00:00:00.000Z"});
const voucher=(id:string,type:string,status:Voucher["status"]="posted"):Voucher=>({id,businessId:"biz-1",financialYearId:"fy-2026-27",voucherType:type,voucherNumber:id,date:"2026-08-01",status,totalDebit:1000,totalCredit:1000,createdBy:"u",createdAt:"2026-08-01T00:00:00.000Z",updatedAt:"2026-08-01T00:00:00.000Z"});
const line=(id:string,voucherId:string,accountId:string,debit:number,credit:number,lineNo:number):LedgerEntry=>({lineId:id,voucherId,accountId,debit,credit,businessId:"biz-1",lineNo,financialYearId:"fy-2026-27",date:"2026-08-01",voucherType:"SALE",voucherNumber:voucherId,createdAt:"2026-08-01T00:00:00.000Z"});

describe("reporting engine hardening",()=>{
 it("keeps P&L and balance sheet derived from ledger",()=>{const accounts=[account("cash","asset"),account("sales","income"),account("expense","expense"),account("capital","equity")];const entries=[line("1","s","cash",1000,0,1),line("2","s","sales",0,1000,2),line("3","e","expense",200,0,1),line("4","e","cash",0,200,2)];const pl=buildProfitLoss(accounts,entries,{fromDate:"2026-08-01",toDate:"2026-08-31"});expect(pl.income).toBe(1000);expect(pl.expense).toBe(200);expect(pl.profit).toBe(800);const tb=buildTrialBalance(accounts,entries);expect(tb.balanced).toBe(true);const bs=buildBalanceSheet(accounts,entries,{toDate:"2026-08-31"});expect(bs.balanced).toBe(true);});
 it("shows cancelled vouchers in audit-visible registers instead of hiding them",()=>{const rows=buildDayBook([voucher("v1","SALE"),voucher("v2","SALE","cancelled")]);expect(rows).toHaveLength(2);expect(rows[1].status).toBe("cancelled");});
 it("keeps specialized registers sourced from voucher types",()=>{const vs=[voucher("j","JOURNAL"),voucher("s","SALE"),voucher("p","PURCHASE")];expect(buildJournalRegister(vs)).toHaveLength(1);expect(buildSalesRegister(vs)).toHaveLength(1);expect(buildPurchaseRegister(vs)).toHaveLength(1);});
 it("filters ledger, cash book and bank book from ledger entries only",()=>{const entries=[line("1","v","cash",100,0,1),line("2","v","bank",0,100,2)];expect(buildLedger(entries,"cash")).toHaveLength(1);expect(buildCashBook(entries,["cash"])).toHaveLength(1);expect(buildBankBook(entries,["bank"])).toHaveLength(1);});
 it("reconciles stock summary with the stock ledger",()=>{const movements:StockMovement[]=[{id:"m1",businessId:"biz-1",financialYearId:"fy-2026-27",date:"2026-04-01",itemId:"item-1",warehouseId:"default",direction:"in",quantity:10,unitCost:100,value:1000,sourceType:"opening",sourceId:"open",createdBy:"u",createdAt:"2026-04-01T00:00:00.000Z"},{id:"m2",businessId:"biz-1",financialYearId:"fy-2026-27",date:"2026-04-02",itemId:"item-1",warehouseId:"default",direction:"out",quantity:3,unitCost:100,value:300,sourceType:"sale",sourceId:"sale-1",createdBy:"u",createdAt:"2026-04-02T00:00:00.000Z"}];const r=reconcileStockSummary(movements,{businessId:"biz-1",financialYearId:"fy-2026-27",itemId:"item-1",warehouseId:"default"});expect(r.balance.quantity).toBe(7);expect(r.balance.value).toBe(700);expect(r.reconciled).toBe(true);});
});
