import { NextResponse } from "next/server";
import type { Firestore } from "firebase-admin/firestore";
import { getAdminServices } from "@/infrastructure/firebase/admin";
import type { BusinessMember } from "@/types";
export const runtime="nodejs";
const err=(message:string,status=400)=>NextResponse.json({success:false,error:message},{status});
async function auth(request:Request){const{auth,db}=getAdminServices();const h=request.headers.get("authorization")||"";if(!h.startsWith("Bearer "))throw new Error("Authentication is required.");return{db,token:await auth.verifyIdToken(h.slice(7))};}
async function member(db:Firestore,businessId:string,uid:string){const s=await db.collection("businesses").doc(businessId).collection("members").doc(uid).get();if(!s.exists)throw Object.assign(new Error("You are not a member of this business."),{statusCode:403});const m=s.data() as BusinessMember;if(m.status!=="active")throw Object.assign(new Error("Your business membership is not active."),{statusCode:403});return m;}
const text=(v:unknown)=>String(v??"").trim();
export async function GET(request:Request){try{const{db,token}=await auth(request);const u=new URL(request.url),businessId=text(u.searchParams.get("businessId"));if(!businessId)return err("Business ID is required.");const m=await member(db,businessId,token.uid);if(m.role!=="owner"&&m.role!=="admin"&&!m.permissions?.items?.view)return err("Permission denied: item view.",403);const base=db.collection("businesses").doc(businessId);const[type]=[text(u.searchParams.get("type"))];if(!["categories","units","warehouses"].includes(type))return err("Master type must be categories, units or warehouses.");const snap=await base.collection(type).get();return NextResponse.json({success:true,items:snap.docs.map(d=>({id:d.id,...d.data()}))});}catch(e){return err(e instanceof Error?e.message:"Could not load item masters.",(e as{statusCode?:number}).statusCode||400);}}
export async function POST(request:Request){try{const{db,token}=await auth(request);const body=await request.json() as Record<string,unknown>,businessId=text(body.businessId),type=text(body.type);if(!businessId||!["categories","units","warehouses"].includes(type))return err("Business ID and valid master type are required.");const m=await member(db,businessId,token.uid);if(m.role!=="owner"&&m.role!=="admin"&&!m.permissions?.items?.create)return err("Permission denied: item master creation.",403);const name=text(body.name),shortName=text(body.shortName);if(!name)return err("Name is required.");if(type==="units"&&!shortName)return err("Unit short name is required.");const ref=db.collection("businesses").doc(businessId).collection(type).doc(),now=new Date().toISOString();const record=type==="units"?{businessId,name,shortName,status:"Active",createdAt:now,updatedAt:now}:type==="warehouses"?{businessId,name,address:text(body.address),status:"Active",isDefault:Boolean(body.isDefault),createdAt:now,updatedAt:now}:{businessId,name,description:text(body.description),status:"Active",createdAt:now,updatedAt:now};await db.runTransaction(async tx=>{const dup=await tx.get(db.collection("businesses").doc(businessId).collection(type).where(type==="units"?"shortName":"name","==",type==="units"?shortName:name).limit(1));if(!dup.empty)throw new Error(`${type.slice(0,-1)} already exists.`);tx.set(ref,record);});return NextResponse.json({success:true,item:{id:ref.id,...record}});}catch(e){return err(e instanceof Error?e.message:"Could not create item master.",(e as{statusCode?:number}).statusCode||400);}}
export async function PATCH(request:Request){try{const{db,token}=await auth(request);const body=await request.json() as Record<string,unknown>,businessId=text(body.businessId),type=text(body.type),id=text(body.id);if(!businessId||!id||!["categories","units","warehouses"].includes(type))return err("Business ID, ID and valid master type are required.");const m=await member(db,businessId,token.uid);if(m.role!=="owner"&&m.role!=="admin"&&!m.permissions?.items?.edit)return err("Permission denied: item master edit.",403);const ref=db.collection("businesses").doc(businessId).collection(type).doc(id);const current=await ref.get();if(!current.exists)return err("Master record not found.",404);const patch={...body};delete (patch as Record<string,unknown>).businessId;delete (patch as Record<string,unknown>).type;delete (patch as Record<string,unknown>).id;delete (patch as Record<string,unknown>).createdAt;patch.updatedAt=new Date().toISOString();await ref.set(patch,{merge:true});return NextResponse.json({success:true});}catch(e){return err(e instanceof Error?e.message:"Could not update item master.",(e as{statusCode?:number}).statusCode||400);}}
