"use client";

import { useEffect, useMemo, useState } from "react";
import Link from "next/link";
import Sidebar from "../Components/Sidebar/page";
import TopNav from "../Components/TopNav/page";
import AuthGate from "../Components/Auth/AuthGate";
import { auth } from "../../lib/firebase";
import { useBusiness } from "../../context/BusinessContext";

type Account={id:string;code?:string;name:string;type:string;active?:boolean};
type Bom={itemId:string;quantity:number;unitCost?:number;scrapPercent?:number};
type Config={enabled?:boolean;bom?:Bom[];batchQuantity?:number;wastagePercent?:number;costComponents?:{type:string;name:string;amount:number}[];finishedGoodsAccountId?:string;wipAccountId?:string;manufacturingOverheadAccountId?:string};
type Item={id:string;name:string;code:string;unit?:string;manufacturing?:Config};
type Production={id:string;voucherNumber:string;date:string;itemName:string;quantity:number;unitCost:number;totalCost:number;status:string;reversalVoucherId?:string};
const money=(n:number)=>new Intl.NumberFormat("en-IN",{style:"currency",currency:"INR"}).format((n||0)/100);
const getToken=async()=>{if(!auth.currentUser)throw new Error("Please sign in again.");return auth.currentUser.getIdToken();};

export default function ProductionPage(){
 const{activeBusinessId,businessName,loading}=useBusiness();
 const[items,setItems]=useState<Item[]>([]);const[accounts,setAccounts]=useState<Account[]>([]);const[productions,setProductions]=useState<Production[]>([]);
 const[selected,setSelected]=useState("");const[qty,setQty]=useState("1");const[fy,setFy]=useState("");const[material,setMaterial]=useState("");const[finished,setFinished]=useState("");const[wip,setWip]=useState("");const[warehouse,setWarehouse]=useState("");const[date,setDate]=useState(new Date().toISOString().slice(0,10));const[message,setMessage]=useState("");const[saving,setSaving]=useState(false);const[cancelling,setCancelling]=useState("");
 const load=async()=>{if(!activeBusinessId)return;try{setMessage("");const t=await getToken();const headers={Authorization:`Bearer ${t}`};const[r,a,p]=await Promise.all([fetch(`/api/items?businessId=${encodeURIComponent(activeBusinessId)}`,{headers,cache:"no-store"}),fetch(`/api/accounting/accounts?businessId=${encodeURIComponent(activeBusinessId)}&type=asset`,{headers,cache:"no-store"}),fetch(`/api/production?businessId=${encodeURIComponent(activeBusinessId)}`,{headers,cache:"no-store`})]);const rd=await r.json(),ad=await a.json(),pd=await p.json();if(!r.ok)throw new Error(rd.error);if(!a.ok)throw new Error(ad.error);if(!p.ok)throw new Error(pd.error);setItems(rd.items||[]);setAccounts(ad.accounts||[]);setFy(pd.financialYearId||"");setProductions(pd.productions||[]);}catch(e){setMessage(e instanceof Error?e.message:"Unable to load production workspace.");}};
 useEffect(()=>{if(!loading)void load();},[activeBusinessId,loading]);
 const manufactured=useMemo(()=>items.filter(i=>i.manufacturing?.enabled),[items]);const item=items.find(i=>i.id===selected);const config=item?.manufacturing;const rows=(config?.bom||[]).map(c=>({...c,name:items.find(i=>i.id===c.itemId)?.name||c.itemId,code:items.find(i=>i.id===c.itemId)?.code||""}));
 useEffect(()=>{if(!item)return;setFinished(item.manufacturing?.finishedGoodsAccountId||"");setWip(item.manufacturing?.wipAccountId||item.manufacturing?.manufacturingOverheadAccountId||"");},[selected,item]);
 const batchOutput=(Number(config?.batchQuantity)||0)*(1-Number(config?.wastagePercent||0)/100);const factor=batchOutput>0?(Number(qty)||0)/batchOutput:0;const materialCost=rows.reduce((s,r)=>s+Number(r.unitCost||0)*Number(r.quantity||0)*factor*(1+Number(r.scrapPercent||0)/100),0);const extra=(config?.costComponents||[]).reduce((s,c)=>s+Number(c.amount||0),0)*factor;const total=Math.round(materialCost+extra);const unitCost=Number(qty)>0?Math.round(total/Number(qty)):0;
 const post=async()=>{setSaving(true);setMessage("");try{if(!activeBusinessId||!selected||!fy)throw new Error("Select a manufactured item and active financial year.");if(!material||!finished)throw new Error("Select the raw-material and finished-goods inventory accounts.");const t=await getToken();const r=await fetch("/api/production",{method:"POST",headers:{"Content-Type":"application/json",Authorization:`Bearer ${t}`},body:JSON.stringify({businessId:activeBusinessId,itemId:selected,financialYearId:fy,quantity:Number(qty),date,warehouseId:warehouse||undefined,materialInventoryAccountId:material,finishedGoodsAccountId:finished,wipAccountId:wip||undefined,idempotencyKey:`production-${crypto.randomUUID()}`})});const d=await r.json();if(!r.ok)throw new Error(d.error||"Production failed.");setMessage(`Production ${d.result?.voucher?.voucherNumber||""} posted successfully at ${money(d.result?.voucher?.totalDebit||0)}.`);await load();}catch(e){setMessage(e instanceof Error?e.message:"Production failed.");}finally{setSaving(false);}};
 const cancel=async(id:string)=>{if(!confirm("Cancel this production voucher? This creates a reversal voucher and reverses its stock movements."))return;setCancelling(id);setMessage("");try{const t=await getToken();const r=await fetch("/api/production",{method:"POST",headers:{"Content-Type":"application/json",Authorization:`Bearer ${t}`},body:JSON.stringify({businessId:activeBusinessId,action:"cancel",productionId:id})});const d=await r.json();if(!r.ok)throw new Error(d.error||"Cancellation failed.");setMessage(`Production cancelled. Reversal voucher ${d.result?.voucher?.voucherNumber||""} created.`);await load();}catch(e){setMessage(e instanceof Error?e.message:"Cancellation failed.");}finally{setCancelling("");}};
 return <AuthGate><div className="flex min-h-screen bg-slate-50"><Sidebar/><main className="min-w-0 flex-1 px-4 pb-10 sm:px-8"><TopNav/><div className="mx-auto max-w-[1450px] py-6">
  <div className="flex flex-wrap items-start justify-between gap-4"><div><p className="text-sm font-semibold text-indigo-600">{businessName||"Business"} · Manufacturing</p><h1 className="text-3xl font-bold text-slate-900">Production</h1><p className="mt-1 text-sm text-slate-500">Convert raw materials and manufacturing overhead into accurately valued finished stock.</p></div><Link href="/items/manufacturing" className="rounded-xl border bg-white px-4 py-2.5 text-sm font-semibold">BOM / Manufacturing Setup →</Link></div>
  {message&&<div className="mt-5 rounded-xl border border-slate-200 bg-white p-3 text-sm text-slate-700">{message}</div>}
  <div className="mt-6 grid gap-5 lg:grid-cols-[1.15fr_.85fr]">
   <section className="rounded-2xl border bg-white p-6"><div className="flex items-center justify-between"><h2 className="font-bold">Production Entry</h2><span className="rounded-full bg-slate-100 px-3 py-1 text-xs text-slate-600">FY {fy.replace(/^fy-/,'')}</span></div><div className="mt-5 grid gap-4 sm:grid-cols-2">
    <label className="text-sm font-medium">Finished Item<select value={selected} onChange={e=>setSelected(e.target.value)} className="mt-1 h-11 w-full rounded-xl border px-3"><option value="">Select manufactured item</option>{manufactured.map(i=><option key={i.id} value={i.id}>{i.name} · {i.code}</option>)}</select></label>
    <label className="text-sm font-medium">Quantity<input type="number" min="0.0001" step="0.0001" value={qty} onChange={e=>setQty(e.target.value)} className="mt-1 h-11 w-full rounded-xl border px-3"/></label>
    <label className="text-sm font-medium">Production Date<input type="date" value={date} onChange={e=>setDate(e.target.value)} className="mt-1 h-11 w-full rounded-xl border px-3"/></label>
    <label className="text-sm font-medium">Warehouse ID<input value={warehouse} onChange={e=>setWarehouse(e.target.value)} placeholder="Optional" className="mt-1 h-11 w-full rounded-xl border px-3"/></label>
   </div>{item&&<div className="mt-6 overflow-hidden rounded-xl border"><div className="border-b bg-slate-50 px-4 py-3 font-semibold">Bill of Materials</div><table className="w-full text-sm"><thead><tr className="text-left text-slate-500"><th className="px-4 py-3">Component</th><th className="px-4 py-3">Required</th><th className="px-4 py-3">Std. Cost</th><th className="px-4 py-3 text-right">Value</th></tr></thead><tbody className="divide-y">{rows.map(r=>{const required=Number(r.quantity)*factor*(1+Number(r.scrapPercent||0)/100);return <tr key={r.itemId}><td className="px-4 py-3">{r.name}<div className="text-xs text-slate-400">{r.code}</div></td><td className="px-4 py-3">{required.toFixed(3)}</td><td className="px-4 py-3">{money(Number(r.unitCost||0))}</td><td className="px-4 py-3 text-right">{money(Math.round(required*Number(r.unitCost||0)))}</td></tr>})}</tbody></table></div>}</section>
   <section className="rounded-2xl border bg-white p-6"><h2 className="font-bold">Inventory Accounts</h2><p className="mt-1 text-xs text-slate-500">Accounts are loaded from this business's active chart of accounts. No manual IDs are required.</p><div className="mt-5 space-y-4">
    <label className="block text-sm font-medium">Raw Material Inventory<select value={material} onChange={e=>setMaterial(e.target.value)} className="mt-1 h-11 w-full rounded-xl border px-3"><option value="">Select account</option>{accounts.map(a=><option key={a.id} value={a.id}>{a.code?`${a.code} · `:""}{a.name}</option>)}</select></label>
    <label className="block text-sm font-medium">Finished Goods Inventory<select value={finished} onChange={e=>setFinished(e.target.value)} className="mt-1 h-11 w-full rounded-xl border px-3"><option value="">Select account</option>{accounts.map(a=><option key={a.id} value={a.id}>{a.code?`${a.code} · `:""}{a.name}</option>)}</select></label>
    <label className="block text-sm font-medium">WIP / Manufacturing Overhead<select value={wip} onChange={e=>setWip(e.target.value)} className="mt-1 h-11 w-full rounded-xl border px-3"><option value="">No conversion account</option>{accounts.map(a=><option key={a.id} value={a.id}>{a.code?`${a.code} · `:""}{a.name}</option>)}</select></label>
    <div className="rounded-xl bg-slate-50 p-4"><div className="flex justify-between"><span>Material cost</span><b>{money(Math.round(materialCost))}</b></div><div className="mt-2 flex justify-between"><span>Labour + overhead</span><b>{money(Math.round(extra))}</b></div><div className="mt-3 flex justify-between border-t pt-3 text-lg"><span>Total cost</span><b>{money(total)}</b></div><div className="mt-2 flex justify-between text-indigo-700"><span>Unit cost</span><b>{money(unitCost)}</b></div></div>
    <button disabled={saving||!selected} onClick={post} className="h-12 w-full rounded-xl bg-indigo-600 font-semibold text-white disabled:opacity-50">{saving?"Posting…":"Post Production"}</button>
   </div></section>
  </div>
  <section className="mt-6 rounded-2xl border bg-white"><div className="border-b px-6 py-4"><h2 className="font-bold">Production Register</h2><p className="mt-1 text-xs text-slate-500">Posted production vouchers and their reversible stock/accounting status.</p></div><div className="overflow-x-auto"><table className="w-full text-sm"><thead className="bg-slate-50 text-left text-xs uppercase tracking-wide text-slate-500"><tr><th className="px-6 py-3">Voucher</th><th className="px-6 py-3">Date</th><th className="px-6 py-3">Finished Item</th><th className="px-6 py-3 text-right">Qty</th><th className="px-6 py-3 text-right">Unit Cost</th><th className="px-6 py-3 text-right">Total</th><th className="px-6 py-3">Status</th><th className="px-6 py-3 text-right">Action</th></tr></thead><tbody className="divide-y">{productions.map(p=><tr key={p.id}><td className="px-6 py-3 font-semibold">{p.voucherNumber}</td><td className="px-6 py-3">{p.date}</td><td className="px-6 py-3">{p.itemName}</td><td className="px-6 py-3 text-right">{p.quantity}</td><td className="px-6 py-3 text-right">{money(p.unitCost)}</td><td className="px-6 py-3 text-right font-semibold">{money(p.totalCost)}</td><td className="px-6 py-3"><span className={`rounded-full px-2.5 py-1 text-xs font-semibold ${p.status==="cancelled"?"bg-red-50 text-red-700":"bg-emerald-50 text-emerald-700"}`}>{p.status}</span></td><td className="px-6 py-3 text-right">{p.status==="posted"&&<button onClick={()=>cancel(p.id)} disabled={cancelling===p.id} className="rounded-lg border border-red-200 px-3 py-1.5 text-xs font-semibold text-red-700 disabled:opacity-50">{cancelling===p.id?"Cancelling…":"Cancel"}</button>}</td></tr>)}{!productions.length&&<tr><td colSpan={8} className="px-6 py-10 text-center text-slate-500">No production vouchers in the active financial year.</td></tr>}</tbody></table></div></section>
 </div></main></div></AuthGate>;
}
